import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export function CalendarPanel(){
 const [emailStatus,setEmailStatus]=useState([]),[action,setAction]=useState(null),[newStart,setNewStart]=useState(''),[holidayText,setHolidayText]=useState('');
 const [data,setData]=useState(null),[bookings,setBookings]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 async function load(){setError('');try{const responses=await Promise.all([fetch('/api/studio/calendar'),fetch('/api/studio/calendar/bookings'),fetch('/api/studio/calendar/email-status')]);const [connection,appointments,mail]=await Promise.all(responses.map(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error||'Calendar could not load.');return b;}));setData(connection);setHolidayText((connection.schedule.holidays||[]).join('\n'));setBookings(appointments.bookings||[]);setEmailStatus(mail.emails||[]);}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function manage(e){e.preventDefault();setSaving(true);setError('');setNotice('');try{const response=await fetch('/api/studio/calendar/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...action,...(action.action==='reschedule'?{start:new Date(newStart+':00+03:30').toISOString()}: {})})});const body=await response.json();if(!response.ok)throw Error(body.error||'Appointment could not be updated.');setAction(null);setNotice(body.cancelled?'Appointment cancelled. Google notifies the guest.':'Appointment rescheduled. Google notifies the guest.');await load();}catch(e){setError(e.message);}finally{setSaving(false);}}
 async function sendQueuedEmails(){setSaving(true);setError('');setNotice('');try{const response=await fetch('/api/studio/calendar/email/send-queued',{method:'POST'});const body=await response.json();if(!response.ok)throw Error(body.error||'Emails could not be processed. Try again.');await load();setNotice('Queued emails processed. Check each appointment for its sending status.');}catch(e){setError(e.message);}finally{setSaving(false);}}
 const patch=(key,value)=>setData(d=>({...d,schedule:{...d.schedule,[key]:value}}));
 async function save(e){e.preventDefault();setSaving(true);setError('');setNotice('');try{const response=await fetch('/api/studio/calendar/schedule',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data.schedule,holidays:holidayText.split(/\n/).map(d=>d.trim()).filter(Boolean)})});const body=await response.json();if(!response.ok)throw Error(body.error);setData(d=>({...d,schedule:body.schedule}));setNotice('Working hours saved.');}catch(e){setError(e.message||'Working hours could not be saved.');}finally{setSaving(false);}}
 return <div className="cms-operations"><div className="cms-heading"><div><span className="cms-eyebrow">NATIVE BOOKING · GOOGLE CALENDAR</span><h1>Time for a conversation.</h1><p>Visitors book inside Desartly. Google Calendar checks conflicts and receives each confirmed appointment.</p></div><a className="cms-primary" href="https://book.desartly.info" target="_blank" rel="noreferrer">Preview booking →</a></div>
  {error&&<p className="cms-error" role="alert">{error} <button type="button" onClick={load}>Reload calendar</button></p>}{notice&&<p role="status">{notice}</p>}
  <section className="cms-panel cms-form"><div className="cms-calendar-connection"><div><span className={'cms-calendar-status'+(data?.connected?' is-connected':'')}>{data?.connected?'Connected':data?'Connection needed':'Loading…'}</span><h2>Google Calendar</h2><p>Calendar permissions are used to check busy times and create briefing and mentorship appointments. Visitors never see your calendar or other event details.</p></div>{data?.configured?<a className="cms-primary" href="/api/studio/calendar/connect">{data.connected?'Reconnect Google Calendar':'Connect Google Calendar'} ↗</a>:<span className="cms-calendar-setup">Google API setup required</span>}</div>{data&&!data.configured&&<details className="cms-calendar-setup-details"><summary>Connection setup</summary><p>Create a Web application OAuth client in your Google Cloud project with Calendar API enabled. Store its Client ID and Client Secret securely on the server.</p><label>Authorised redirect URI<input readOnly value="https://desartly.vercel.app/api/studio/calendar/callback"/></label><p>Then connect the calendar here. Booking stays unavailable until Google grants access.</p><a href="https://console.cloud.google.com/apis/credentials" target="_blank" rel="noreferrer">Open Google Cloud credentials ↗</a></details>}</section>
  {data&&<section className="cms-panel cms-form"><div className="cms-calendar-connection"><div><h2>Booking emails</h2><p>Send each new booking, project brief and meeting link to {data.ownerEmail?.address||'komeilipv@gmail.com'}. Emails are sent automatically after the booking is confirmed.</p><p>{data.ownerEmail?.provider==='resend'?'Domain email is connected: '+data.ownerEmail.sender:data.ownerEmail?.connected?'Gmail sending is connected.':'Connect Gmail to receive booking emails. Calendar booking is already separate from this connection.'}</p>{data.ownerEmail?.provider!=='resend'&&<p>Requests permission to send email and verify your account address. Desartly does not request access to read your inbox.</p>}</div>{data.configured&&data.ownerEmail?.provider!=='resend'&&<a className="cms-primary" href="/api/studio/calendar/email/connect">{data.ownerEmail?.connected?'Reconnect booking emails':'Connect booking emails'} ↗</a>}</div>{data.ownerEmail?.connected&&<button type="button" className="cms-primary" disabled={saving} onClick={sendQueuedEmails}>{saving?'Processing…':'Send queued emails'}</button>}</section>}
  {data&&<form className="cms-panel cms-form" onSubmit={save}><h2>Your working hours</h2><p>These hours control the website booking calendar. Existing Google appointments automatically block conflicting times. Google’s appointment-schedule hours are managed separately.</p><div className="cms-calendar-day-picker">{days.map((day,index)=><label key={day}><input type="checkbox" checked={data.schedule.days.includes(index)} onChange={e=>patch('days',e.target.checked?[...data.schedule.days,index]:data.schedule.days.filter(d=>d!==index))}/>{day.slice(0,3)}</label>)}</div><div className="cms-calendar-settings-grid"><label>From<select value={data.schedule.startHour} onChange={e=>patch('startHour',Number(e.target.value))}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label>Until<select value={data.schedule.endHour} onChange={e=>patch('endHour',Number(e.target.value))}>{Array.from({length:24},(_,i)=>i+1).map(h=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label>Minimum notice (hours)<input type="number" required min="1" max="168" value={data.schedule.noticeHours} onChange={e=>patch('noticeHours',Number(e.target.value))}/></label><label>Buffer between meetings (minutes)<input type="number" min="0" max="120" required value={data.schedule.bufferMinutes||0} onChange={e=>patch('bufferMinutes',Number(e.target.value))}/></label><label>Days off (one YYYY-MM-DD per line)<textarea rows={4} value={holidayText} onChange={e=>setHolidayText(e.target.value)}/></label><label>Google calendar ID<input required maxLength={250} value={data.schedule.calendarId} onChange={e=>patch('calendarId',e.target.value)}/></label></div><p>30-minute calls · Next 30 days · Asia/Tehran. Use “primary” for your main Google calendar.</p><button className="cms-primary" disabled={saving}>{saving?'Saving…':'Save working hours'}</button></form>}
  {action&&<form className="cms-panel cms-form" onSubmit={manage}><h2>{action.action==='cancel'?'Cancel this appointment?':'Choose a new time'}</h2><p>Google will send the guest an update. All times use Tehran time.</p>{action.action==='reschedule'&&<label>New date and time · Tehran<input required type="datetime-local" step="1800" value={newStart} onChange={e=>setNewStart(e.target.value)}/></label>}<button className="cms-primary" disabled={saving}>{saving?'Updating…':action.action==='cancel'?'Confirm cancellation':'Confirm new time'}</button><button type="button" disabled={saving} onClick={()=>setAction(null)}>Keep current appointment</button></form>}
  <section className="cms-panel cms-form"><h2>Website appointments</h2>{bookings.length?<div className="cms-calendar-bookings">{bookings.map(b=><article key={b.id}><div><strong>{b.brief.name} · {b.brief.company}</strong><span>{new Intl.DateTimeFormat('en',{timeZone:'Asia/Tehran',dateStyle:'medium',timeStyle:'short'}).format(new Date(b.start_at))} · Tehran</span><small>{b.status==='confirmed'?'Confirmed in Google Calendar':'Confirmation pending — check Google Calendar'}</small>{b.status==='confirmed'&&<small>{({sent:'Booking email accepted by mail provider',sending:'Booking email is sending',pending:'Booking email is queued',failed:'Booking email failed — check the email connection',uncertain:'Email delivery is uncertain — check provider delivery logs before sending again'})[emailStatus.find(e=>e.booking_id===b.id)?.status]||'Booking email awaits the next scan'}</small>}</div><details><summary>{b.brief.meetingType==='mentorship'?'Mentorship session':'Project briefing'}</summary><p>{b.brief.email} · {b.brief.services.join(', ')} · {b.brief.industry}</p><p>{b.brief.message}</p></details>{b.status==='confirmed'&&<div className="cms-calendar-actions"><button type="button" disabled={saving} onClick={()=>{setAction({id:b.id,action:'reschedule'});setNewStart('');}}>Reschedule</button><button type="button" disabled={saving} onClick={()=>setAction({id:b.id,action:'cancel'})}>Cancel appointment</button></div>}{b.confirmation?.meetingUrl&&<a href={b.confirmation.meetingUrl} target="_blank" rel="noreferrer">Google Meet ↗</a>}</article>)}</div>:<p>Confirmed website bookings and their briefs will appear here.</p>}<a href="https://calendar.google.com/calendar/u/0/r/agenda" target="_blank" rel="noreferrer">Manage appointments in Google Calendar ↗</a></section>
 </div>;
}
