export const creativeSeasons=[
 ['First spark','جرقهٔ اول','Discover your voice'],['Visual explorer','کاوشگر تصویر','Explore new fields'],['System builder','سازندهٔ سیستم','Connect ideas and craft'],['Story architect','معمار روایت','Shape meaningful stories'],['Brand conductor','رهبر ارکستر برند','Direct a visual family'],['Experience director','کارگردان تجربه','Connect brand and product'],['Cross-industry thinker','متفکر میان‌رشته‌ای','Expand across industries'],['Creative mentor','منتور خلاق','Turn learning into practice'],['Culture shaper','شکل‌دهندهٔ فرهنگ','Build an enduring point of view'],['Art-direction legacy','میراث آرت‌دایرکشن','Sustain a diverse creative practice']
].map(([name,fa,description],i)=>({number:i+1,name,fa,description,from:i*10+1,to:(i+1)*10}));
export const progressLevels=Array.from({length:100},(_,i)=>({number:i+1,name:creativeSeasons[Math.floor(i/10)].name,threshold:Math.round(100*i+12*i*i),season:Math.floor(i/10)+1}));
const key=v=>String(v||'').normalize('NFKC').trim().toLowerCase().replace(/\s+/g,' ');
const distinct=items=>new Set(items.map(key).filter(Boolean)).size;
const unique=items=>[...new Map(items.filter(x=>!x.hidden&&!x.archived).map((x,i)=>[x.id||'missing-'+i,x])).values()];
export function credentialTopic(c){if(c.category||c.topic||c.subject)return c.category||c.topic||c.subject;const t=key(c.title||c.name);if(/3d|model|blender|cinema|poly/.test(t))return '3D & modeling';if(/ai|midjourney|prompt|artificial/.test(t))return 'AI & creative tools';if(/ux|ui|product|interaction/.test(t))return 'Product & UX';if(/brand|identity|logo/.test(t))return 'Brand & identity';if(/market|business|strategy/.test(t))return 'Strategy & marketing';if(/motion|animation|video/.test(t))return 'Motion & storytelling';if(/typograph|type|letter/.test(t))return 'Typography';return 'Design foundations';}
export function creativeJourney({projects=[],articles=[],certificates=[]}={}){
 const p=unique(projects),a=unique(articles),c=unique(certificates),counts={projects:p.length,industries:distinct(p.map(x=>x.industry)),disciplines:distinct(p.map(x=>x.discipline||x.category)),personalities:distinct(p.map(x=>x.brandPersonality)),articles:a.length,topics:distinct(a.flatMap(x=>[x.category,...(x.tags||[])])),credentials:c.length,credentialTopics:distinct(c.map(credentialTopic)),issuers:distinct(c.map(x=>x.issuer))};
 const tracks=[['projects','Project collection',[1,5,10,25,50,100,250],30],['industries','Industry explorer',[1,3,5,10,20,30,50],150],['disciplines','Creative range',[1,2,3],300],['personalities','Brand expression',[1,3,5],120],['articles','Field-note author',[1,5,10,25,50,100],50],['topics','Curious mind',[1,3,5,10,20,40],100],['credentials','Lifelong learner',[1,5,10,25,50,100],40],['credentialTopics','Learning range',[1,3,5,8,12,20],100],['issuers','Learning networks',[1,3,5,10,20],60]];
 const achievements=tracks.flatMap(([id,title,targets,weight])=>targets.map(target=>({id:'journey-'+id+'-'+target,title:title+' · '+target,current:Math.min(counts[id],target),target,xp:Math.round(weight*target/2)})));
 const rewards=tracks.map(([id,title,,weight])=>({id,title,count:counts[id],xp:counts[id]*weight,pointsPerItem:weight}));
 return {counts,rewards,achievements,seasons:creativeSeasons,xp:rewards.reduce((n,r)=>n+r.xp,0)+achievements.filter(a=>a.current>=a.target).reduce((n,a)=>n+a.xp,0)};
}
