import React,{useEffect,useRef,useState} from 'react';
import {Mail,Send,FileText,Trash2,Plus,RefreshCw,ArrowLeft,ArrowRight,Star,Archive,Eye,LayoutTemplate,Reply,Forward,Check,X,Search} from 'lucide-react';
import {api} from './context.jsx';
import {mailTemplates,mailDesignHtml} from '../mail-design.js';
import './mailbox.css';
const folders=[['inbox','All incoming',Mail],['email','Email',Mail],['briefs','Project briefs',FileText],['starred','Starred',Star],['sent','Sent',Send],['drafts','Drafts',FileText],['archive','Archive',Archive],['trash','Trash',Trash2]];
const parse=(s,fallback)=>{try{return JSON.parse(s);}catch{return fallback;}};
const blank=()=>({id:crypto.randomUUID(),recipient:'',cc:'',bcc:'',subject:'',body:'',template:'letter',fields:{}});
const subjects={booking:'Your conversation with Desartly is confirmed',mentorship:'Your mentorship session with Desartly',kickoff:'A new chapter together — Desartly',completion:'Your project, brought to life — Desartly',proposal:'A proposal for your next chapter — Desartly',letter:''};
const bodies={booking:'Thank you for making time for a conversation. Your session is confirmed. You can find the details below.\n\nLooking forward to speaking with you,\nAli',mentorship:'I’m looking forward to our mentorship session. Bring your questions, ideas and anything you would like us to explore together.\n\nSee you soon,\nAli',kickoff:'I’m delighted to begin this project together. Thank you for your trust. Here is our starting point and the next step.\n\nLet’s make something meaningful,\nAli',completion:'Thank you for the collaboration and trust throughout this project. It has been a pleasure bringing this work to life together. The handover details are below.\n\nWith appreciation,\nAli',proposal:'Thank you for sharing your vision. I’ve put together a proposal outlining the scope, timeline and investment for our collaboration.\n\nPlease take a look and let me know your thoughts.\n\nBest,\nAli',letter:''};
export function Mailbox({refreshStudio}){
 const [folder,setFolder]=useState('inbox'),[data,setData]=useState(null),[selected,setSelected]=useState(null),[compose,setCompose]=useState(null),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[unread,setUnread]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[gallery,setGallery]=useState(false),[previewSize,setPreviewSize]=useState('desktop'),[copies,setCopies]=useState(false),[discard,setDiscard]=useState(null);
 const requestNumber=useRef(0);
 async function load(){const n=++requestNumber.current;try{const result=await api('/api/studio/mail?'+new URLSearchParams({folder,q:query,offset:String(offset),unread:unread?'1':'0'}));if(n===requestNumber.current)setData(result);}catch(e){if(n===requestNumber.current)setError(e.message);}}
 useEffect(()=>{load();return()=>{requestNumber.current++;};},[folder,query,offset,unread]);
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setOffset(0);},250);return()=>clearTimeout(timer);},[search]);
 async function action(path,body){setBusy(true);setError('');setNotice('');try{await api(path,body);await load();return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 const patch=value=>{setCompose(c=>({...c,...value}));setReview(false);setNotice('');};
 const leave=next=>{if(compose){setDiscard(()=>next);}else next();};
 function fresh(template='letter'){setCompose({...blank(),template,subject:subjects[template],body:bodies[template]});setReview(false);setGallery(false);setSelected(null);setCopies(false);setNotice('');}
 function useTemplate(id){patch({template:id,subject:!compose.subject||compose.subject===subjects[compose.template]?subjects[id]:compose.subject,body:!compose.body||compose.body===bodies[compose.template]?bodies[id]:compose.body,fields:compose.fields});setGallery(false);}
 function open(m){leave(()=>{setCompose(null);setSelected(m);if(m.unread&&m.source!=='brief')action('/api/studio/mail/update',{id:m.id,action:'read'});});}
 async function update(actionName){if(await action('/api/studio/mail/update',{id:selected.id,action:actionName})){if(['trash','restore','archive'].includes(actionName))setSelected(null);else setSelected({...selected,starred:actionName==='star'?1:actionName==='unstar'?0:selected.starred,unread:actionName==='unread'?1:0});}}
 function respond(forward=false){setReview(false);setCopies(false);setCompose({ ...blank(),recipient:forward?'':(selected.direction==='inbound'?selected.sender.match(/<([^>]+)>/)?.[1]||selected.sender:selected.recipient),subject:(forward?'Fwd: ':'Re: ')+selected.subject.replace(/^(Re: |Fwd: )/i,''),body:'\n\n— '+(forward?'Forwarded message':'Previous message')+' —\nFrom: '+selected.sender+'\nDate: '+new Date(selected.created_at).toLocaleString()+'\nSubject: '+selected.subject+'\n\n'+selected.body});}
 const activeTemplate=mailTemplates.find(t=>t.id===compose?.template)||mailTemplates[0];
 const messages=data?.messages||[];
 const briefFields=selected?.source==='brief'?parse(selected.brief_fields,{}):null;
 async function reviewBrief(){if(await action('/api/studio/inquiry',{id:selected.id.slice(6),status:selected.status==='reviewed'?'new':'done'})){setSelected({...selected,status:selected.status==='reviewed'?'new':'reviewed'});refreshStudio?.();}}
 function replyToBrief(){fresh('proposal');setCompose(c=>({...c,recipient:briefFields.email||'',subject:'Your project brief — Desartly',body:'Hi '+(briefFields.name||'there')+',\n\nThank you for sharing your project brief.\n\nBest,\nAli'}));}

 const counts=Object.fromEntries((data?.counts||[]).map(c=>[c.folder,c]));
 const previewHtml=compose?mailDesignHtml(compose.body,compose.template,compose.fields):selected?.direction==='outbound'?mailDesignHtml(selected.body,selected.template,parse(selected.template_data,{})):null;
 return <div className="mail-workspace">
 <header className="mail-heading"><div className="mail-identity"><img src="/email/desartly-avatar.png" alt="Desartly"/><div><span>EMAIL / PROJECT BRIEFS</span><h1>Your conversations. One inbox.</h1><p>{data?.address||'Komeili@desartly.info'} <span className="mail-connected">{data?.configured?'● Connected':'○ Connecting'}</span></p></div></div><div className="cms-actions"><button onClick={()=>leave(()=>{fresh();setGallery(true);})}><LayoutTemplate size={16}/>Templates</button><button className="cms-primary" onClick={()=>leave(()=>fresh())}><Plus size={16}/>Compose</button></div></header>
 {error&&<p role="alert" className="cms-message error">{error}</p>}{notice&&<p role="status" className="cms-message">{notice}</p>}
 {discard&&<div className="mail-discard" role="alert"><p>Your current message has unsaved changes. Save it as a draft before leaving, or discard your edits.</p><button onClick={async()=>{if(await action('/api/studio/mail/draft',compose)){const next=discard;setDiscard(null);setCompose(null);next();}}}>Save draft & continue</button><button onClick={()=>{const next=discard;setDiscard(null);setCompose(null);next();}}>Discard edits</button><button onClick={()=>setDiscard(null)}>Keep editing</button></div>}
 {data&&!data.configured&&<p role="status">Sending is available after domain verification and connection are complete.</p>}
 <div className={'mail-layout '+(compose?'is-composing':'')}><aside className="mail-folders" aria-label="Mail folders"><span className="mail-nav-title">CORRESPONDENCE</span>{folders.map(([key,label,Icon])=><button key={key} aria-pressed={folder===key} disabled={busy} onClick={()=>leave(()=>{setFolder(key);setOffset(0);setSelected(null);setCompose(null);})}><Icon size={17}/><span>{label}</span>{counts[key]?.count>0&&<small>{key==='inbox'&&counts[key].unread?counts[key].unread:counts[key].count}</small>}</button>)}<div className="mail-folder-note"><img src="/email/desartly-avatar.png" alt=""/><strong>Made personal.</strong><p>Designed emails,<br/>from your own domain.</p></div></aside>
 <section className="mail-list" aria-label="Messages"><div className="mail-search"><Search size={15}/><input aria-label="Search mail" placeholder="Search your mail…" value={search} onChange={e=>setSearch(e.target.value)}/><button aria-label="Refresh mail" onClick={load}><RefreshCw size={15}/></button></div><div className="mail-list-filter"><strong>{folders.find(([key])=>key===folder)?.[1]} <small>{data?.total||0}</small></strong><label><input type="checkbox" checked={unread} onChange={e=>{setUnread(e.target.checked);setOffset(0);}}/>Unread</label></div>
 {!data?<p className="mail-loading" role="status">Opening your inbox…</p>:!messages.length?<div className="mail-empty"><Mail size={28}/><h2>{query?'No matching messages':'A little quiet here.'}</h2><p>{query?'Try another search.':'Your conversations will appear here.'}</p></div>:messages.map(m=><button key={m.id} className={'mail-row '+(m.unread?'unread ':'')+(selected?.id===m.id?'selected':'')} onClick={()=>open(m)}><span className="mail-row-meta"><span>{m.direction==='inbound'?m.sender:m.recipient||'No recipient'}</span><small>{new Date(m.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></span><strong>{m.starred?'★ ':''}{m.subject||'(No subject)'}</strong><p>{m.body.slice(0,90)}</p><small className="mail-status">{m.source==='brief'?'PROJECT BRIEF · '+m.status:m.status==='sent'?'Sent to provider':m.status}{m.template&&m.template!=='letter'?' · '+(mailTemplates.find(t=>t.id===m.template)?.name||m.template):''}</small></button>)}
 {(offset>0||(data?.total||0)>50)&&<div className="mail-pagination"><button aria-label="Previous messages" disabled={!offset} onClick={()=>setOffset(o=>Math.max(0,o-50))}><ArrowLeft size={14}/></button><small>{offset+1}–{Math.min(offset+50,data?.total||0)} of {data?.total}</small><button aria-label="Next messages" disabled={offset+50>=(data?.total||0)} onClick={()=>setOffset(o=>o+50)}><ArrowRight size={14}/></button></div>}</section>
 <section className="mail-detail" aria-label="Conversation">{compose?<>
 <div className="mail-detail-bar"><div><span className="mail-kicker">{review?'READY FOR YOUR REVIEW':'COMPOSE WITH INTENTION'}</span><h2>{review?'One last look.':'A new conversation.'}</h2></div><button aria-label="Close composer" disabled={busy} onClick={()=>leave(()=>{setCompose(null);setGallery(false);})}><X size={17}/></button></div>
 {gallery?<div className="mail-template-gallery"><div className="mail-gallery-title"><h3>Choose a starting point.</h3><p>Five designed occasions. Your voice in every one.</p></div>{mailTemplates.map(t=><button key={t.id} className={'mail-template-card '+(compose.template===t.id?'active':'')} onClick={()=>useTemplate(t.id)}><span className="mail-template-art"><img src="/email/desartly-avatar.png" alt=""/><span>{t.tag}</span><strong>{t.title}</strong><i/><i/></span><strong>{t.name}</strong><p>{t.description}</p></button>)}</div>:<form className="mail-compose" onSubmit={e=>{e.preventDefault();setReview(true);if(compose.cc||compose.bcc)setCopies(true);}}>
 <div className="mail-compose-editor"><p className="mail-from">From <strong>Ali Komeili · Desartly</strong><br/><span>{data?.address}</span></p>
 <div className="mail-template-choice"><label>Email design<select disabled={review} value={compose.template} onChange={e=>useTemplate(e.target.value)}>{mailTemplates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button type="button" disabled={review} onClick={()=>setGallery(true)}><LayoutTemplate size={16}/>Browse</button></div>
 <label>To<input required type="email" readOnly={review} placeholder="client@company.com" value={compose.recipient} onChange={e=>patch({recipient:e.target.value})}/></label><button className="mail-copy-toggle" type="button" onClick={()=>setCopies(!copies)}>{copies?'Hide':'Add'} Cc / Bcc</button>
 {copies&&['cc','bcc'].map(key=><label key={key}>{key==='cc'?'Cc':'Bcc'}<input readOnly={review} placeholder="Addresses, separated by commas" value={compose[key]} onChange={e=>patch({[key]:e.target.value})}/></label>)}
 <label>Subject<input required maxLength={250} readOnly={review} value={compose.subject} onChange={e=>patch({subject:e.target.value})}/></label>
 {activeTemplate.fields.length>0&&<fieldset className="mail-template-fields"><legend>{activeTemplate.name} details</legend>{activeTemplate.fields.map(([key,label,type])=><label key={key}>{label}<input type={type==='url'?'url':'text'} maxLength={2000} readOnly={review} placeholder={type==='url'?'https://…':label} value={compose.fields[key]||''} onChange={e=>patch({fields:{...compose.fields,[key]:e.target.value}})}/></label>)}</fieldset>}
 <label>Your message<textarea required rows={10} readOnly={review} dir="auto" placeholder="Write in your own voice…" value={compose.body} onChange={e=>patch({body:e.target.value})}/></label><small className="mail-compose-hint">Links and details appear in the designed email. Nothing is sent until you confirm.</small>
 <div className="cms-actions mail-compose-actions">{review?<><button type="button" disabled={busy} onClick={()=>setReview(false)}><ArrowLeft size={15}/>Keep editing</button><button type="button" className="cms-primary" disabled={busy||!data?.configured} onClick={async()=>{if(await action('/api/studio/mail/send',compose)){setCompose(null);setSelected(null);setReview(false);setFolder('sent');setOffset(0);setNotice('Email accepted by the provider. It is saved in Sent.');}}}><Send size={15}/>{busy?'Sending…':'Confirm & send'}</button></>:<><button type="button" disabled={busy} onClick={async()=>{if(await action('/api/studio/mail/draft',compose)){setCompose(null);setFolder('drafts');setOffset(0);setNotice('Draft saved. Your template and details are preserved.');}}}><FileText size={15}/>Save draft</button><button type="submit" className="cms-primary" disabled={!data?.configured}><Eye size={15}/>Review & send</button></>}</div></div>
 <div className="mail-preview-panel"><div className="mail-preview-bar"><span><Eye size={14}/>LIVE EMAIL PREVIEW</span><div><button type="button" aria-pressed={previewSize==='desktop'} onClick={()=>setPreviewSize('desktop')}>Desktop</button><button type="button" aria-pressed={previewSize==='mobile'} onClick={()=>setPreviewSize('mobile')}>Mobile</button></div></div><iframe title="Designed email preview" sandbox="" referrerPolicy="no-referrer" className={'mail-preview '+previewSize} srcDoc={previewHtml}/><p className="mail-preview-note">The same design is sent to your recipient. Email applications may render spacing differently.</p></div>
 </form>}
 </>:selected?.source==='brief'?<><div className="mail-detail-bar"><div><span className="mail-kicker">WEBSITE / PROJECT BRIEF</span><h2>{briefFields.name||'Project enquiry'}</h2></div><span className="cms-status">{selected.status==='reviewed'?'Reviewed':'New'}</span></div><p className="mail-address">{briefFields.email}<br/>{new Date(selected.created_at).toLocaleString()}</p><dl className="mail-brief-fields">{Object.entries(briefFields).filter(([key,value])=>value&&!['name','email','website_trap'].includes(key)).map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd dir="auto">{String(value)}</dd></div>)}</dl><div className="cms-actions"><button className="cms-primary" onClick={replyToBrief}><Reply size={15}/>Reply with proposal</button><button disabled={busy} onClick={reviewBrief}>{selected.status==='reviewed'?'Mark as new':'Mark reviewed'}</button></div></>:selected?<><div className="mail-detail-bar"><div><span className="mail-kicker">{selected.direction==='inbound'?'RECEIVED':'YOUR CORRESPONDENCE'}</span><h2>{selected.subject||'(No subject)'}</h2></div><button aria-label={selected.starred?'Remove star':'Star message'} disabled={busy} onClick={()=>update(selected.starred?'unstar':'star')}><Star size={18} fill={selected.starred?'currentColor':'none'}/></button></div><p className="mail-address">From: {selected.sender}<br/>To: {selected.recipient}{parse(selected.cc,[]).length>0&&<><br/>Cc: {parse(selected.cc,[]).join(', ')}</>}<br/>{new Date(selected.created_at).toLocaleString()} · {selected.status==='sent'?'Sent to provider':selected.status}</p>
 <div className="mail-message-tools">{folder==='trash'?<button disabled={busy} onClick={()=>update('restore')}>Restore message</button>:<><button disabled={busy} onClick={()=>update('unread')}><Mail size={15}/>Mark unread</button>{selected.status!=='draft'&&<button disabled={busy} onClick={()=>update(folder==='archive'?'restore':'archive')}><Archive size={15}/>{folder==='archive'?'Restore':'Archive'}</button>}<button disabled={busy} onClick={()=>update('trash')}><Trash2 size={15}/>Trash</button></>}</div>
 {previewHtml&&selected.template&&selected.template!=='letter'?<iframe title={selected.status==='draft'?'Draft email design':'Sent email design'} sandbox="" referrerPolicy="no-referrer" className="mail-preview sent" srcDoc={previewHtml}/>:<div className="mail-body" dir="auto">{selected.body}</div>}
 {folder!=='trash'&&<div className="cms-actions">{selected.status==='draft'?<button className="cms-primary" onClick={()=>{setReview(false);setCompose({id:selected.id,recipient:selected.recipient,subject:selected.subject,body:selected.body,template:selected.template||'letter',fields:parse(selected.template_data,{}),cc:parse(selected.cc,[]).join(', '),bcc:parse(selected.bcc,[]).join(', ')});setCopies(!!(parse(selected.cc,[]).length||parse(selected.bcc,[]).length));}}><FileText size={15}/>Continue draft</button>:<><button className="cms-primary" onClick={()=>respond()}><Reply size={15}/>Reply</button><button onClick={()=>respond(true)}><Forward size={15}/>Forward</button></>}</div>}</>:<div className="mail-welcome"><img src="/email/desartly-avatar.png" alt="Desartly"/><span className="mail-kicker">YOUR PRIVATE CORRESPONDENCE</span><h2>A thoughtful email<br/>goes a long way.</h2><p>From first conversations to final handovers.<br/>Write something that feels like you.</p><button className="cms-primary" onClick={()=>{fresh();setGallery(true);}}><LayoutTemplate size={16}/>Explore email templates</button><div className="mail-welcome-tags">BOOKING · MENTORSHIP · PROJECTS · PROPOSALS</div></div>}</section>
 </div></div>;
}
