import React,{useEffect,useState} from 'react';
import {Mail,Send,FileText,Trash2,Plus,RefreshCw,ArrowLeft} from 'lucide-react';
import {api} from './context.jsx';
import './mailbox.css';
export function Mailbox(){
 const [folder,setFolder]=useState('inbox'),[data,setData]=useState(null),[selected,setSelected]=useState(null),[compose,setCompose]=useState(null),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false);
 async function load(){try{setData(await api('/api/studio/mail?folder='+folder));}catch(e){setError(e.message);}}
 useEffect(()=>{setSelected(null);load();},[folder]);
 async function action(path,body){setBusy(true);setError('');try{await api(path,body);await load();return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 const messages=(data?.messages||[]).filter(m=>(m.subject+' '+m.sender+' '+m.recipient+' '+m.body).toLowerCase().includes(search.toLowerCase()));
 const fresh=()=>{setCompose({id:crypto.randomUUID(),recipient:'',subject:'',body:''});setPreview(false);};
 return <div className="mail-workspace"><header className="mail-heading"><div><span>DESARTLY MAIL</span><h1>A place for conversations.</h1><p>{data?.address||'Komeili@desartly.info'}</p></div><button className="cms-primary" onClick={fresh}><Plus size={16}/>Compose</button></header>
 {error&&<p role="alert" className="cms-message error">{error}</p>}
 {data&&!data.configured&&<section className="cms-panel mail-connection"><strong>Connect your domain email</strong><p>Your inbox is ready. Sending and receiving start after Resend credentials and DNS verification are complete.</p></section>}
 {data?.configured&&!data.receivingConfigured&&<p role="status">Sending credentials are present. Incoming mail still needs its verified webhook and MX record.</p>}
 <div className="mail-layout"><aside className="mail-folders" aria-label="Mail folders">{[['inbox','Inbox',Mail],['sent','Sent',Send],['drafts','Drafts',FileText],['trash','Trash',Trash2]].map(([key,label,Icon])=><button key={key} aria-pressed={folder===key} onClick={()=>{setFolder(key);setCompose(null);}}><Icon size={17}/>{label}</button>)}</aside>
 <section className="mail-list" aria-label="Messages"><div className="mail-search"><input aria-label="Search mail" placeholder="Search conversations…" value={search} onChange={e=>setSearch(e.target.value)}/><button aria-label="Refresh mail" onClick={load}><RefreshCw size={16}/></button></div>{!data?<p>Opening your inbox…</p>:!messages.length?<div className="mail-empty"><Mail size={28}/><h2>{search?'No matching messages':'No messages yet'}</h2><p>{folder==='inbox'?'New conversations will appear here.':'This folder is empty.'}</p></div>:messages.map(m=><button key={m.id} className={'mail-row '+(m.unread?'unread ':'')+(selected?.id===m.id?'selected':'')} onClick={()=>{setCompose(null);setSelected(m);if(m.unread)action('/api/studio/mail/update',{id:m.id,action:'read'});}}><span>{m.direction==='inbound'?m.sender:m.recipient}</span><strong>{m.subject}</strong><small>{new Date(m.created_at).toLocaleDateString()} · {m.status}</small><p>{m.body.slice(0,90)}</p></button>)}</section>
 <section className="mail-detail" aria-label="Conversation">{compose?<><div className="mail-detail-bar"><h2>{preview?'Review your email':'New conversation'}</h2><button onClick={()=>{setCompose(null);setPreview(false);}}>Close</button></div><form className="cms-form" onSubmit={e=>{e.preventDefault();setPreview(true);}}><p>From: {data?.address}</p>{['recipient','subject'].map(key=><label key={key}>{key==='recipient'?'To':'Subject'}<input required type={key==='recipient'?'email':'text'} readOnly={preview} value={compose[key]} onChange={e=>setCompose({...compose,[key]:e.target.value})}/></label>)}<label>Message<textarea required rows={14} readOnly={preview} value={compose.body} onChange={e=>setCompose({...compose,body:e.target.value})}/></label><div className="cms-actions">{preview?<><button type="button" onClick={()=>setPreview(false)}><ArrowLeft size={16}/>Edit</button><button type="button" className="cms-primary" disabled={busy||!data?.configured} onClick={async()=>{if(await action('/api/studio/mail/send',compose)){setCompose(null);setPreview(false);setFolder('sent');}}}>Confirm and send</button></>:<><button type="button" disabled={busy} onClick={async()=>{if(await action('/api/studio/mail/draft',compose)){setCompose(null);setFolder('drafts');}}}>Save draft</button><button type="submit" className="cms-primary" disabled={!data?.configured}>Review email</button></>}</div></form></>:selected?<><div className="mail-detail-bar"><h2>{selected.subject}</h2><button disabled={busy} onClick={async()=>{if(await action('/api/studio/mail/update',{id:selected.id,action:folder==='trash'?'restore':'trash'}))setSelected(null);}}>{folder==='trash'?'Restore':'Move to trash'}</button></div><p className="mail-address">From: {selected.sender}<br/>To: {selected.recipient}<br/>{new Date(selected.created_at).toLocaleString()} · {selected.status}</p><div className="mail-body" dir="auto">{selected.body}</div>{folder!=='trash'&&<button className="cms-primary" onClick={()=>{setPreview(false);setCompose(selected.status==='draft'?{id:selected.id,recipient:selected.recipient,subject:selected.subject,body:selected.body}:{id:crypto.randomUUID(),recipient:selected.direction==='inbound'?selected.sender.match(/<([^>]+)>/)?.[1]||selected.sender:selected.recipient,subject:selected.subject.startsWith('Re:')?selected.subject:'Re: '+selected.subject,body:'\n\n—\n'+selected.body});}}>{selected.status==='draft'?'Continue draft':'Reply'}</button>}</>:<div className="mail-empty"><Mail size={32}/><h2>Your next conversation.</h2><p>Select a message or write something new.</p></div>}</section></div></div>;
}
