export const marketingStages=[['awareness','Awareness'],['consideration','Consideration'],['acquisition','Acquisition'],['conversion','Conversion'],['retention','Retention & expansion']];
const definitions=[
['foundation','Core channels','acquisition','LinkedIn و شبکه حرفه‌ای|ایمیل سرد هدفمند|همکاری با آژانس‌ها|معرفی مشتریان قبلی|وب‌سایت و SEO|Case Study و پورتفولیو|Instagram ارگانیک|PR و جوایز طراحی|Google Search Ads|LinkedIn Ads'],
['events','B2B & events','acquisition','جلسات B2B و Business Matching|اسپانسرینگ رویدادهای تخصصی|برگزاری رویداد مشترک با یک شریک تجاری|شرکت در Pitch Eventها|حضور در Demo Day شتاب‌دهنده‌ها'],
['products','Product-led marketing','consideration','فایل‌های رایگان Brand Brief|قالب‌های Brand Strategy|قالب‌های Brand Guidelines|قالب‌های Presentation|قالب‌های Pitch Deck|قالب‌های طراحی بسته‌بندی|ابزار ارزیابی سلامت برند|Brand Audit آنلاین|ماشین‌حساب تخمینی هزینه برندسازی|چک‌لیست راه‌اندازی برند|بانک منابع طراحی|گزارش‌های قابل دانلود|ابزارهای کوچک مبتنی بر AI برای بررسی هویت بصری|Newsletter تخصصی|دوره کوتاه برندینگ|ورکشاپ پولی|مشاوره اولیه یا جلسه تشخیصی پولی|محصولات دیجیتال در مارکت‌پلیس‌ها|کتاب یا مجله اختصاصی استودیو|کیت فیزیکی نمونه متریال و بسته‌بندی'],
['personal','Talent & personal brand','awareness','LinkedIn شخصی بنیان‌گذار|Instagram شخصی|Behance شخصی|Dribbble شخصی|وب‌سایت شخصی|خبرنامه شخصی|انتشار دیدگاه‌های حرفه‌ای|نمایش فرایند تصمیم‌گیری خلاقه|تحلیل پروژه‌های واقعی|انتشار تجربه مدیریت پروژه|روایت چالش‌های کسب‌وکار طراحی|مصاحبه و پادکست شخصی|سخنرانی به‌عنوان متخصص|منتورینگ|تدریس|مشارکت در پروژه‌های مشترک با افراد شناخته‌شده|همکاری با Creative Directorها و مشاوران برند|انتشار مقالات با نام شخصی|مشارکت در بحث‌های تخصصی مدیران'],
['directories','Marketplaces & directories','consideration','Behance|Dribbble|Clutch|DesignRush|The Manifest|Awwwards|CSS Design Awards|World Brand Design Society|Packaging of the World|Dieline|BP&O|Creative Boom|It’s Nice That|Communication Arts|Ads of the World|Lürzer’s Archive|Working Not Working|Contra|Upwork|Fiverr Pro|Malt|Sortlist|Agency Spotter|GoodFirms|دایرکتوری‌های محلی آژانس‌ها|پلتفرم‌های تأمین‌کنندگان شرکت‌های بزرگ|مارکت‌پلیس‌های مناقصه و درخواست پروپوزال'],
['sales','Sales enablement','conversion','پروپوزال اختصاصی|معرفی‌نامه خدمات|Deck معرفی استودیو|پورتفولیوی PDF|Case Study متناسب با صنعت مشتری|ویدئوی معرفی|نمونه فیزیکی طراحی و بسته‌بندی|جلسه کشف نیاز|ورکشاپ تشخیص مسئله|Brand Audit|پیشنهاد پروژه آزمایشی پولی|پیشنهاد Retainer ماهانه|قرارداد همکاری بلندمدت|Follow-up منظم|CRM و مدیریت قیف فروش|اتوماسیون ایمیل|سیستم امتیازدهی به سرنخ‌ها|سیستم ثبت دلایل برد و باخت Pitch|صفحه اختصاصی برای هر مشتری بالقوه|ارائه نتایج و شاخص‌های تجاری پروژه‌های قبلی'],
['lifecycle','Lifecycle marketing','retention','ایمیل پیگیری بعد از تحویل پروژه|بررسی رضایت مشتری|معرفی خدمات مکمل|پیشنهاد توسعه هویت بصری|طراحی کمپین تبلیغاتی برای مشتری برندینگ|طراحی بسته‌بندی جدید برای مشتری قبلی|قرارداد ماهانه Creative Support|قرارداد سالانه طراحی|پیشنهاد بازنگری هویت برند|یادآوری زمان به‌روزرسانی بسته‌بندی|پیشنهاد کمپین مناسبتی|برنامه وفاداری مشتریان|برنامه معرفی مشتری جدید|انتشار دستاوردهای مشترک|دعوت مشتریان سابق به رویدادهای اختصاصی|نگهداری ارتباط با مشتریان غیرفعال'],
['partners','Co-marketing','acquisition','انتشار Case Study مشترک با مشتری|ساخت کمپین مشترک با برند مشتری|تولید محتوای مشترک با آژانس تبلیغاتی|وبینار مشترک با مشاور برند|مقاله مشترک با شرکت تحقیقات بازار|همکاری با چاپخانه برای معرفی راهکارهای بسته‌بندی|همکاری با استودیو موشن برای پروژه‌های یکپارچه|تولید گزارش مشترک با یک رسانه تخصصی|انتشار مصاحبه با مدیر مارکتینگ مشتری|ساخت پروژه مفهومی مشترک با برندهای منتخب|تولید محتوای آموزشی با یک پلتفرم تخصصی|همکاری با شتاب‌دهنده‌ها برای ارائه خدمات به استارتاپ‌ها'],
['experiential','Guerrilla & experiential','awareness','کمپین محیطی برای معرفی استودیو|ارسال بسته خلاقانه به مدیران منتخب|انتشار یک پروژه مفهومی غیرمنتظره|ساخت یک گزارش فیزیکی با طراحی ممتاز|نمایشگاه خیابانی یا Pop-up|نصب آثار طراحی در رویدادهای مرتبط|کمپین تعاملی آنلاین|ساخت تجربه تعاملی برند|طراحی ابزار یا سایت ویروسی|انتشار یک مطالعه موردی با روایت غیرمعمول|اجرای چالش طراحی عمومی|همکاری با هنرمندان و سازندگان محتوا|طراحی پروژه‌ای برای یک مسئله اجتماعی|تولید یک شیء یا نمونه بسته‌بندی قابل توجه و ارسال هدفمند|انتشار یک پروژه فرضی که توانایی استودیو را در یک صنعت نشان دهد'],
['creators','Influencer & creator marketing','awareness','همکاری با طراحان شناخته‌شده|همکاری با اینفلوئنسرهای کسب‌وکار|همکاری با تولیدکنندگان محتوای مارکتینگ|همکاری با مشاوران استارتاپ|حضور در پادکست‌های تخصصی|حضور در کانال‌های آموزش برندینگ|نقد یا بررسی پروژه‌های استودیو توسط افراد متخصص|ساخت ویدئوی مشترک|مصاحبه با بنیان‌گذار استودیو|همکاری با رسانه‌های طراحی|حمایت از تولید محتوای تخصصی|همکاری با تولیدکنندگان محتوای یک صنعت خاص'],
['procurement','Tender & procurement','acquisition','ثبت‌نام در پورتال تأمین‌کنندگان سازمان‌ها|شرکت در مناقصه‌های طراحی و تبلیغات|پاسخ به RFP|حضور در فهرست تأمین‌کنندگان تأییدشده|همکاری با آژانس‌های بزرگ به‌عنوان پیمانکار تخصصی|شرکت در Pitchهای برندینگ|ارتباط با Procurement Managerها|ارتباط با مدیران بازاریابی سازمان‌ها|شرکت در فراخوان‌های طراحی|همکاری با شرکت‌های بین‌المللی|ارائه اسناد صلاحیت و سوابق پروژه|ایجاد بسته مستندات حقوقی و تجاری برای همکاری سازمانی'],
['international','International marketing','acquisition','وب‌سایت انگلیسی مستقل یا دوزبانه|SEO بین‌المللی|پورتفولیوی انگلیسی|Case Studyهای انگلیسی|LinkedIn Outreach بین‌المللی|ایمیل سرد به برندهای خارجی|حضور در دایرکتوری‌های جهانی آژانس‌ها|شرکت در رویدادهای بین‌المللی|همکاری White Label با آژانس‌های خارجی|همکاری با مشاوران برند در بازار هدف|انتشار پروژه در رسانه‌های بین‌المللی طراحی|فعالیت در پلتفرم‌های جهانی پروژه‌یابی|هدف‌گیری صنایع مشخص در کشورهای هدف|همکاری با استودیوهای محلی به‌عنوان شریک اجرایی|ساخت شبکه معرفی مشتری در بازارهای خارجی|تولید محتوای تخصصی با تمرکز بر بازارهای هدف|مشارکت در مناقصه‌های بین‌المللی']
];
export const marketingChannels=definitions.map(([id,title,stage,items])=>({id,title,stage,templates:items.split('|').map((title,index)=>({id:id+'-'+String(index+1).padStart(2,'0'),channel:id,stage,title,brief:'Define one concrete deliverable, audience and next action. Record a link or short result after execution.',minutes:['procurement','products','experiential'].includes(id)?120:45}))}));
export const channelFa={foundation:'کانال‌های اصلی',events:'رویداد و ارتباط B2B',products:'محصول و منابع آموزشی',personal:'برند شخصی',directories:'پلتفرم و دایرکتوری',sales:'تبدیل به قرارداد',lifecycle:'رشد مشتریان قبلی',partners:'بازاریابی مشترک',experiential:'تجربه و کمپین خلاق',creators:'همکاری با سازندگان محتوا',procurement:'مناقصه و تأمین‌کنندگان',international:'بازار بین‌المللی'};
const actionable=[
['foundation','یک کیس استادی برای صنعت هدف آماده کن','Prepare an industry-specific case study','یک پروژه مرتبط انتخاب کن؛ مسئله، تصمیم و خروجی را با تصاویر واقعی نشان بده.','Choose a relevant project; show its problem, decisions and deliverables with actual visuals.'],
['foundation','فهرست مشتریان بالقوه را هدفمند کن','Build a focused prospect shortlist','پنج شرکت متناسب با تخصصت انتخاب کن و دلیل تناسب هرکدام را ثبت کن.','Choose five companies that fit your expertise and record why each is relevant.'],
['events','جلسه B2B را آماده کن','Prepare a B2B meeting','هدف جلسه، سه سؤال کشف نیاز و یک نمونه کار مرتبط را آماده کن.','Prepare a meeting objective, three discovery questions and one relevant project.'],
['events','ارتباط‌های رویداد را پیگیری کن','Follow up after an industry event','گفت‌وگوها را مرور کن؛ برای هر ارتباط مناسب یک قدم بعدی مشخص بنویس.','Review the conversations and define one next step for each relevant contact.'],
['products','یک قالب بریف برند بساز','Create a reusable brand brief','یک فایل قابل ویرایش با سؤال‌های کاربردی و راهنمای کوتاه استفاده آماده کن.','Produce an editable file with practical questions and a short usage guide.'],
['products','چک‌لیست راه‌اندازی برند آماده کن','Publish a brand launch checklist','موارد ضروری را به مراحل روشن تقسیم کن و یک خروجی قابل دانلود بساز.','Group essential checks into clear steps and prepare a downloadable resource.'],
['personal','یک تصمیم طراحی را روایت کن','Explain one design decision','از یک پروژه واقعی، مسئله و دلیل انتخابت را با تصویر توضیح بده.','Use a real project to explain the problem and your decision, supported by a visual.'],
['personal','یک پست تخصصی برای لینکدین بنویس','Draft a practical LinkedIn post','یک دیدگاه مشخص، مثال واقعی و سؤال مرتبط برای پایان پست آماده کن.','Draft a clear viewpoint, a concrete example and a relevant closing question.'],
['directories','پروژه منتخب را برای Behance آماده کن','Prepare a selected project for Behance','تصاویر باکیفیت، روایت کوتاه، عنوان و تگ‌های مرتبط را آماده کن.','Prepare sharp images, a concise story, a title and relevant tags.'],
['directories','پروفایل استودیو را تکمیل کن','Refresh the studio directory profile','خدمات، بازار هدف، نمونه کار و راه تماس را بازبینی کن.','Review services, target market, portfolio examples and contact information.'],
['sales','پروپوزال متناسب با مسئله بنویس','Draft a problem-specific proposal','مسئله، دامنه، خروجی، زمان‌بندی و موارد خارج از دامنه را روشن کن.','Clarify the problem, scope, deliverables, schedule and exclusions.'],
['sales','جلسه کشف نیاز را طراحی کن','Design a discovery conversation','پنج سؤال درباره هدف تجاری، مخاطب، محدودیت و معیار موفقیت آماده کن.','Prepare five questions about goals, audience, constraints and success criteria.'],
['lifecycle','رضایت مشتری قبلی را بررسی کن','Prepare a client satisfaction check-in','سؤال‌های کوتاه درباره تجربه همکاری و نیازهای جدید آماده کن.','Prepare concise questions about the collaboration and emerging needs.'],
['lifecycle','یک خدمت مکمل پیشنهاد بده','Identify a useful follow-on service','یک نیاز واقعی از پروژه قبلی پیدا کن و پیشنهاد مشخصی آماده کن.','Identify a real need related to previous work and prepare a specific recommendation.'],
['partners','کیس استادی مشترک را آماده کن','Prepare a joint case study','نقش طرفین، اجازه استفاده از محتوا و شواهد پروژه را مشخص کن.','Clarify contributions, content permissions and project evidence.'],
['partners','طرح همکاری با یک آژانس بنویس','Outline an agency partnership','تخصص مکمل، شیوه همکاری و یک پروژه آزمایشی روشن را تعریف کن.','Define complementary expertise, working arrangements and a clear pilot scope.'],
['experiential','ایده یک تجربه تعاملی را بساز','Sketch an interactive brand experience','مخاطب، رفتار مورد انتظار و ارتباط ایده با مسئله تجاری را ثبت کن.','Record the audience, intended action and connection to a business problem.'],
['experiential','بسته معرفی خلاقانه طراحی کن','Design a targeted introduction kit','یک مخاطب مشخص انتخاب کن و محتوا، دلیل ارتباط و قدم بعدی را طراحی کن.','Choose a specific audience and design the content, relevance and next action.'],
['creators','بریف همکاری محتوایی آماده کن','Prepare a creator collaboration brief','موضوع، مخاطب، خروجی و معیار ارزیابی همکاری را تعریف کن.','Define the topic, audience, deliverables and evaluation criteria.'],
['creators','پیشنهاد حضور در پادکست بنویس','Draft a specialist podcast pitch','یک موضوع مفید و سه نکته‌ای که می‌توانی با تجربه واقعی توضیح بدهی آماده کن.','Prepare a useful topic and three points grounded in actual experience.'],
['procurement','بسته صلاحیت استودیو بساز','Prepare a studio qualification pack','سوابق واقعی، خدمات، نمونه کار و مدارک مورد نیاز را فهرست و مرتب کن.','Organize actual credentials, services, project examples and required documents.'],
['procurement','تناسب یک RFP را ارزیابی کن','Evaluate an RFP opportunity','دامنه، زمان، شرایط و تناسب با تخصص را ثبت کن؛ تصمیم ورود یا انصراف بگیر.','Record scope, timing, terms and expertise fit; decide whether to proceed.'],
['international','پورتفولیوی انگلیسی را بازبینی کن','Review the English portfolio','زبان، نقش واقعی، کیفیت تصاویر و تناسب پروژه‌ها با بازار هدف را بررسی کن.','Review language, actual role, image quality and relevance to the target market.'],
['international','یک بازار خارجی را انتخاب کن','Define one international target market','صنعت، نوع مشتری و دلیل تناسب خدماتت با یک بازار مشخص را بنویس.','Define an industry, customer profile and why your services fit one specific market.']
];
for(const [channel,fa,en,briefFa,briefEn] of actionable){const c=marketingChannels.find(c=>c.id===channel),index=c.templates.filter(t=>t.id.includes('-action-')).length;for(const language of ['fa','en'])c.templates.push({id:channel+'-action-'+index+'-'+language,channel,stage:c.stage,language,title:language==='fa'?fa:en,brief:language==='fa'?briefFa:briefEn,minutes:45});}
for(const c of marketingChannels)for(const t of c.templates){t.language||=/[\u0600-\u06ff]/.test(t.title)?'fa':'en';if(!t.id.includes('-action-')&&t.language==='fa')t.brief='یک خروجی مشخص، مخاطب هدف و قدم بعدی تعریف کن؛ پس از اجرا، لینک یا یادداشت نتیجه را ثبت کن.';}
export const marketingTemplates=marketingChannels.flatMap(c=>c.templates);
export const taskStatus=task=>task.done?'done':task.status==='doing'?'doing':'todo';
export const programTemplates=[{id:'b2b',title:'B2B opportunity building',goal:'Turn relevant conversations into qualified opportunities.',templates:['personal-01','sales-05','sales-14','partners-04']},{id:'trust',title:'Authority & portfolio',goal:'Make the studio’s expertise easier to evaluate.',templates:['foundation-06','personal-07','directories-01']},{id:'retention',title:'Existing-client growth',goal:'Identify useful follow-on work with existing clients.',templates:['lifecycle-01','lifecycle-02','lifecycle-03']},{id:'global',title:'International development',goal:'Build relationships in one chosen market.',templates:['international-03','international-04','international-09']},{id:'product',title:'Useful free product',goal:'Create one reusable resource with a clear next action.',templates:['products-01','products-10','products-14']}];
export function marketingWeek(date=new Date()){const dateString=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(date),d=new Date(dateString+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+1)%7);return d.toISOString().slice(0,10);}
export function marketingMetrics(marketing={}){const tasks=marketing.tasks||[],completed=tasks.filter(t=>t.done),weeks={};for(const task of completed){const week=task.creditWeek||task.completedAt?.slice(0,10)||'legacy';weeks[week]=(weeks[week]||0)+10;}const xp=Object.values(weeks).reduce((sum,value)=>sum+Math.min(value,100),0);const outcomes=completed.reduce((a,t)=>{for(const key of ['leads','meetings','proposals','wins'])a[key]+=Number(t.outcome?.[key])||0;return a;},{leads:0,meetings:0,proposals:0,wins:0});return {xp,weeklyXp:Math.min(weeks[marketingWeek()]||0,100),weeklyCap:100,completed:completed.length,total:tasks.filter(t=>!t.archived).length,outcomes,rules:'Owner-reported execution earns 10 XP per unique completed task, capped at 100 per Tehran week. Reticking does not create new credit. Results are self-reported, not verified leads or revenue.'};}
