import React,{useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {api} from './context.jsx';
import {marketingChannels} from './marketing-catalog.js';
const date=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function MarketingSchedule({marketing,programs,busy,save}){
 const [connection,setConnection]=useState(null),[error,setError]=useState(''),[draft,setDraft]=useState(()=>marketing.schedule||{enabled:false,programId:programs[0]?.id||'',cadence:'weekly',days:[6],time:'09:00',start:date(),language:'both',channels:marketingChannels.map(c=>c.id),deadlineHours:48});
 useEffect(()=>{api('/api/studio/telegram').then(setConnection).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(marketing.schedule)setDraft(marketing.schedule);},[marketing.schedule]);
 const change=(key,value)=>setDraft(s=>({...s,[key]:value})),reports=marketing.tasks.flatMap(t=>(t.reports||[]).map(r=>({...r,title:t.title,taskId:t.id}))).sort((a,b)=>b.at.localeCompare(a.at));
 return <section className="mk-schedule"><header><div><h2>Your Telegram rhythm</h2><p>A reminder to pick a task, on your schedule. You choose the action; the bot asks for reports on tasks with deadlines.</p></div><Link to="/studio/telegram">{connection?.ownerId?'Connected owner bot':'Connect Telegram'}</Link></header>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();save('save-schedule',{schedule:draft},{close:false});}}><div className="mk-schedule-grid"><label>Program<select required value={draft.programId} onChange={e=>change('programId',e.target.value)}><option value="">Choose a program</option>{programs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Frequency<select value={draft.cadence} onChange={e=>{const cadence=e.target.value;setDraft(s=>({...s,cadence,days:cadence==='twice'?[6,2]:[s.days[0]??6]}));}}><option value="weekly">Once a week</option><option value="twice">Twice a week</option><option value="alternate">Every other day</option></select></label><label>Send time · Tehran<input type="time" required value={draft.time} onChange={e=>change('time',e.target.value)}/></label><label>Start date<input type="date" required max={new Date(Date.now()+14*86400000).toISOString().slice(0,10)} value={draft.start} onChange={e=>change('start',e.target.value)}/></label><label>Reminder language<select value={draft.language} onChange={e=>change('language',e.target.value)}><option value="both">Persian & English</option><option value="fa">Persian</option><option value="en">English</option></select></label></div>{draft.cadence!=='alternate'&&<fieldset><legend>Send days · choose {draft.cadence==='weekly'?'one':'two'}</legend><div className="mk-schedule-days">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=><label key={day}><input type="checkbox" checked={draft.days.includes(i)} onChange={e=>change('days',e.target.checked?[...draft.days,i]:draft.days.filter(d=>d!==i))}/>{day}</label>)}</div></fieldset>}<label className="mk-check"><input type="checkbox" checked={draft.enabled} disabled={!connection?.ownerId} onChange={e=>change('enabled',e.target.checked)}/>Enable pick-a-task reminders</label><p>The bot never selects or creates a task. Set a due date on a task to receive its report request at 18:00 Tehran. Missed reminder slots do not create a backlog. Use /marketing to open your active tasks.</p><button className="cms-primary" disabled={busy||!programs.length||draft.enabled&&!connection?.ownerId}>{busy?'Saving…':'Save schedule'}</button>{!programs.length&&<p>Create a program first.</p>}{marketing.schedule?.nextAt&&<p>{marketing.schedule.enabled?'Next slot: ':'Paused · next configured slot: '}{new Date(marketing.schedule.nextAt).toLocaleString('en-GB',{timeZone:'Asia/Tehran'})} · Tehran</p>}{marketing.schedule?.error&&<p role="alert">{marketing.schedule.error}</p>}</form><Link to="/studio/marketing?view=reports">Open Reports & analysis →</Link></section>;
}
