import React,{useRef,useState} from 'react';
import {Download,Upload,Archive,FolderOpen,ShieldCheck} from 'lucide-react';
import {api} from './context.jsx';
import {createMediaArchive,readMediaArchive} from './media-archive.js';
const base='/api/studio/media-backup';
export function MediaBackup({state,refresh,notify,onError}){
 const [busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[archive,setArchive]=useState(null);const picker=useRef(null),abort=useRef(null);
 async function download(){setBusy(true);abort.current=new AbortController();try{setProgress('Preparing your library…');const manifest=await api(base);const blob=await createMediaArchive(manifest,async(m,i,v)=>{const r=await fetch(base+'/file?'+new URLSearchParams({id:m.id,variant:i,source:v.source}),{signal:abort.current.signal});if(!r.ok){const e=await r.json();throw Error(e.error);}return r.arrayBuffer();},(done,total)=>setProgress(`Downloading files · ${done} / ${total}`));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`desartly-media-${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);notify('Complete media backup downloaded.');}catch(e){if(e.name!=='AbortError')onError(e);}finally{setBusy(false);setProgress('');}}
 async function select(file){if(!file)return;abort.current=null;setBusy(true);setArchive(null);setProgress('Checking every file in your backup…');try{const value=await readMediaArchive(file);setArchive(value);}catch(e){onError(e);}finally{setBusy(false);setProgress('');if(picker.current)picker.current.value='';}}
 async function restore(){setBusy(true);abort.current=new AbortController();try{const {session}=await api(base+'/restore',archive.manifest);let done=0;const total=archive.manifest.media.reduce((n,m)=>n+m.variants.length,0);for(const m of archive.manifest.media)for(let i=0;i<m.variants.length;i++){setProgress(`Restoring files · ${done} / ${total}`);const r=await fetch(base+'/restore-file?'+new URLSearchParams({session,id:m.id,variant:i}),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:archive.entries.get(m.variants[i].path),signal:abort.current.signal});if(!r.ok){const e=await r.json();throw Error(e.error);}done++;}if(abort.current.signal.aborted)throw new DOMException('Cancelled','AbortError');setProgress('Saving your library…');await api(base+'/commit?'+new URLSearchParams({session}),{});setArchive(null);await refresh();notify('Media files and folders restored.');}catch(e){if(e.name!=='AbortError')onError(e);}finally{setBusy(false);setProgress('');}}
 const bytes=state.media?.reduce((n,m)=>n+(m.variants?.reduce((sum,v)=>sum+v.size,0)||0),0)||0;
 return <><div className="cms-heading"><div><span className="cms-eyebrow">YOUR LIBRARY, SAFELY KEPT</span><h1>Media backup & restore</h1><p>Keep a complete copy of your images, files and folder structure.</p></div></div><div className="cms-backup-summary"><span><Archive size={19}/><strong>{state.media?.length||0}</strong> media items</span><span><FolderOpen size={19}/><strong>{(bytes/1024/1024).toFixed(1)} MB</strong> of original files</span><span><ShieldCheck size={19}/> Includes folders, names and archived media</span></div><div className="cms-backup-grid"><section className="cms-panel cms-form"><Download size={28}/><h2>Download your library</h2><p>One ZIP contains every file, all image sizes and the information needed to rebuild your media library.</p><button className="cms-primary" disabled={busy} onClick={download}><Download size={17}/> Download full backup</button><small>Keep this ZIP somewhere safe. Download a fresh copy after important changes.</small></section><section className="cms-panel cms-form"><Upload size={28}/><h2>Restore from a backup</h2><p>Select a Desartly media ZIP. We check its files before uploading and restore folders and media links together.</p><input ref={picker} hidden type="file" accept=".zip,application/zip" onChange={e=>select(e.target.files[0])}/><button disabled={busy} onClick={()=>picker.current.click()}><Upload size={17}/> Choose backup ZIP</button><small>Matching media is replaced with the backup version. Newer files outside the backup stay in your library. Page and project content stays as it is.</small></section></div>{archive&&<section className="cms-panel cms-form"><h2>Ready to restore</h2><p>{archive.manifest.media.length} media items · {archive.manifest.folders.length} saved folders. Files have passed the integrity check.</p><div className="cms-actions"><button className="cms-primary" disabled={busy} onClick={restore}>Restore media library</button><button disabled={busy} onClick={()=>setArchive(null)}>Cancel</button></div></section>}{busy&&<section className="cms-panel cms-form" role="status" aria-live="polite"><strong>{progress}</strong><p>Keep this page open until the operation finishes.</p>{abort.current&&<button onClick={()=>abort.current.abort()}>Cancel transfer</button>}</section>}</>;
}
