import React,{useState} from 'react';
import {Folder,Upload,Download,Copy,Trash2,RotateCcw,Search,Plus,X,Image as ImageIcon} from 'lucide-react';
import {api} from './context.jsx';
import {useDialogLifecycle} from './useDialogLifecycle.js';
export function MediaLibrary({state,refresh,notify,onError,uploadFile}){
 const [sizes,setSizes]=useState({});
 const [query,setQuery]=useState(''),[folder,setFolder]=useState('All files'),[ids,setIds]=useState([]),[busy,setBusy]=useState(false),[dialog,setDialog]=useState(null),[value,setValue]=useState('');
 useDialogLifecycle(Boolean(dialog),()=>setDialog(null));
 const folders=[...(state.mediaFolders||[])].sort();
 const files=state.media.filter(m=>(folder==='Trash'?Boolean(m.trashedAt):!m.trashedAt)&&(folder==='All files'||folder==='Trash'||m.folder===folder)&&[m.name,m.alt,m.folder].join(' ').toLowerCase().includes(query.toLowerCase()));
 async function saveAlt(){setBusy(true);try{const item=state.media.find(m=>m.id===ids[0]);await api('/api/studio/media',{...item,alt:value});await refresh();setDialog(null);notify('Image description saved.');}catch(e){onError(e);}finally{setBusy(false);}}
 async function action(action,extra={}){setBusy(true);try{await api('/api/studio/media-action',{action,ids,revision:state.revision,...extra});await refresh();setIds([]);setDialog(null);notify('Library updated.');}catch(e){onError(e);}finally{setBusy(false);}}
 async function upload(files){setBusy(true);try{for(const file of files){const item=await uploadFile(file);if(!['All files','Trash'].includes(folder))await api('/api/studio/media',{...item,folder});}await refresh();notify('Files uploaded and images optimized.');}catch(e){onError(e);}finally{setBusy(false);}}
 async function download(){setBusy(true);try{for(const id of ids){const m=state.media.find(m=>m.id===id);const r=await fetch(m.url,{credentials:'same-origin'});if(!r.ok)throw Error('Could not download '+m.name);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=m.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}}catch(e){onError(e);}finally{setBusy(false);}}
 function open(type){setValue(type==='rename'?state.media.find(m=>m.id===ids[0])?.name||'':type==='alt'?state.media.find(m=>m.id===ids[0])?.alt||'':folders.includes(folder)?folder:'Site assets');setDialog(type);}
 return <><div className="cms-heading"><div><span className="cms-eyebrow">YOUR ASSET WORKSPACE</span><h1>Files, in good order.</h1><p>Organise once. Reuse across your portfolio.</p></div><label className="cms-primary"><Upload size={17}/>{busy?'Working…':'Upload files'}<input type="file" multiple disabled={busy} accept="image/*,application/pdf,video/mp4,video/webm" onChange={e=>upload([...e.target.files])}/></label></div>
 <div className="asset-workspace"><aside className="asset-folders" aria-label="Media folders"><p className="asset-folder-note">One folder per project and article. Folders appear when you create content.</p>{['All files',...folders,'Trash'].map(f=><button key={f} aria-pressed={folder===f} onClick={()=>{setFolder(f);setIds([]);}}>{f==='Trash'?<Trash2 size={16}/>:<Folder size={16}/>}<span>{f}</span></button>)}</aside><section className="asset-browser" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)upload([...e.dataTransfer.files]);}}><div className="cms-search"><Search size={17}/><input aria-label="Search files" placeholder="Search names, folders or descriptions" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="asset-toolbar"><label><input type="checkbox" checked={files.length>0&&files.every(m=>ids.includes(m.id))} onChange={e=>setIds(e.target.checked?files.map(m=>m.id):[])}/>Select all</label><span role="status">{ids.length?ids.length+' selected':files.length+' files'}</span>{ids.length>0&&<><button disabled={busy} onClick={download}><Download size={16}/>Download</button>{folder==='Trash'?<><button disabled={busy} onClick={()=>action('restore')}><RotateCcw size={16}/>Restore</button><button disabled={busy} onClick={()=>open('delete')}>Remove permanently</button></>:<><button disabled={busy} onClick={()=>open('move')}>Move</button><button disabled={busy} onClick={()=>open('copy')}><Copy size={16}/>Copy</button>{ids.length===1&&<><button disabled={busy} onClick={()=>open('rename')}>Rename</button><button disabled={busy} onClick={()=>open('alt')}>Image description</button></>}<button disabled={busy} onClick={()=>open('trash')}><Trash2 size={16}/>Trash</button></>}</>}</div><div className="cms-media-grid">{files.map(m=><label className={'asset-card '+(ids.includes(m.id)?'selected':'')} key={m.id}><input type="checkbox" aria-label={'Select '+m.name} checked={ids.includes(m.id)} onChange={e=>setIds(e.target.checked?[...ids,m.id]:ids.filter(id=>id!==m.id))}/>{m.type.startsWith('image/')?<img src={m.url} alt={m.alt||m.name} loading="lazy" onLoad={e=>{const image=e.currentTarget;setSizes(previous=>({...previous,[m.id]:image.naturalWidth+' × '+image.naturalHeight}));}}/>:<ImageIcon size={40}/>}<strong>{m.name}</strong><small>{sizes[m.id]?sizes[m.id]+' · ':m.variants?.[0]?.height?m.variants[0].width+' × '+m.variants[0].height+' · ':''}{Math.ceil((m.variants?.[0]?.size||0)/1024)} KB</small></label>)}</div>{!files.length&&<p className="cms-empty">No files here yet. Drop files into this area to upload.</p>}</section></div>
 {dialog&&<div className="cms-modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setDialog(null);}}><section className="cms-modal cms-form" role="dialog" aria-modal="true" aria-label="File action"><div className="cms-panel-head"><h2>{({alt:'Image description',folder:'New folder',rename:'Rename file',move:'Move files',copy:'Copy files',trash:'Move to Trash?',delete:'Remove from library permanently?'})[dialog]}</h2><button aria-label="Close" disabled={busy} onClick={()=>setDialog(null)}><X/></button></div>{['trash','delete'].includes(dialog)?<p>{dialog==='trash'?'You can restore these files later. Files used in content or history are protected.':'This removes the library record. Stored bytes may remain for backup retention; this is not a secure erase.'}</p>:<label className="cms-field">{dialog==='alt'?'Accessible image description':dialog==='rename'?'Filename':'Folder path'}{['move','copy'].includes(dialog)?<select autoFocus value={value} onChange={e=>setValue(e.target.value)}>{folders.map(f=><option key={f}>{f}</option>)}</select>:<input autoFocus value={value} onChange={e=>setValue(e.target.value)}/>}<small>{dialog==='alt'?'Describe the meaningful content of this image.':dialog==='rename'?'Use a clear, descriptive filename.':'Each project and article has one folder. Shared artwork belongs in Site assets.'}</small></label>}<button className="cms-primary" disabled={busy||(!['trash','delete'].includes(dialog)&&!value.trim())} onClick={()=>dialog==='alt'?saveAlt():action(dialog,dialog==='rename'?{name:value}:{folder:value||'Site assets'})}>{busy?'Working…':'Confirm'}</button></section></div>}</>;
}
