import React,{useEffect,useRef,useState} from 'react';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import 'pdfjs-dist/web/pdf_viewer.css';
export function PdfPreview({url,pageNumber}){const host=useRef(null),pageHost=useRef(null),pdfRef=useRef(null),[document,setDocument]=useState(null),[width,setWidth]=useState(600),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{const observer=new ResizeObserver(([entry])=>setWidth(Math.max(200,entry.contentRect.width-32)));observer.observe(host.current);return()=>observer.disconnect();},[]);
 useEffect(()=>{let cancelled=false,task;setDocument(null);setLoading(true);setError('');(async()=>{const lib=await import('pdfjs-dist');lib.GlobalWorkerOptions.workerSrc=workerUrl;task=lib.getDocument({url});const pdf=await task.promise;if(cancelled){pdf.destroy();return;}pdfRef.current=pdf;setDocument(pdf);})().catch(e=>{if(!cancelled){setError(e.message);setLoading(false);}});return()=>{cancelled=true;task?.destroy();pdfRef.current=null;};},[url]);
 useEffect(()=>{if(!document)return;let cancelled=false,renderTask,textLayer;setLoading(true);setError('');(async()=>{const page=await document.getPage(Math.min(pageNumber,document.numPages));if(cancelled)return;const lib=await import('pdfjs-dist'),base=page.getViewport({scale:1}),viewport=page.getViewport({scale:width/base.width}),ratio=Math.max(1,window.devicePixelRatio||1),wrapper=window.document.createElement('div'),canvas=window.document.createElement('canvas'),text=window.document.createElement('div');wrapper.className='pdf-page';wrapper.style.width=viewport.width+'px';wrapper.style.height=viewport.height+'px';wrapper.style.setProperty('--scale-factor',String(viewport.scale));wrapper.style.setProperty('--total-scale-factor',String(viewport.scale));canvas.width=Math.ceil(viewport.width*ratio);canvas.height=Math.ceil(viewport.height*ratio);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';text.className='textLayer';wrapper.append(canvas,text);pageHost.current.replaceChildren(wrapper);renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:ratio===1?null:[ratio,0,0,ratio,0,0]});await renderTask.promise;if(cancelled)return;textLayer=new lib.TextLayer({textContentSource:await page.getTextContent(),container:text,viewport});await textLayer.render();if(!cancelled)setLoading(false);})().catch(e=>{if(!cancelled&&e.name!=='RenderingCancelledException'){setError(e.message);setLoading(false);}});return()=>{cancelled=true;renderTask?.cancel();textLayer?.cancel();};},[document,pageNumber,width]);
 return <div ref={host} className="pdf-document-viewer" aria-busy={loading}><div ref={pageHost} aria-label={'PDF page '+pageNumber}/>{loading&&<p role="status">Rendering PDF page…</p>}{error&&<p role="alert">PDF could not display: {error}. Use Open PDF to view the file.</p>}</div>;
}
