import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Download,Save,RefreshCw,GripVertical,ChevronUp,ChevronDown,ChevronLeft,ChevronRight,Search,Check,Settings2,Layers,ArrowUpRight,X} from 'lucide-react';
import {api} from './context.jsx';
import {resolveAbout} from '../AboutSections.jsx';
import {buildPortfolio,movePortfolioProject,portfolioContentKey,validatePortfolioConfig} from './portfolio-model.js';
import {renderSlide,createPresentationPdf} from './presentation-renderer.js';
import './portfolio-maker.css';
function SlideCanvas({slide}){
 const host=useRef(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let cancelled=false,canvas;setLoading(true);setError('');renderSlide(slide,{scale:.55}).then(result=>{canvas=result;if(cancelled){canvas.width=0;return;}host.current.replaceChildren(canvas);setLoading(false);}).catch(e=>{if(!cancelled){setError(e.message);setLoading(false);}});return()=>{cancelled=true;if(canvas)canvas.width=0;};},[slide]);
 return <div className="pm-slide" aria-label={'Portfolio page '+slide.pageNumber} aria-busy={loading}><div ref={host}/>{loading&&<p role="status">Rendering page…</p>}{error&&<p role="alert">{error}</p>}</div>;
}
export function PortfolioMaker(){
 const [data,setData]=useState(null),[config,setConfig]=useState(null),[saved,setSaved]=useState(''),[version,setVersion]=useState(0),[page,setPage]=useState(0),[query,setQuery]=useState(''),[settings,setSettings]=useState(false),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[progress,setProgress]=useState(null),[dragged,setDragged]=useState(null),[over,setOver]=useState(null),[lastExport,setLastExport]=useState(null);
 const cancel=useRef(false),pdfUrl=useRef(''),touch=useRef(null);const dirty=config&&JSON.stringify(config)!==saved;
 async function load(initial=false){setError('');try{const value=await api('/api/studio/portfolio');setData(value);if(initial||!dirty){setConfig(value.config);setSaved(JSON.stringify(value.config));setVersion(value.version);}else if(value.version!==version)setError('The saved portfolio changed in another session. Your local edits are kept; reload before saving.');setNotice(initial?'':'Project content and About refreshed.');}catch(e){setError(e.message);}}
 useEffect(()=>{load(true);return()=>{cancel.current=true;if(pdfUrl.current)URL.revokeObjectURL(pdfUrl.current);};},[]);
 useEffect(()=>{if(!dirty)return;const warn=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const about=useMemo(()=>data?resolveAbout(data.about,data.resume):{},[data]);
 const result=useMemo(()=>config&&data?buildPortfolio(data.projects,config,about):null,[data,config,about]);
 const key=useMemo(()=>result?portfolioContentKey(result.chapters.map(c=>data.projects.find(p=>p.id===c.id)),config,about):'',[result,config,about,data]);
 const current=result?Math.min(page,result.slides.length-1):0;
 function patch(values){setConfig(c=>({...c,...values}));setNotice('');}
 async function save(){setSaving(true);setError('');try{const normalized=validatePortfolioConfig(config),value=await api('/api/studio/portfolio',{config:normalized,version});setConfig(value.config);setVersion(value.version);setSaved(JSON.stringify(value.config));setNotice('Portfolio order and settings saved privately.');}catch(e){setError(e.message);}finally{setSaving(false);}}
 function move(from,to){if(!from||!to||from===to)return;patch({projectIds:movePortfolioProject(config.projectIds,from,to)});setNotice('Project order updated.');}
 function select(id,checked){patch({projectIds:checked?[...config.projectIds,id]:config.projectIds.filter(v=>v!==id)});}
 function touchStart(e,id){e.preventDefault();touch.current={id,target:id};e.currentTarget.setPointerCapture(e.pointerId);setDragged(id);}
 function touchMove(e){if(!touch.current)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-portfolio-project]')?.dataset.portfolioProject;if(target){touch.current.target=target;setOver(target);}}
 function touchEnd(){if(touch.current)move(touch.current.id,touch.current.target);touch.current=null;setDragged(null);setOver(null);}
 async function download(){setBusy(true);setError('');cancel.current=false;setProgress({page:0,total:result.slides.length});const exportKey=key,slides=result.slides;try{validatePortfolioConfig(config);const pdf=await createPresentationPdf(slides,config.title,(i,total)=>setProgress({page:i,total}),'portfolio',{compact:true,cancelled:()=>cancel.current});if(cancel.current)throw Error('Export cancelled. Your portfolio settings are kept.');const blob=pdf.output('blob');if(pdfUrl.current)URL.revokeObjectURL(pdfUrl.current);pdfUrl.current=URL.createObjectURL(blob);const link=document.createElement('a');link.href=pdfUrl.current;link.download=(config.name+' — Portfolio').replace(/[^\p{L}\p{N} .—-]/gu,'')+'.pdf';document.body.appendChild(link);link.click();link.remove();setLastExport({key:exportKey,size:blob.size,pages:slides.length});setNotice('Your complete landscape portfolio was downloaded.');}catch(e){setError(e.message);}finally{setBusy(false);setProgress(null);}}
 if(!data||!config||!result)return <section className="cms-panel"><h1>Opening Portfolio maker…</h1>{error&&<><p role="alert">{error}</p><button onClick={()=>load(true)}>Retry</button></>}</section>;
 const map=new Map(data.projects.map(p=>[p.id,p]));const ids=config.projectIds.filter(id=>map.has(id));const available=data.projects.filter(p=>!ids.includes(p.id));const visible=ids.filter(id=>(map.get(id).title+' '+map.get(id).industry).toLowerCase().includes(query.toLowerCase()));
 return <div className="portfolio-maker">
 <div className="pm-heading"><div><span className="cms-eyebrow">DESARTLY / YOUR COMPLETE BODY OF WORK</span><h1>Portfolio maker.</h1><p>One continuous story. Arranged by you.</p></div><div className="cms-actions"><button disabled={busy||saving} onClick={()=>load()}><RefreshCw size={16}/>Refresh content</button><button disabled={busy||saving||!dirty} onClick={save}><Save size={16}/>{saving?'Saving…':'Save portfolio'}</button><button className="cms-primary" disabled={busy||saving||!result.projectCount} onClick={download}><Download size={16}/>Download portfolio PDF</button></div></div>
 {error&&<p role="alert" className="pm-alert error">{error}</p>}{notice&&<p role="status" className="pm-alert">{notice}</p>}
 {progress&&<div className="pm-export" role="status"><div><strong>Building your portfolio</strong><span>Page {progress.page} of {progress.total} · Text and graphics stay sharp.</span></div><progress max={progress.total} value={progress.page}/><button onClick={()=>{cancel.current=true;}}>Cancel export</button></div>}
 <div className="pm-status"><span><span className={dirty?'pm-dot dirty':'pm-dot'}/>{dirty?'Unsaved portfolio changes':'Portfolio settings saved'}</span><span>{result.projectCount} projects · {result.slides.length} landscape pages</span><span>1920 × 1280 · Shared presentation template</span>{lastExport&&<span>{lastExport.key===key?'Latest PDF is current':'PDF needs regeneration'} · {(lastExport.size/1024/1024).toFixed(1)} MB</span>}</div>
 {lastExport&&<a className="pm-last-download" href={pdfUrl.current} download={(config.name+' — Portfolio.pdf')}>Download the generated PDF · {lastExport.pages} pages <Download size={15}/></a>}
 <div className="pm-workspace"><aside className="pm-outline"><div className="pm-outline-head"><div><Layers size={17}/><strong>Your portfolio</strong></div><button aria-label="Edit portfolio identity" aria-pressed={settings} onClick={()=>setSettings(!settings)}><Settings2 size={17}/></button></div>
 <div className="pm-bookends">{result.slides.map((s,i)=>s.type.startsWith('portfolio-')&&!s.closing&&s.type!=='portfolio-contents'?<button key={i} aria-pressed={current===i} onClick={()=>setPage(i)}><span>{String(i+1).padStart(2,'0')}</span>{s.type==='portfolio-cover'?'Branded cover':s.type==='portfolio-contact'?'Contact':s.type==='portfolio-experience'?'Experience':s.type==='portfolio-skills'?'Expertise':'About'}</button>:null)}</div>
 <div className="pm-project-heading"><span>PROJECT RUNNING ORDER</span><small>Drag titles to reorder</small></div><label className="pm-search"><Search size={14}/><input aria-label="Search portfolio projects" placeholder="Find a project…" value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <p id="pm-reorder-help" className="pm-reorder-help">Drag the handle or use the up/down buttons. On mobile, drag the handle with your finger.</p>
 <ol className="pm-projects" aria-label="Portfolio project order">{visible.map(id=>{const project=map.get(id),index=ids.indexOf(id),chapter=result.chapters.find(c=>c.id===id);return <li key={id} data-portfolio-project={id} draggable={!busy&&!query} onDragStart={e=>{if(touch.current){e.preventDefault();return;}e.dataTransfer.setData('text/plain',id);e.dataTransfer.effectAllowed='move';setDragged(id);}} onDragOver={e=>{if(dragged&&!query){e.preventDefault();e.dataTransfer.dropEffect='move';setOver(id);}}} onDrop={e=>{e.preventDefault();move(dragged,id);setDragged(null);setOver(null);}} onDragEnd={()=>{setDragged(null);setOver(null);}} className={(dragged===id?'is-dragging ':'')+(over===id?'is-over ':'')+(result.slides[current]?.projectId===id?'is-current':'')}><button className="pm-grip" aria-label={'Drag '+project.title} aria-describedby="pm-reorder-help" disabled={busy||!!query} onPointerDown={e=>touchStart(e,id)} onPointerMove={touchMove} onPointerUp={touchEnd} onPointerCancel={()=>{touch.current=null;setDragged(null);setOver(null);}}><GripVertical size={17}/></button><button className="pm-project-title" onPointerDown={e=>{if(e.pointerType==='mouse'&&!busy&&!query)touchStart(e,id);}} onPointerMove={touchMove} onPointerUp={touchEnd} onPointerCancel={()=>{touch.current=null;setDragged(null);setOver(null);}} onClick={()=>setPage(chapter.startPage-1)}><span>{String(index+1).padStart(2,'0')} / {project.title}</span><small>Pages {chapter.startPage}–{(result.chapters[index+1]?.startPage||result.slides.length)-1}</small></button><div className="pm-order-tools"><button aria-label={'Move '+project.title+' up'} disabled={!index||busy||!!query} onClick={()=>move(id,ids[index-1])}><ChevronUp size={13}/></button><button aria-label={'Move '+project.title+' down'} disabled={index===ids.length-1||busy||!!query} onClick={()=>move(id,ids[index+1])}><ChevronDown size={13}/></button></div><button className="pm-remove" aria-label={'Remove '+project.title+' from portfolio'} disabled={busy} onClick={()=>select(id,false)}><X size={13}/></button></li>;})}</ol>
 <details className="pm-available"><summary>Add projects <span>{available.length}</span></summary><button disabled={busy} onClick={()=>patch({projectIds:[...ids,...available.map(p=>p.id)]})}>Include all projects</button>{available.map(p=><button key={p.id} disabled={busy} onClick={()=>select(p.id,true)}>+ {p.title}</button>)}{!available.length&&<p>Every project is included.</p>}</details>
 <div className="pm-bookends"><button aria-pressed={current===result.slides.length-1} onClick={()=>setPage(result.slides.length-1)}><span>{result.slides.length}</span>Branded closing</button></div><p className="pm-private">Uses the latest saved CMS drafts. Refresh after editing a project. Your website stays unchanged.</p></aside>
 <section className="pm-stage" aria-label="Live portfolio preview"><div className="pm-preview-heading"><span>LIVE / LANDSCAPE PREVIEW</span><span>{result.slides[current].projectTitle||config.name}</span></div><SlideCanvas slide={result.slides[current]}/><div className="pm-navigation"><button aria-label="Previous portfolio page" disabled={!current} onClick={()=>setPage(current-1)}><ChevronLeft size={18}/></button><label>Page<input type="number" aria-label="Portfolio page number" min={1} max={result.slides.length} value={current+1} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=result.slides.length)setPage(n-1);}}/><span>of {result.slides.length}</span></label><button aria-label="Next portfolio page" disabled={current===result.slides.length-1} onClick={()=>setPage(current+1)}><ChevronRight size={18}/></button></div>
 <div className="pm-filmstrip" aria-label="Portfolio pages">{result.slides.map((s,i)=><button key={i} aria-pressed={current===i} onClick={()=>setPage(i)}><span>{String(i+1).padStart(2,'0')}</span><strong>{s.projectTitle||s.title}</strong><small>{s.type.replace('portfolio-','')}</small></button>)}</div>
 {settings&&<section className="pm-settings"><div><h2>Your identity, throughout.</h2><p>The opening pages use your CMS About content. Optional overrides apply only to this portfolio.</p></div><div className="pm-settings-grid">{[['title','Cover title'],['name','Your name'],['role','Your role'],['subtitle','Cover subtitle'],['email','Contact email'],['website','Website'],['booking','Booking link'],['closingTitle','Closing title'],['closingText','Closing message']].map(([key,label])=><label key={key}>{label}<input disabled={busy} type={key==='email'?'email':['website','booking'].includes(key)?'url':'text'} value={config[key]} onChange={e=>patch({[key]:e.target.value})}/></label>)}</div><div className="pm-options">{[['includeExperience','Include experience & expertise'],['includeContents','Include a clickable contents section']].map(([key,label])=><label key={key}><input type="checkbox" disabled={busy} checked={config[key]} onChange={e=>patch({[key]:e.target.checked})}/>{label}</label>)}</div><details><summary>About text overrides</summary>{[['aboutIntro','About introduction'],['aboutBody','About body']].map(([key,label])=><label key={key}>{label}<textarea disabled={busy} rows={5} value={config[key]} placeholder="Leave empty to follow your CMS About page." onChange={e=>patch({[key]:e.target.value})}/></label>)}</details><a href="/studio/layout?path=%2Fabout">Edit the source About page <ArrowUpRight size={14}/></a></section>}
 {result.warnings.length>0&&<details className="pm-warnings"><summary>Review {result.warnings.length} content notes before sharing</summary><ul>{result.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}
 <div className="pm-method"><Check size={16}/><p>Project pages use the exact landscape presentation renderer. One cover, continuous page numbers, clickable contents and contact links, one closing. Downloading exports the complete current order.</p></div></section></div></div>;
}
