import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Download,ChevronLeft,ChevronRight} from 'lucide-react';
import {buildPresentation,buildInstagramPresentation} from './presentation-model.js';
import {renderSlide,downloadPresentation,downloadInstagramImages} from './presentation-renderer.js';
import './presentation.css';
export function ProjectPresentation({project}){
 const [format,setFormat]=useState('linkedin');const {slides,warnings}=useMemo(()=>format==='instagram'?buildInstagramPresentation(project):buildPresentation(project),[project,format]);const [index,setIndex]=useState(0),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);const host=useRef(null);const current=Math.min(index,slides.length-1);
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');renderSlide(slides[current],{scale:.5,format}).then(canvas=>{if(!cancelled){host.current?.replaceChildren(canvas);setLoading(false);}}).catch(e=>{if(!cancelled){setError(e.message);setLoading(false);host.current?.replaceChildren();}});return()=>{cancelled=true;};},[slides,current,format]);
 async function download(images=false){setBusy(true);setError('');try{const onProgress=(i,total)=>setProgress(`Preparing slide ${i} of ${total}…`);if(images)await downloadInstagramImages(slides,project.title,onProgress);else await downloadPresentation(slides,project.title,onProgress,format);setProgress(images?'Instagram images downloaded.':'PDF downloaded.');}catch(e){setError(e.message);setProgress('');}finally{setBusy(false);}}
 return <section className="cms-panel project-presentation"><div className="presentation-heading"><div><span className="cms-eyebrow">{format==='instagram'?'INSTAGRAM / 1080 × 1350':'LINKEDIN PRESENTATION / 3:2'}</span><h2>Your story, ready to share</h2><p>Built automatically from this project’s latest text, images and section layouts. Cover → project profile → story → closing.</p></div><button className="cms-primary" disabled={busy||!slides[0].image} onClick={()=>download(false)}><Download size={17}/>{busy?'Preparing…':'Download PDF'}</button></div><div className="presentation-formats" role="group" aria-label="Presentation format">{[['linkedin','LinkedIn · Landscape'],['instagram','Instagram · Portrait']].map(([id,label])=><button key={id} disabled={busy} aria-pressed={format===id} onClick={()=>{setFormat(id);setIndex(0);setProgress('');}}>{label}</button>)}{format==='instagram'&&<button disabled={busy||!slides[0].image} onClick={()=>download(true)}><Download size={16}/>Download JPGs (ZIP)</button>}</div>{warnings.length>0&&<ul className="presentation-warnings">{warnings.map((w,i)=><li key={i}>{w}</li>)}</ul>}<div className={'presentation-preview'+(format==='instagram'?' is-portrait':'')} ref={host} role="img" aria-label={`Slide ${current+1}: ${slides[current].title||slides[current].label}`} aria-busy={loading}/><div className="presentation-controls"><button aria-label="Previous presentation slide" disabled={!current||busy} onClick={()=>setIndex(current-1)}><ChevronLeft size={18}/></button><span>{current+1} / {slides.length} · {slides[current].type==='identity'?'Project profile':slides[current].type}</span><button aria-label="Next presentation slide" disabled={current===slides.length-1||busy} onClick={()=>setIndex(current+1)}><ChevronRight size={18}/></button></div><div className="presentation-filmstrip" aria-label="Presentation slides">{slides.map((s,i)=><button key={i} aria-pressed={i===current} onClick={()=>setIndex(i)}>{String(i+1).padStart(2,'0')}<span>{s.type==='identity'?'Project profile':s.title||s.label||s.type}</span></button>)}</div><p className="presentation-status" role="status">{loading?'Loading preview…':progress}</p>{error&&<p role="alert" className="presentation-error">{error}</p>}<small>Edits update the presentation automatically. PDF uses the current draft, including unsaved edits. Downloading does not publish the project. Interactive sections require a static image.</small></section>;
}
