import React,{useEffect,useState} from 'react';
import {Copy,Download,LockKeyhole,Check} from 'lucide-react';
import {announcementText} from './announcement.js';
export function ProjectAnnouncement({project,onChange}){
 const [view,setView]=useState('edit'),[feedback,setFeedback]=useState(''),[error,setError]=useState('');const value=project.announcement||{},text=announcementText(value);
 useEffect(()=>{if(project.updatedAt&&announcementText(project.announcement))setFeedback('Caption saved with this project.');},[project.updatedAt]);
 const update=(key,next)=>{onChange({...value,[key]:next});setFeedback('Save draft to keep your caption changes.');setError('');};
 async function copy(){try{await navigator.clipboard.writeText(text);setFeedback('Bilingual caption copied.');setError('');}catch{setError('Could not copy. Select the text in Preview and copy it manually.');}}
 function download(){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=(project.id||'project')+'-announcement.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setFeedback('Caption downloaded.');}
 return <section className="cms-panel announcement-panel" aria-labelledby="announcement-heading"><header className="announcement-heading"><div><span className="cms-eyebrow"><LockKeyhole size={14}/> PRIVATE / SOCIAL CAPTION</span><h2 id="announcement-heading">Project announcement</h2><p>Your voice, in Persian and English. Saved with this project; excluded from the public website and presentation slides.</p></div><span className="announcement-badge"><Check size={14}/> CMS only</span></header><div className="announcement-tools"><div className="announcement-views" role="group" aria-label="Caption view"><button aria-pressed={view==='edit'} onClick={()=>setView('edit')}>Edit caption</button><button aria-pressed={view==='preview'} onClick={()=>setView('preview')}>Preview</button></div><div className="announcement-actions"><button disabled={!text} onClick={copy}><Copy size={16}/> Copy bilingual</button><button disabled={!text} onClick={download}><Download size={16}/> TXT</button></div></div>{view==='edit'?<><div className="announcement-editors"><label className="announcement-field"><span>فارسی <small>تجربه، معرفی برند و دعوت به همکاری</small></span><textarea lang="fa" dir="rtl" value={value.fa||''} onChange={e=>update('fa',e.target.value)} maxLength={16000} placeholder="تجربهٔ طراحی این پروژه رو از کجا شروع کردی؟"/><small>{(value.fa||'').length.toLocaleString()} characters</small></label><label className="announcement-field"><span>English <small>Brand introduction, design story & CTA</small></span><textarea lang="en" dir="ltr" value={value.en||''} onChange={e=>update('en',e.target.value)} maxLength={16000} placeholder="Tell the story behind this project…"/><small>{(value.en||'').length.toLocaleString()} characters</small></label></div><label className="announcement-field announcement-tags"><span>Hashtags</span><textarea dir="ltr" value={value.hashtags||''} onChange={e=>update('hashtags',e.target.value)} maxLength={16000} placeholder="#BrandDesign #VisualIdentity"/></label><details className="announcement-notes"><summary>Private editorial notes</summary><label className="announcement-field"><span>Assumptions & details to review</span><textarea lang="fa" dir="auto" value={value.notes||''} onChange={e=>update('notes',e.target.value)} maxLength={16000}/></label></details></>:<div className="announcement-preview">{text?<>{value.fa&&<div dir="rtl" lang="fa">{value.fa}</div>}{value.en&&<div dir="ltr" lang="en">{value.en}</div>}{value.hashtags&&<div dir="ltr" className="announcement-preview-tags">{value.hashtags}</div>}</>:<p>Add a caption to preview your announcement.</p>}</div>}<footer><p role="status">{feedback||'Ready for social sharing. Telegram delivery will be connected later.'}</p>{error&&<p role="alert" className="presentation-error">{error}</p>}</footer></section>;
}
