import React from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight} from 'lucide-react';
import {safeLink} from '../data.js';
import {useSite,Editable,EditingContext} from './context';
export function Media({src,alt='',className='',style={},eager=false}){const image=typeof src==='string'?src:src?.url;if(!image)return null;return <img className={className} src={image} alt={alt} loading={eager?'eager':'lazy'} decoding="async" style={style}/>;}
export function ExternalEmbed({url,title}){const [loaded,setLoaded]=React.useState(false);let safe='';try{const u=new URL(url);if(u.protocol==='https:'&&['www.youtube-nocookie.com','player.vimeo.com','www.figma.com','embed.figma.com'].includes(u.hostname))safe=u.href;}catch{}if(!safe)return <p>Add a supported HTTPS embed URL (Figma, Vimeo or YouTube privacy mode).</p>;return loaded?<iframe title={title||'Interactive prototype'} src={safe} loading="lazy" sandbox="allow-scripts allow-same-origin allow-presentation" allowFullScreen/>:<button className="embed-load" onClick={()=>setLoaded(true)}>Load {title||'interactive preview'} <ArrowUpRight size={18}/></button>;}
export function ExtraSection({section:s,path,Card}){const site=useSite();const index=site.pages[path]?.sections?.findIndex(v=>v.id===s.id);const field=key=>['pages',path,'sections',index,key];const heading=<Editable as="h2" path={field('title')}>{s.title}</Editable>;const text=<Editable as="p" path={field('text')}>{s.text}</Editable>;
 switch(s.type){
 case 'logos':return <section className="client-section">{heading}{text}<div className="client-logos">{site.clients.filter(c=>c.visible!==false).map(c=><a key={c.id} href={safeLink(c.url)||undefined}><Media src={c.image} alt={c.name}/><span>{c.name}</span><small>{c.relationship}</small></a>)}</div></section>;
 case 'quote':{const quote=site.testimonials.find(q=>q.id===s.quoteId)||site.testimonials[0];return <section className="quote-section">{heading}{quote?<><blockquote>“{quote.text}”</blockquote><p>{quote.name} · {quote.role}</p>{safeLink(quote.url)&&<a href={safeLink(quote.url)}>View project</a>}</>:text}</section>;}
 case 'stats':return <section className="stats-section">{heading}<div>{s.items?.map(item=><article key={item.id}><strong>{item.value}</strong><p>{item.label}</p><small>{item.source}</small></article>)}</div></section>;
 case 'image':return <section className="media-section">{heading}<Media src={s.image} alt={s.alt} style={{objectPosition:s.focus||'50% 50%'}}/>{text}</section>;
 case 'gallery':return <section className="media-section">{heading}<div className="gallery-section">{s.items?.map(item=><figure key={item.id}><Media src={item.image} alt={item.alt}/><figcaption>{item.caption}</figcaption></figure>)}</div>{text}</section>;
 case 'video':return <section className="media-section">{heading}{safeLink(s.url)&&<video controls preload="none" poster={s.image||undefined} src={safeLink(s.url)}/ >}{text}</section>;
 case 'embed':return <section className="media-section">{heading}<ExternalEmbed url={s.url} title={s.title}/>{text}</section>;
 case 'comparison':return <Comparison section={s} heading={heading} text={text}/>;
 case 'steps':return <section className="steps-section">{heading}{text}<ol>{s.items?.map(item=><li key={item.id}><h3>{item.title}</h3><p>{item.text}</p><Media src={item.image} alt={item.alt}/></li>)}</ol></section>;
 case 'selected':{const projects=(s.projectIds||[]).map(id=>site.projects.find(p=>p.id===id)).filter(Boolean);return <section>{heading}{text}<div className="cards">{projects.map(p=><Card key={p.id} p={p}/>)}</div></section>;}
 default:return <section className="text-block">{heading}{text}{safeLink(s.url)&&<a className="button" href={safeLink(s.url)}>{s.linkLabel||'Learn more'} <ArrowUpRight size={16}/></a>}</section>;
 }
}
function Comparison({section:s,heading,text}){const [value,setValue]=React.useState(50);return <section className="comparison-section">{heading}<div className="comparison-images"><Media src={s.after} alt={s.afterAlt||'After'}/><div style={{clipPath:`inset(0 ${100-value}% 0 0)`}}><Media src={s.before} alt={s.beforeAlt||'Before'}/></div><span style={{left:value+'%'}}/></div><label>Before / After<input aria-label="Compare before and after" type="range" min="0" max="100" value={value} onChange={e=>setValue(+e.target.value)}/></label>{text}</section>}
export function SectionList({path,builtins,Card}){const site=useSite(),editing=React.useContext(EditingContext);const sections=site.pages[path]?.sections||[];return <>{sections.map((s,i)=>s.visible===false&&!editing?null:<div key={s.id} className={'site-section section-space-'+(s.spacing||'normal')+' section-width-'+(s.width||'wide')+(s.visible===false?' is-hidden':'')} style={{background:s.background==='tint'?'var(--surface)':s.background==='dark'?'var(--ink)':undefined,color:s.background==='dark'?'white':undefined}}>{editing&&<div className="section-edit-bar"><button onClick={()=>editing.select(['pages',path,'sections',i])}>{s.type} · Edit section</button><button aria-label="Move section up" onClick={()=>editing.move(['pages',path,'sections'],i,i-1)} disabled={!i}>↑</button><button aria-label="Move section down" onClick={()=>editing.move(['pages',path,'sections'],i,i+1)} disabled={i===sections.length-1}>↓</button><button onClick={()=>editing.set(['pages',path,'sections',i,'visible'],s.visible===false)}> {s.visible===false?'Show':'Hide'}</button></div>}{builtins[s.type]||<ExtraSection section={s} path={path} Card={Card}/>}</div>)}</>}
