import React,{useEffect,useState}from'react';
import{Search,ArrowUpRight,RefreshCw,CheckCircle2,AlertCircle,Globe,FileText,Download}from'lucide-react';
import{api}from'./context.jsx';
import './seo-panel.css';
const origin='https://www.desartly.info';
const consoleUrl='https://search.google.com/search-console?resource_id='+encodeURIComponent(origin+'/');
export function SeoPanel({state,refresh,notify,onError}){
 const [inventory,setInventory]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState('/'),[form,setForm]=useState(state.seo?.['/']||{}),[busy,setBusy]=useState(false),[checking,setChecking]=useState(false),[audits,setAudits]=useState({}),[view,setView]=useState('draft');
 useEffect(()=>{let active=true;api('/api/cms/seo-report').then(r=>{if(active)setInventory(r)}).catch(onError);return()=>{active=false};},[state.draftVersion]);
 const rows=inventory?.rows||[],current=rows.find(p=>p.path===selected),audit=audits[selected],effective=view==='live'?current?.live:{...current?.defaults,...Object.fromEntries(Object.entries(form).filter(([,v])=>v?.trim()))};
 const visible=rows.filter(r=>(filter==='all'||filter==='issues'&&r.issues.length||filter==='drafts'&&r.hasDraft)&&(r.name+' '+r.path).toLowerCase().includes(query.toLowerCase()));
 function choose(path){setSelected(path);setForm(state.seo?.[path]||{});setView('draft');}
 async function save(publish){setBusy(true);try{await api('/api/cms/seo',{path:selected,seo:form,draftVersion:state.draftVersion,publish});await refresh();notify(publish?'Page metadata published. Run a live check to verify it.':'Metadata draft saved.');}catch(e){onError(e);}finally{setBusy(false);}}
 async function check(){setChecking(true);const path=selected;try{const r=await api('/api/cms/seo-report?path='+encodeURIComponent(path));setAudits(a=>({...a,[path]:r}));}catch(e){onError(e);}finally{setChecking(false);}}
 function exportReport(){const blob=new Blob([JSON.stringify({inventory,audits},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='desartly-seo-report.json';a.click();URL.revokeObjectURL(url);}
 const issues=rows.filter(r=>r.issues.length).length,drafts=rows.filter(r=>r.hasDraft).length;
 return <div className="cms-operations seo-workspace"><header className="cms-heading"><div><span className="cms-eyebrow">DESARTLY / SEARCH VISIBILITY</span><h1>Search, with a clear direction.</h1><p>Manage published pages, refine their search appearance and verify what crawlers receive.</p></div><a className="seo-console-link" href={consoleUrl} target="_blank" rel="noreferrer">Open Search Console <ArrowUpRight size={16}/></a></header>
 <section className="seo-overview" aria-label="Published site overview"><div><Globe size={20}/><strong>{inventory?rows.length:'—'}</strong><span>Published pages</span></div><div><AlertCircle size={20}/><strong>{inventory?issues:'—'}</strong><span>Pages to review</span></div><div><FileText size={20}/><strong>{inventory?drafts:'—'}</strong><span>Unpublished metadata</span></div><div><Search size={20}/><strong>Not measured</strong><span>Google indexing · see Search Console</span></div></section>
 <section className="seo-discovery cms-panel"><div><span className="cms-eyebrow">GOOGLE DISCOVERY</span><h2>Give Google a reliable starting point.</h2><p>Verify ownership in Search Console, submit the sitemap, then inspect key URLs. Technical readiness does not guarantee indexing or a search position.</p></div><div className="seo-discovery-links"><a href={origin+'/sitemap.xml'} target="_blank" rel="noreferrer">Open sitemap <ArrowUpRight size={15}/></a><a href={origin+'/robots.txt'} target="_blank" rel="noreferrer">Open robots.txt <ArrowUpRight size={15}/></a><a href="https://developers.google.com/search/docs/crawling-indexing/ask-google-to-recrawl" target="_blank" rel="noreferrer">Google indexing guide <ArrowUpRight size={15}/></a><button disabled={!inventory} onClick={exportReport}><Download size={15}/> Export checks</button></div></section>
 <div className="seo-layout"><section className="seo-pages cms-panel" aria-label="Published pages"><header><h2>Your search pages</h2><span>{visible.length} pages</span></header><label className="seo-find"><Search size={16}/><input aria-label="Find a page" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title or URL"/></label><label className="seo-filter">Show<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All published pages</option><option value="issues">Needs review</option><option value="drafts">Unpublished metadata</option></select></label><div className="seo-page-list">{!inventory?<p role="status">Loading published pages…</p>:!visible.length?<p>No pages match this filter.</p>:visible.map(p=><button key={p.path} className={p.path===selected?'is-selected':''} aria-pressed={p.path===selected} disabled={busy} onClick={()=>choose(p.path)}><span><small>{p.kind}{p.hasDraft?' · Draft changes':''}</small><strong>{p.name}</strong><code>{p.path}</code></span>{p.issues.length?<AlertCircle size={16} aria-label="Review suggested"/>:<CheckCircle2 size={16} aria-label="Metadata present"/>}</button>)}</div></section>
 <div className="seo-editor"><section className="cms-panel cms-form" aria-busy={busy}><div className="seo-section-heading"><div><span className="cms-eyebrow">PAGE METADATA</span><h2>{current?.name||'Home'}</h2></div><a href={origin+selected} target="_blank" rel="noreferrer" aria-label="Open selected page"><ArrowUpRight size={20}/></a></div><label>Search title<input disabled={busy} aria-describedby="seo-title-help" maxLength={200} value={form.title||''} placeholder={current?.editing.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><small id="seo-title-help">{(form.title||current?.editing.title||'').length} characters · appearance varies by device. Empty uses the page’s default.</small><label>Search description<textarea disabled={busy} maxLength={500} rows={4} value={form.description||''} placeholder={current?.editing.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><small>{(form.description||current?.editing.description||'').length} characters · describe this page specifically.</small><label>Sharing image URL<input disabled={busy} type="text" value={form.image||''} placeholder={current?.editing.image||'/api/media/… or https://…'} onChange={e=>setForm({...form,image:e.target.value})}/></label><small>Empty uses the project cover or site image.</small><div className="cms-actions"><button disabled={busy||!inventory} onClick={()=>save(false)}>Save draft</button><button className="cms-primary" disabled={busy||!inventory} onClick={()=>save(true)}>{busy?'Saving…':'Publish metadata'}</button></div></section>
 <section className="cms-search-preview" aria-label="Search appearance preview"><div className="seo-preview-heading"><strong>Search appearance</strong><label>Preview<select value={view} onChange={e=>setView(e.target.value)}><option value="draft">Current edit</option><option value="live">Published metadata</option></select></label></div><div className="seo-result-brand"><span>AK</span><div>Desartly<small>{origin}{selected==='/'?'':selected}</small></div></div><h3 dir="auto">{effective?.title||'Loading metadata…'}</h3><p dir="auto">{effective?.description||''}</p><small>Illustration only. Google may choose different text.</small></section>
 <section className="cms-panel seo-checks"><div className="seo-section-heading"><div><span className="cms-eyebrow">LIVE TECHNICAL CHECK</span><h2>What crawlers can access.</h2></div><button disabled={checking||!inventory} onClick={check}><RefreshCw size={16}/>{checking?'Checking…':'Check this page'}</button></div><p>Checks the published HTML, canonical URL, indexing directives, robots file and sitemap. Private Studio pages stay excluded.</p>{audit?.error&&<p role="alert">{audit.error}</p>}{audit&&<><small>Checked {new Date(audit.checkedAt).toLocaleString()}</small><ul>{[...audit.checks,...audit.infrastructure].map(c=><li key={c.name}>{c.ok?<CheckCircle2 size={17}/>:<AlertCircle size={17}/>}<div><strong>{c.name}</strong><span>{c.detail}</span></div><small>{c.ok?'Passed':'Review'}</small></li>)}</ul><p>Structured data: {audit.structured?.join(', ')||'None detected on this page'}. Google indexing status is available in Search Console.</p></>}{!audit&&<p className="seo-unchecked">No live check for this page yet. Run a check after publishing.</p>}{current?.issues.length>0&&<div className="seo-review"><strong>Metadata review</strong><ul>{current.issues.map(i=><li key={i}>{i}</li>)}</ul><small>Length guidance is a review prompt, not a ranking score.</small></div>}</section></div></div></div>;
}
