import React,{useState}from'react';
import {api}from'./context.jsx';
const core=[['/','Home'],['/work','Projects'],['/journal','Journal'],['/about','About'],['/services','Services'],['/contact','Booking'],['/privacy','Privacy'],['/certificates','Certificates']];
export function SeoPanel({state,refresh,notify,onError}){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState('/'),[form,setForm]=useState(state.seo?.['/']||{}),[busy,setBusy]=useState(false);
 const pages=[...core.map(([path,title])=>({path,title})),...state.projects.filter(p=>p.status!=='Archived').map(p=>({path:'/work/'+p.id,title:p.title})),...state.articles.filter(p=>p.status!=='Archived').map(p=>({path:'/journal/'+p.id,title:p.title}))];
 function choose(path){setSelected(path);setForm(state.seo?.[path]||{});}
 async function save(publish){setBusy(true);try{await api('/api/cms/seo',{path:selected,seo:form,draftVersion:state.draftVersion,publish});await refresh();notify(publish?'Page metadata published.':'Metadata draft saved.');}catch(e){onError(e);}finally{setBusy(false);}}
 return <div className="cms-operations"><div className="cms-heading"><div><span className="cms-eyebrow">SEARCH VISIBILITY</span><h1>SEO workspace</h1><p>Set the search title, description and sharing image for each page.</p></div></div><section className="cms-panel cms-form"><label>Find a page<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Title or URL"/></label><label>Page<select disabled={busy} value={selected} onChange={e=>choose(e.target.value)}>{pages.filter(p=>p.path===selected||(p.title+p.path).toLowerCase().includes(query.toLowerCase())).map(p=><option key={p.path} value={p.path}>{p.title} · {p.path}</option>)}</select></label><label>Search title<input maxLength={200} value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><small>{(form.title||'').length} characters. Leave empty to use the page title.</small><label>Search description<textarea maxLength={500} rows={3} value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Sharing image URL<input type="text" value={form.image||''} onChange={e=>setForm({...form,image:e.target.value})} placeholder="/api/media/… or https://…"/></label><small>Leave empty to use the content cover or site image.</small><div className="cms-actions"><button disabled={busy} onClick={()=>save(false)}>Save metadata draft</button><button className="cms-primary" disabled={busy} onClick={()=>save(true)}>Publish page metadata</button></div></section><section className="cms-search-preview" aria-label="Search appearance preview"><small>Preview · search engines may display different text</small><h3>{form.title||pages.find(p=>p.path===selected)?.title}</h3><p>{form.description||state.settings.description}</p><small>{selected}</small></section></div>;
}
