import React,{useState,useEffect} from 'react';
import {RefreshCw,Download,Search,AlertTriangle,Activity,CheckCircle2} from 'lucide-react';
import {api} from './context.jsx';
export function SystemLogs(){
 const [filters,setFilters]=useState({level:'',source:'',q:'',trace:'',after:'',before:''}),[data,setData]=useState({items:[],stats:[]}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(null);
 const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString();
 async function load(cursor){setBusy(true);setError('');try{const result=await api('/api/studio/logs?'+query+(cursor?'&cursor='+encodeURIComponent(cursor):''));setData(previous=>({...result,items:cursor?[...previous.items,...result.items]:result.items}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[query]);
 const field=(key,value)=>{setSelected(null);setFilters(f=>({...f,[key]:value}));};
 function download(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),filters,items:data.items},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='desartly-system-logs.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="cms-observability"><div className="cms-heading"><div><span className="cms-eyebrow">SITE HEALTH</span><h1>System logs</h1><p>Trace API operations, browser errors and failed transfers across your site and Studio.</p></div><div className="cms-actions"><button disabled={busy} onClick={()=>load()}><RefreshCw size={16}/>Refresh</button><button disabled={!data.items.length} onClick={download}><Download size={16}/>Export loaded logs</button></div></div>
 <div className="log-summary">{[['error','Errors',AlertTriangle],['warning','Warnings',Activity],['info','Operations',CheckCircle2]].map(([level,title,Icon])=><button key={level} onClick={()=>field('level',level)} aria-pressed={filters.level===level}><Icon size={18}/><span>{title}<small>Last 24 hours</small></span><strong>{data.stats.find(s=>s.level===level)?.count||0}</strong></button>)}</div>
 <section className="cms-panel log-panel"><div className="log-filters"><label><Search size={16}/><input aria-label="Search logs" placeholder="Search event, message or route" value={filters.q} onChange={e=>field('q',e.target.value)}/></label><select aria-label="Log severity" value={filters.level} onChange={e=>field('level',e.target.value)}><option value="">All severities</option>{['error','warning','info'].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Log source" value={filters.source} onChange={e=>field('source',e.target.value)}><option value="">All sources</option>{['worker','cms-browser','site-browser'].map(v=><option key={v}>{v}</option>)}</select><input aria-label="Request reference" placeholder="Request reference" value={filters.trace} onChange={e=>field('trace',e.target.value)}/><label>From<input type="date" value={filters.after} onChange={e=>field('after',e.target.value)}/></label><label>Through<input type="date" value={filters.before} onChange={e=>field('before',e.target.value)}/></label></div>
 {error&&<p role="alert">{error}</p>}<div className="log-table-wrap"><table><thead><tr><th>Time</th><th>Severity</th><th>Event / route</th><th>Source</th><th>Status</th><th>Duration</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td><span className={'log-level '+item.level}>{item.level}</span></td><td><button onClick={()=>setSelected(item)}>{item.event}<small>{item.path}</small></button></td><td>{item.source}</td><td>{item.status||'—'}</td><td>{item.duration_ms===null?'—':item.duration_ms+' ms'}</td></tr>)}</tbody></table></div>{!data.items.length&&!busy&&!error&&<p className="log-empty">No events match these filters. New operations and errors appear here after monitoring is enabled.</p>}{busy&&<p role="status">Loading logs…</p>}{data.next&&<button disabled={busy} onClick={()=>load(data.next)}>Load older events</button>}
 {selected&&<aside className="log-details"><div><h2>Event details</h2><button onClick={()=>setSelected(null)}>Close details</button></div><dl><dt>Request reference</dt><dd><code>{selected.request_id||'—'}</code></dd><dt>Message</dt><dd dir="auto">{selected.message||'Operation completed.'}</dd><dt>Route</dt><dd>{selected.path}</dd></dl>{selected.request_id&&<button onClick={()=>field('trace',selected.request_id)}>Trace related events</button>}</aside>}
 <footer>Retained for {data.retentionDays||14} days, up to {data.maxRows||10000} events. Request bodies, cookies and media contents are excluded. Platform outages before the Worker starts remain in provider logs.</footer></section></div>;
}
