import React,{useEffect,useState} from 'react';
import {Send,LockKeyhole,Files,CalendarDays,Clock3,Users,RefreshCw,ArrowUpRight} from 'lucide-react';
import {api} from './context.jsx';
import './telegram-panel.css';
const capabilities=[{icon:Files,title:'Project materials',text:'Landscape & portrait PDFs, original covers, ordered image albums and your saved Persian or English captions.'},{icon:CalendarDays,title:'Appointments',text:'Confirmed bookings, today’s sessions and upcoming appointments. Preview before cancelling or moving a session.'},{icon:Users,title:'Client records',text:'Name, email, appointment history, private notes, session outcomes and a dated next step.'},{icon:Clock3,title:'Schedule & reminders',text:'Working days, hours, holidays, booking alerts and reminders. Website bookings stay automatically confirmed.'}];
const deliveryLabels={pending:'Queued',preparing:'Generating PDF',sending:'Preparing / sending',sent:'Delivered',failed:'Failed',uncertain:'Needs review',obsolete:'Superseded'};
export function TelegramPanel(){
 const [data,setData]=useState(null),[secret,setSecret]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pair,setPair]=useState(''),[materials,setMaterials]=useState(null),[project,setProject]=useState(''),[format,setFormat]=useState('both');
 async function load(){try{setData(await api('/api/studio/telegram'));setMaterials(await api('/api/studio/telegram/materials'));}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function action(values){setBusy(true);setError('');try{const result=await api('/api/studio/telegram',values);setSecret('');if(result.url)setPair(result.url);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function prepare(){setBusy(true);setError('');try{await api('/api/studio/telegram/materials',{projectId:project,format});await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="cms-operations telegram-workspace"><div className="cms-heading"><div><span className="cms-eyebrow"><Send size={14}/> DESARTLY / PRIVATE ASSISTANT</span><h1>Your studio. Always within reach.</h1><p>Ask for a project, get its materials, and manage your sessions from your own Telegram account.</p></div><button disabled={busy} onClick={load}><RefreshCw size={16}/>Refresh connection</button></div>{error&&<p role="alert">{error}</p>}
 <section className="telegram-identity"><div className="telegram-monogram">AK</div><div><span>DESARTLY STUDIO</span><h2>{data?.botName?'@'+data.botName:'Connect your private assistant'}</h2><p><LockKeyhole size={14}/>{data?.ownerId?'Private access · '+data.ownerName:'Private access · owner connection required'}</p></div>{data?.ownerId&&<a href={'https://t.me/'+data.botName} target="_blank" rel="noreferrer">Open assistant <ArrowUpRight size={17}/></a>}</section>
 <div className="cms-feature-grid"><section className="cms-panel cms-form"><h2>01 / Bot connection</h2><p>{data?.configured?'Connected. Credentials are encrypted on the server and never returned to this page.':'Create your bot with BotFather, then paste its token in this private form.'}</p>{!data?.configured&&<form onSubmit={e=>{e.preventDefault();action({action:'connect',token:secret});}}><label>BotFather token<input type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} required/></label><button className="cms-primary" disabled={busy||!secret}>Connect bot</button></form>}<a href="https://t.me/BotFather" target="_blank" rel="noreferrer">Open BotFather ↗</a></section>
 <section className="cms-panel cms-form"><h2>02 / Owner account</h2>{data?.ownerId?<><strong>Owner connected: {data.ownerName}</strong><p>Telegram ID: {data.ownerId}. Private commands are limited to this account.</p></>:<><p>Create a ten-minute link and open it from your Telegram account. Refresh here to review and approve the requesting account.</p><button disabled={busy||!data?.configured} onClick={()=>action({action:'pair'})}>Create owner connection link</button>{pair&&<a href={pair} target="_blank" rel="noreferrer">Open connection in Telegram ↗</a>}{data?.candidateId&&<div><strong>Request from {data.candidateName}</strong><p>Telegram ID: {data.candidateId}</p><button className="cms-primary" disabled={busy} onClick={()=>action({action:'approve',candidateId:data.candidateId})}>Approve this account as owner</button></div>}</>}</section></div>
 <div className="telegram-capabilities">{capabilities.map(({icon:Icon,title,text})=><section key={title} className="cms-panel"><Icon size={23}/><h2>{title}</h2><p>{text}</p></section>)}</div>
 <section className="cms-panel telegram-request-guide"><div><span className="cms-eyebrow">REQUEST / RECEIVE / KEEP</span><h2>Your materials, in a private conversation.</h2><p>Send the project name, select it, then choose the file. Ready PDFs are delivered directly. Missing or outdated PDFs are generated using the same Presentation studio layout and privately saved for the next request.</p><p>Older files are clearly marked. Channel publishing is disabled.</p></div><div dir="rtl" lang="fa"><code>کاور MyOm</code><code>آلبوم MyOm</code><code>پرزنتیشن MyOm</code><code>کپشن MyOm</code><small>Or send /projects and choose a project.</small></div></section>
 <section className="cms-panel cms-form"><h2>Prepare private presentations</h2><p>Prepare files ahead of time for immediate Telegram delivery. The original CMS layouts are preserved. Preparing files does not publish a project.</p><div className="telegram-preferences"><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">Choose a project</option>{materials?.projects?.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="both">Both PDFs</option><option value="linkedin">Landscape</option><option value="instagram">Portrait</option></select></label><button disabled={busy||!project} onClick={prepare}>Prepare private PDFs</button></div>{materials?.jobs?.slice(0,5).map(job=>{const p=JSON.parse(job.payload);return <p key={job.id}>{materials.projects.find(x=>x.id===p.projectId)?.title||p.projectId} · {p.format} · {job.status==='done'?'Ready':job.status==='failed'?'Failed — '+(p.error||'check project images'):job.status==='processing'?'Generating…':'Queued'}</p>;})}<small>{materials?.exports?.length||0} private presentation files saved.</small>{materials?.exports?.map(file=><p key={file.project_id+file.format}><a href={'/api/studio/telegram/materials?projectId='+encodeURIComponent(file.project_id)+'&format='+file.format}>Download saved PDF · {materials.projects.find(p=>p.id===file.project_id)?.title||file.project_id} · {file.format}</a> · {(file.byte_size/1048576).toFixed(1)} MB</p>)}</section>
 {data?.ownerId&&<section className="cms-panel cms-form"><h2>Notifications & reminders</h2><div className="telegram-preferences"><label><input type="checkbox" checked={!!data.preferences?.notifications} disabled={busy} onChange={e=>action({action:'preferences',notifications:e.target.checked?1:0})}/> New booking alerts</label><label><input type="checkbox" checked={!!data.preferences?.reminders} disabled={busy} onChange={e=>action({action:'preferences',reminders:e.target.checked?1:0})}/> Session and follow-up reminders</label><label>Session reminder<select value={data.preferences?.reminderMinutes||60} disabled={busy} onChange={e=>action({action:'preferences',reminder_minutes:Number(e.target.value)})}><option value={30}>30 minutes before</option><option value={60}>1 hour before</option><option value={1440}>24 hours before</option></select></label></div></section>}
 <section className="cms-panel"><div className="cms-heading"><div><h2>Private delivery history</h2><p>Each file or album part has its own delivery status. Uncertain requests are held for review.</p></div>{data?.ownerId&&<button disabled={busy} onClick={()=>action({action:'process'})}>Process queued requests</button>}</div>{data?.deliveries?.length?<div className="telegram-delivery-table"><table><thead><tr><th>Request</th><th>Status</th><th>Updated</th><th>Action</th></tr></thead><tbody>{data.deliveries.map(d=><tr key={d.id}><td>{d.kind}<small>{d.id}</small></td><td><span className={'telegram-status telegram-status-'+d.status}>{deliveryLabels[d.status]||d.status}</span></td><td>{new Date(d.updated_at).toLocaleString()}</td><td>{d.status==='failed'&&<button disabled={busy} onClick={()=>action({action:'retry',id:d.id})}>Retry failed request</button>}</td></tr>)}</tbody></table></div>:<p>No deliveries yet.</p>}</section>
 <details className="cms-panel"><summary>Webhook activity</summary>{data?.events?.length?<ul>{data.events.map(e=><li key={e.update_id}>Update {e.update_id} · {e.status} · {new Date(e.created_at).toLocaleString()}</li>)}</ul>:<p>No updates received yet.</p>}</details></div>;
}
