import test from 'node:test';import assert from 'node:assert/strict';
import * as utils from '../src/cms/file-manager-utils.js';
import {mediaAction} from '../server/media-service.js';
import {libraryFolders} from '../src/cms/media-architecture.js';
test('folder sorting follows name, size and modification controls',()=>{const files=[{id:'1',folder:'Projects/Alpha',createdAt:'2026-01-01',variants:[{asset:'a',size:20}]},{id:'2',folder:'Projects/Zebra',createdAt:'2026-02-01',variants:[{asset:'b',size:10}]}];assert.deepEqual(utils.sortedFolders(['Projects/Zebra','Projects/Alpha'],files,{sort:'name',direction:'desc'}),['Projects/Zebra','Projects/Alpha']);assert.deepEqual(utils.sortedFolders(['Projects/Zebra','Projects/Alpha'],files,{sort:'size'}),['Projects/Zebra','Projects/Alpha']);});
test('empty project folder can go to Trash and restore without archiving content',()=>{const state={revision:1,media:[],draft:{projects:[{id:'test',managed:true}]},published:{}};const next=mediaAction(state,{action:'trash-folder',source:'Projects/test',revision:1});assert(!libraryFolders(next).includes('Projects/test'));assert.deepEqual(next.draft,state.draft);const restored=mediaAction(next,{action:'restore-folder',source:'Projects/test',revision:1});assert(libraryFolders(restored).includes('Projects/test'));assert.throws(()=>mediaAction(state,{action:'trash-folder',source:'Projects',revision:1}),/system|root/i);});

test('New badge expires exactly one hour after upload, independent of metadata edits',()=>{const now=Date.parse('2026-10-10T12:00:00Z');assert.equal(utils.isNewUpload({uploadedAt:'2026-10-10T11:00:01Z'},now),true);assert.equal(utils.isNewUpload({uploadedAt:'2026-10-10T11:00:00Z',updatedAt:'2026-10-10T12:00:00Z'},now),false);assert.equal(utils.isNewUpload({createdAt:'2026-10-10T11:30:00Z'},now),true);assert.equal(utils.isNewUpload({uploadedAt:'invalid'},now),false);assert.equal(utils.isNewUpload({uploadedAt:'2026-10-10T12:00:01Z'},now),false);assert.equal(utils.isNewUpload({uploadedAt:'2026-10-10T11:30:00Z',trashedAt:'2026-10-10T11:40:00Z'},now),false);});

 test('Recent defaults to newest first while other folders retain name order',()=>{const media=[{id:'old',name:'a-old.txt',createdAt:'2020-01-01',variants:[]},{id:'new',name:'z-new.txt',createdAt:'2026-10-10',variants:[]}];assert.deepEqual(utils.filteredFiles(media,{folder:'Recent'}).map(x=>x.id),['new','old']);assert.deepEqual(utils.filteredFiles(media,{folder:'All files'}).map(x=>x.id),['old','new']);});
