import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {normalizeWorkbook,mergeCards} from '../src/shared/idea-bank.js';import {ideaResponse,validateCard} from '../server/idea-service.js';import {authResponse} from '../server/owner-auth.js';
const source={'Creative Matrix':[['ردیف','صنعت','شخصیت','صفت','شماره','برند','ارتباط','محصول'],['1','Agriculture','Sincerity','Earthy','1','Terra: soil','John Deere: map','App: dashboard'],['','','','','2','Brand two','','']],Influence:[['ردیف','نام','سبک'],['1','Paul Rand','Modern']]};
test('matrix expands three disciplines, carries merged context and leaves references unchecked',()=>{const c=normalizeWorkbook(source);assert.equal(c.length,5);assert.equal(c[3].industry,'Agriculture');assert.equal(c[4].matrix,false);assert.equal(new Set(c.map(v=>v.id)).size,5);});
test('merge updates descriptions without losing stable selections and keeps previous references',()=>{const old=normalizeWorkbook(source),copy=structuredClone(source);copy['Creative Matrix'][1][5]='Terra: revised';const incoming=normalizeWorkbook({'Creative Matrix':copy['Creative Matrix']});assert.equal(incoming[0].id,old[0].id);const merged=mergeCards(old,incoming);assert.equal(merged.length,5);assert.equal(merged[0].body,'Terra: revised');});
test('empty workbook and malformed or oversized cards fail validation',()=>{assert.throws(()=>normalizeWorkbook({Empty:[[]]}));const card=normalizeWorkbook(source)[0];assert.equal(validateCard(card),card);assert.throws(()=>validateCard({...card,fields:[{label:'x',value:4}]}));assert.throws(()=>validateCard({...card,body:'x'.repeat(20001)}));});
async function fixture(){const sqlite=new DatabaseSync(':memory:');const DB={prepare(sql){const args=[];return {bind(...values){args.push(...values);return this},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}}}},async batch(statements){return Promise.all(statements.map(s=>s.run()))}};const env={DB,OWNER_PASSWORD:'fixture-password',OWNER_SESSION_SECRET:'fixture-secret',OWNER_RATE_LIMITER:{limit:async()=>({success:true})}};const login=await authResponse(new Request('https://test.example/api/owner/login',{method:'POST',headers:{Origin:'https://test.example','Content-Type':'application/json'},body:JSON.stringify({password:env.OWNER_PASSWORD})}),env);const cookie=login.headers.get('Set-Cookie').split(';')[0];const call=(action,body,origin='https://test.example')=>ideaResponse(new Request('https://test.example/api/ideas'+(action?'/'+action:''),{method:body?'POST':'GET',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);return {call,env,sqlite};}
test('staged imports stay invisible, commit atomically and reject concurrent stale replacement',async()=>{const {call}=await fixture(),cards=normalizeWorkbook(source);const begin=await (await call('begin',{count:cards.length,name:'fixture.xlsx',base:null})).json();const second=await (await call('begin',{count:cards.length,name:'other.xlsx',base:null})).json();await call('batch',{id:begin.id,cards:cards.slice(0,2)});assert.equal((await call('commit',{id:begin.id})).status,409);assert.equal((await (await call()).json()).cards.length,0);await call('batch',{id:begin.id,cards});assert.equal((await call('commit',{id:begin.id})).status,200);await call('batch',{id:second.id,cards});assert.equal((await call('commit',{id:second.id})).status,409);assert.equal((await (await call()).json()).cards.length,5);});
test('checks survive replacement, reference cards cannot be checked, authentication and origin enforced',async()=>{const {call,env}=await fixture(),cards=normalizeWorkbook(source);const v=await (await call('begin',{count:5,name:'one',base:null})).json();await call('batch',{id:v.id,cards});await call('commit',{id:v.id});assert.equal((await call('check',{id:cards[0].id,checked:true})).status,200);assert.equal((await call('check',{id:cards[4].id,checked:true})).status,400);const next=await (await call('begin',{count:5,name:'two',base:v.id})).json();await call('batch',{id:next.id,cards});await call('commit',{id:next.id});assert.deepEqual((await (await call()).json()).checked,[cards[0].id]);assert.equal((await call('check',{id:cards[0].id,checked:false},'https://evil.example')).status,403);assert.equal((await ideaResponse(new Request('https://test.example/api/ideas'),env)).status,401);});
