import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {verifyMailWebhook,validateMail,mailboxResponse} from '../server/mailbox-service.js';
test('mail webhook rejects forged, changed and stale deliveries',async()=>{const raw='{"type":"email.received"}',timestamp=Math.floor(Date.now()/1000),secret=Buffer.from('test-signing-secret').toString('base64'),id='event-123';const signature=createHmac('sha256',Buffer.from(secret,'base64')).update(`${id}.${timestamp}.${raw}`).digest('base64');const headers=new Headers({'svix-id':id,'svix-timestamp':String(timestamp),'svix-signature':'v1,'+signature});assert.equal(await verifyMailWebhook(raw,headers,'whsec_'+secret),true);assert.equal(await verifyMailWebhook(raw+'x',headers,'whsec_'+secret),false);assert.equal(await verifyMailWebhook(raw,headers,'whsec_'+secret,Date.now()+600000),false);});
test('mail rejects header injection and multiple recipients',()=>{assert.throws(()=>validateMail({recipient:'a@b.test',subject:'Hello\r\nBcc: x@y.test',body:'hi'}));assert.throws(()=>validateMail({recipient:'a@b.test, x@y.test',subject:'Hello',body:'hi'}));assert.deepEqual(validateMail({recipient:'a@b.test',subject:'Hello',body:'سلام'}),{recipient:'a@b.test',subject:'Hello',body:'سلام'});});
test('mail API refuses anonymous reads and unsigned inbound mail',async()=>{assert.equal((await mailboxResponse(new Request('https://test/api/studio/mail'),{})).status,401);assert.equal((await mailboxResponse(new Request('https://test/api/mail/inbound',{method:'POST',body:'{}'}),{RESEND_API_KEY:'fixture',RESEND_WEBHOOK_SECRET:'whsec_fixture'})).status,401);});

import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
function mailboxFixture(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../server/migrations/0004_mailbox.sql',import.meta.url),'utf8'));const env={OWNER_SESSION_SECRET:'test-secret',DB:{prepare(sql){return {bind(...values){return {async first(){return db.prepare(sql).get(...values)||null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){return {meta:{changes:db.prepare(sql).run(...values).changes}};}};}};}},OWNER_RATE_LIMITER:{limit:async()=>({success:true})},RESEND_API_KEY:'fixture',RESEND_DOMAIN_READY:'true'};const body=Buffer.from(JSON.stringify({role:'owner',exp:Date.now()+600000,origin:'https://site.test'})).toString('base64url');const cookie='pol_owner='+body+'.'+createHmac('sha256',env.OWNER_SESSION_SECRET).update(body).digest('base64url');const request=(path,data,origin='https://site.test')=>new Request('https://site.test'+path,{headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'},...(data?{method:'POST',body:JSON.stringify(data)}:{})});return {db,env,request};}
test('drafts stay editable, send is claimed once and trash restores sent mail',async()=>{const {db,env,request}=mailboxFixture(),original=globalThis.fetch;let sends=0;globalThis.fetch=async()=>{sends++;return Response.json({id:'provider-123'});};try{const mail={id:crypto.randomUUID(),recipient:'owner@example.test',subject:'A conversation',body:'Hello'};assert.equal((await mailboxResponse(request('/api/studio/mail/draft',mail),env)).status,200);assert.equal(db.prepare('SELECT folder FROM mailbox_messages').get().folder,'drafts');assert.equal((await mailboxResponse(request('/api/studio/mail/send',mail),env)).status,200);assert.equal((await mailboxResponse(request('/api/studio/mail/send',mail),env)).status,200);assert.equal(sends,1);await mailboxResponse(request('/api/studio/mail/update',{id:mail.id,action:'trash'}),env);assert.equal(db.prepare('SELECT folder FROM mailbox_messages').get().folder,'trash');await mailboxResponse(request('/api/studio/mail/update',{id:mail.id,action:'restore'}),env);assert.equal(db.prepare('SELECT folder FROM mailbox_messages').get().folder,'sent');assert.equal((await mailboxResponse(request('/api/studio/mail/send',mail,'https://evil.test'),env)).status,403);}finally{globalThis.fetch=original;}});
test('an uncertain send cannot be blindly repeated',async()=>{const {db,env,request}=mailboxFixture(),original=globalThis.fetch;let sends=0;globalThis.fetch=async()=>{sends++;throw Error('lost response');};try{const mail={id:crypto.randomUUID(),recipient:'owner@example.test',subject:'Hello',body:'Test'};assert.equal((await mailboxResponse(request('/api/studio/mail/send',mail),env)).status,503);assert.equal(db.prepare('SELECT status FROM mailbox_messages').get().status,'uncertain');assert.equal((await mailboxResponse(request('/api/studio/mail/send',mail),env)).status,409);assert.equal(sends,1);}finally{globalThis.fetch=original;}});
