import test from 'node:test';import assert from 'node:assert/strict';import {marketingAction} from '../server/marketing-service.js';import {marketingMetrics,marketingTemplates,marketingWeek} from '../src/cms/marketing-catalog.js';import {siteProgress} from '../src/cms/site-progress.js';
const initial=()=>({revision:7,draft:{projects:[]},published:{projects:[]}}),now=new Date('2026-10-09T10:00:00Z');
function program(){return marketingAction(initial(),{revision:7,action:'create-program',templateId:'b2b',ongoing:true},now);}
test('owner-created ongoing programs have no required end and templates schedule only on request',()=>{const s=program();assert.equal(s.marketing.tasks.length,0);assert.equal(s.marketing.programs[0].ongoing,true);assert.equal(s.marketing.programs[0].end,'');const id=s.marketing.programs[0].id,b={revision:7,action:'add-week',programId:id};const first=marketingAction(s,b,now),second=marketingAction(first,b,now);assert.equal(first.marketing.tasks.length,4);assert.deepEqual(second.marketing.tasks,first.marketing.tasks);assert.throws(()=>marketingAction(s,{...b,revision:6},now),{status:409});assert.throws(()=>marketingAction(initial(),{revision:7,action:'create-program',title:'Test',ongoing:false,start:'2026-10-09',end:'2026-10-01'},now),/end date/);});
test('manual tasks, results and reticking do not duplicate marketing XP',()=>{let s=program(),id=s.marketing.programs[0].id;s=marketingAction(s,{revision:7,action:'add-task',programId:id,title:'Prepare the client-specific deck'},now);const taskId=s.marketing.tasks[0].id;s=marketingAction(s,{revision:7,action:'update-task',taskId,done:true,outcome:{leads:2,meetings:1,wins:0}},now);assert.equal(marketingMetrics(s.marketing).xp,10);assert.equal(marketingMetrics(s.marketing).outcomes.leads,2);s=marketingAction(s,{revision:7,action:'update-task',taskId,done:false},now);assert.equal(marketingMetrics(s.marketing).xp,0);s=marketingAction(s,{revision:7,action:'update-task',taskId,done:true},new Date('2026-10-20T12:00:00Z'));assert.equal(marketingMetrics(s.marketing).xp,10);assert.equal(s.marketing.tasks[0].creditWeek,marketingWeek(now));assert.throws(()=>marketingAction(s,{revision:7,action:'update-task',taskId,evidence:'javascript:alert(1)'},now),/HTTP/);});
test('weekly XP is bounded and cannot inflate content quality scores',()=>{const m={tasks:Array.from({length:30},(_,i)=>({id:String(i),done:true,creditWeek:marketingWeek(now)}))};assert.equal(marketingMetrics(m).xp,100);const before=siteProgress(),after=siteProgress({marketingXp:100});assert.equal(after.xp,before.xp+100);assert.equal(after.score,before.score);assert.equal(marketingTemplates.length>180,true);});
test('program edits preserve private project data and accept explicit scheduling changes',()=>{const s=program(),id=s.marketing.programs[0].id;const updated=marketingAction(s,{revision:7,action:'update-program',programId:id,title:'My own plan',ongoing:false,start:'2026-10-09',end:'2026-12-09',templates:[]},now);assert.deepEqual(updated.draft,s.draft);assert.deepEqual(updated.published,s.published);assert.equal(updated.marketing.programs[0].ongoing,false);assert.throws(()=>marketingAction(s,{revision:7,action:'add-task',programId:id,title:'Task',due:'2026-02-30'},now),/calendar date/);});

test('task board transitions persist started time and credit only completion; bilingual templates remain usable',()=>{let s={revision:1};s=marketingAction(s,{action:'create-program',revision:1,title:'Board'});const programId=s.marketing.programs[0].id;s=marketingAction(s,{action:'add-task',revision:1,programId,title:'Start this',status:'doing'},new Date('2026-10-09T10:00:00Z'));const t=s.marketing.tasks[0];assert.equal(t.status,'doing');assert.ok(t.startedAt);assert.equal(marketingMetrics(s.marketing).xp,0);s=marketingAction(s,{action:'update-task',revision:1,taskId:t.id,status:'done'},new Date('2026-10-09T11:00:00Z'));assert.equal(marketingMetrics(s.marketing).xp,10);s=marketingAction(s,{action:'update-task',revision:1,taskId:t.id,status:'doing'},new Date('2026-10-16T11:00:00Z'));assert.equal(marketingMetrics(s.marketing).xp,0);assert.equal(s.marketing.tasks[0].startedAt,'2026-10-09T10:00:00.000Z');assert.throws(()=>marketingAction(s,{action:'update-task',revision:1,taskId:t.id,status:'invented'}),/status/);assert.ok(marketingTemplates.filter(t=>t.language==='fa'&&t.id.includes('action')).length>=24);assert.ok(marketingTemplates.filter(t=>t.language==='en'&&t.id.includes('action')).length>=24);});
