import test from 'node:test';import assert from 'node:assert/strict';
import {backupManifest,validateManifest,checksum,mediaBackupResponse} from '../server/media-backup.js';
import {createMediaArchive,readMediaArchive} from '../src/cms/media-archive.js';
import {authResponse} from '../server/owner-auth.js';
const fixture=()=>({revision:3,draft:{title:'Keep draft'},published:{title:'Keep live'},media:[{id:'asset-1',name:'طرح.webp',alt:'Artwork',folder:'Projects/Brand',type:'image/webp',createdAt:'2026-10-01',trashedAt:'2026-10-02',variants:[{width:640,size:4,asset:{local:'original'}}]}],customMediaFolders:['Projects/Brand/Empty'],mediaFolderLocations:{'Projects/Brand':'Projects/Brand'}});
async function setup(){let state=fixture();const values=new Map(),files=new Map([['original',new Uint8Array([1,2,3,4])]]);const env={OWNER_RATE_LIMITER:{limit:async()=>({success:true})},OWNER_PASSWORD:'test-password-fixture',OWNER_SESSION_SECRET:'test-secret-fixture',DESARTLY_AUTH:{get:async(k)=>values.has(k)?JSON.parse(values.get(k)):null,put:async(k,v)=>values.set(k,v)}};const r=await authResponse(new Request('https://site.test/api/owner/login',{method:'POST',headers:{Origin:'https://site.test','Content-Type':'application/json'},body:JSON.stringify({password:env.OWNER_PASSWORD})}),env);const cookie=r.headers.get('Set-Cookie').split(';')[0];const store={read:async()=>structuredClone(state),write:async(s,expected)=>{assert.equal(state.revision,expected);state={...s,revision:expected+1};}};const storage={put:async(id,bytes)=>{files.set(id,bytes);return {local:id};},get:async(asset)=>new Response(files.get(asset.local))};const call=(path='',body,headers={})=>mediaBackupResponse(new Request('https://site.test/api/studio/media-backup'+path,{method:body===undefined?'GET':'POST',headers:{Cookie:cookie,Origin:'https://site.test',...headers},...(body!==undefined?{body:typeof body==='string'||body instanceof Uint8Array?body:JSON.stringify(body)}:{})}),env,store,storage);return {call,store,storage,env,state:()=>state,set:s=>state=s};}
async function archiveFor(state){return createMediaArchive(backupManifest(state),async()=>new Uint8Array([1,2,3,4]));}
test('ZIP round trip keeps Unicode metadata, empty folders, trash and exact bytes without provider secrets',async()=>{const blob=await archiveFor(fixture()),{manifest,entries}=await readMediaArchive(blob);assert.equal(manifest.media[0].name,'طرح.webp');assert.equal(manifest.media[0].trashedAt,'2026-10-02');assert.deepEqual(entries.get('files/Projects/Brand/asset-1--0--طرح.webp'),new Uint8Array([1,2,3,4]));assert.ok(manifest.folders.includes('Projects/Brand/Empty'));assert.ok(manifest.folders.includes('Projects'));assert.ok(!JSON.stringify(manifest).includes('original'));});
test('manifest rejects traversal, duplicate identities and oversized entries',async()=>{const {manifest}=await readMediaArchive(await archiveFor(fixture()));for(const mutate of [m=>m.media[0].folder='../oops',m=>m.media.push(m.media[0]),m=>m.media[0].variants[0].path='files/../oops',m=>m.media[0].variants[0].size=13*1024*1024]){const copy=structuredClone(manifest);mutate(copy);assert.throws(()=>validateManifest(copy));}});
test('backup routes require owner authentication and same-origin restores',async()=>{const x=await setup();assert.equal((await mediaBackupResponse(new Request('https://site.test/api/studio/media-backup'),x.env,x.store,x.storage)).status,401);assert.equal((await x.call('/restore',{}, {Origin:'https://other.test'})).status,403);assert.equal((await x.call('/file?id=asset-1&variant=0&source=changed')).status,409);});
test('restore stages verified files and atomically preserves unrelated content and new media',async()=>{const x=await setup(),{manifest,entries}=await readMediaArchive(await archiveFor(fixture()));const {session}=await(await x.call('/restore',manifest)).json();assert.equal((await x.call('/commit?session='+session,{})).status,409);assert.equal(x.state().revision,3);assert.equal((await x.call(`/restore-file?session=${session}&id=asset-1&variant=0`,new Uint8Array([0,0,0,0]))).status,422);assert.equal((await x.call(`/restore-file?session=${session}&id=asset-1&variant=0`,entries.get('files/Projects/Brand/asset-1--0--طرح.webp'))).status,200);const s=x.state();s.media.push({...s.media[0],id:'later'});x.set(s);assert.equal((await x.call('/commit?session='+session,{})).status,200);assert.equal(x.state().media.length,2);assert.deepEqual(x.state().draft,{title:'Keep draft'});assert.deepEqual(x.state().published,{title:'Keep live'});assert.equal((await x.call('/commit?session='+session,{})).status,200);assert.equal(x.state().revision,4);});
test('restore rejects concurrent edits to matching media instead of overwriting them',async()=>{const x=await setup(),{manifest,entries}=await readMediaArchive(await archiveFor(fixture()));const {session}=await(await x.call('/restore',manifest)).json();await x.call(`/restore-file?session=${session}&id=asset-1&variant=0`,entries.get('files/Projects/Brand/asset-1--0--طرح.webp'));x.state().media[0].name='New name';assert.equal((await x.call('/commit?session='+session,{})).status,409);assert.equal(x.state().media[0].name,'New name');});

test('temporary backup reader cannot authorize writes and expires',async()=>{
 const {checksum}=await import('../server/media-backup.js');const token='c'.repeat(64),ticket={hash:await checksum(new TextEncoder().encode(token)),expiresAt:new Date(Date.now()+60000).toISOString()};
 const env={BACKUP_READ_TICKET:JSON.stringify(ticket)},store={read:async()=>({media:[],customMediaFolders:[]})};
 const get=()=>mediaBackupResponse(new Request('https://site.test/api/studio/media-backup',{headers:{Authorization:'Bearer '+token}}),env,store,{});
 assert.equal((await get()).status,200);
 const denied=await mediaBackupResponse(new Request('https://site.test/api/studio/media-backup/restore',{method:'POST',headers:{Origin:'https://site.test',Authorization:'Bearer '+token},body:'{}'}),env,store,{});assert.equal(denied.status,401);
 ticket.expiresAt='2020-01-01T00:00:00Z';env.BACKUP_READ_TICKET=JSON.stringify(ticket);assert.equal((await get()).status,401);
});
