import test from 'node:test';import assert from 'node:assert/strict';
import {authResponse,isOwner,ownerPath,safeNext} from '../server/owner-auth.js';
import worker from '../server/worker.js';
const env={OWNER_PASSWORD:'test-only-fixture-password',OWNER_SESSION_SECRET:'test-only-fixture-session-secret',OWNER_RATE_LIMITER:{limit:async()=>({success:true})}};
function login(password,origin='https://pol.example'){return new Request('https://pol.example/api/owner/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({password})})}
test('owner login rejects wrong passwords, cross-origin submissions and missing secrets',async()=>{assert.equal((await authResponse(login('wrong'),env)).status,401);assert.equal((await authResponse(login(env.OWNER_PASSWORD,'https://other.example'),env)).status,403);assert.equal((await authResponse(login('anything'),{})).status,503)});
test('signed owner cookie authenticates and rejects tampering or a different origin',async()=>{const response=await authResponse(login(env.OWNER_PASSWORD),env);assert.equal(response.status,200);const header=response.headers.get('Set-Cookie');assert.match(header,/HttpOnly/);assert.match(header,/SameSite=Strict/);assert.match(header,/Secure/);const cookie=header.split(';')[0];assert.equal(await isOwner(new Request('https://pol.example/edit',{headers:{Cookie:cookie}}),env),true);assert.equal(await isOwner(new Request('https://pol.example/edit',{headers:{Cookie:cookie+'x'}}),env),false);assert.equal(await isOwner(new Request('https://other.example/edit',{headers:{Cookie:cookie}}),env),false)});
test('protected suffix pages redirect before static assets are served',async()=>{let called=false;const response=await worker.fetch(new Request('https://pol.example/work/example/edit'),{...env,ASSETS:{fetch:async()=>{called=true;return new Response('private')}}});assert.equal(response.status,302);assert.equal(called,false);assert.equal(response.headers.get('Location'),'/login?next=%2Fwork%2Fexample%2Fedit');for(const path of ['/edit','/new','/work/new','/about/edit','/work/post/edit/'])assert.equal(ownerPath(path),true);assert.equal(ownerPath('/work'),false);assert.equal(safeNext('//evil.example'),'/edit')});
test('rate limits and oversized bodies fail closed',async()=>{assert.equal((await authResponse(login('anything'),{...env,OWNER_RATE_LIMITER:{limit:async()=>({success:false})}})).status,429);assert.equal((await authResponse(login('x'.repeat(3000)),env)).status,413)});
test('password changes require owner and current password, hash storage and invalidate old sessions',async()=>{let record=null;const local={...env,DESARTLY_AUTH:{get:async()=>record,put:async(k,v)=>{record=JSON.parse(v)}}};const initial=await authResponse(login(env.OWNER_PASSWORD),local);const cookie=initial.headers.get('Set-Cookie').split(';')[0];const change=(password,newPassword,cookieValue=cookie)=>new Request('https://pol.example/api/owner/password',{method:'POST',headers:{Origin:'https://pol.example','Content-Type':'application/json',Cookie:cookieValue},body:JSON.stringify({password,newPassword})});assert.equal((await authResponse(change(env.OWNER_PASSWORD,'new-fixture-password',''),local)).status,401);assert.equal((await authResponse(change('wrong','new-fixture-password'),local)).status,401);assert.equal((await authResponse(change(env.OWNER_PASSWORD,'short'),local)).status,400);assert.equal((await authResponse(change(env.OWNER_PASSWORD,'new-fixture-password'),local)).status,200);assert.ok(record.hash);assert.ok(!JSON.stringify(record).includes('new-fixture-password'));assert.equal(await isOwner(new Request('https://pol.example/edit',{headers:{Cookie:cookie}}),local),false);assert.equal((await authResponse(login(env.OWNER_PASSWORD),local)).status,401);assert.equal((await authResponse(login('new-fixture-password'),local)).status,200)});
