import test from 'node:test';import assert from 'node:assert/strict';
import {buildPresentation,presentationFrames,shortCopy} from '../src/cms/presentation-model.js';
import {composition} from '../src/layouts.js';
test('all 20 CMS compositions map every slot once within the guide page',()=>{for(let id=1;id<=20;id++){const frames=presentationFrames(id);assert.equal(frames.length,composition(id).boxes.length);assert.equal(new Set(frames.map(f=>`${f.x},${f.y}`)).size,frames.length);for(const f of frames){assert.ok(f.w>0&&f.h>0&&f.x>=0&&f.y>=0);assert.ok(f.x+f.w<=1920&&f.y+f.h<=1121);}}});
test('cover, identity and closing are automatic; source stays unchanged',()=>{const project={id:'demo',title:'Demo',summary:'A distinctive identity for a new brand.',coverImage:'/cover',clientName:'Client',blocks:[{id:'story',type:'text',title:'Idea',text:'My idea.'},{id:'visual',type:'grid',preset:5,images:['/a','/b','/c']}]};const original=structuredClone(project);const {slides}=buildPresentation(project);assert.deepEqual(slides.map(s=>s.type),['cover','identity','images','closing']);assert.equal(slides[0].description,project.summary);assert.equal(slides[2].title,'Idea');assert.equal(slides[1].fields.find(f=>f.label==='Client').value,'Client');assert.deepEqual(project,original);const updated=buildPresentation({...project,title:'Updated'});assert.equal(updated.slides[0].title,'Updated');});
test('extra images are preserved on continuation slides; hidden blocks excluded',()=>{const {slides,warnings}=buildPresentation({title:'Demo',blocks:[{type:'grid',preset:1,images:['/a','/b','/c','/d']},{type:'image',image:'/hidden',hidden:true},{type:'html',id:'interactive'}]});assert.deepEqual(slides.filter(s=>s.type==='images').flatMap(s=>s.images),['/a','/b','/c','/d']);assert.ok(warnings.some(s=>s.includes('static image')));assert.ok(warnings.some(s=>s.includes('cover')));});
test('short copy ends at sentence boundaries where possible',()=>{assert.equal(shortCopy('First complete sentence. Second sentence with more details.',30),'First complete sentence.');assert.ok(shortCopy('A long string of words to fit the slide without overflow',25).length<=25);});

import {pdfFontStyle} from '../src/cms/presentation-renderer.js';
test('native PDF preserves browser-normalized bold weights',()=>{assert.equal(pdfFontStyle('bold 108px PresentationManrope'),'bold');assert.equal(pdfFontStyle('700 108px PresentationManrope'),'bold');assert.equal(pdfFontStyle('30px PresentationManrope'),'normal');});

import {buildInstagramPresentation,INSTAGRAM_PAGE} from '../src/cms/presentation-model.js';
test('Instagram uses portrait dimensions and preserves images with readable profile batches',()=>{assert.deepEqual(INSTAGRAM_PAGE,{width:1080,height:1350});const project={title:'Demo',summary:'An identity.',clientName:'Client',role:'Designer',deliverables:'Identity',challenge:'Positioning',credits:'Studio',blocks:[{type:'grid',preset:5,images:['/a','/b','/c','/d']}]};const before=structuredClone(project),{slides}=buildInstagramPresentation(project);assert.deepEqual(slides.filter(s=>s.type==='images').flatMap(s=>s.images),['/a','/b','/c','/d']);assert.ok(slides.filter(s=>s.type==='images').every(s=>s.images.length<=2));assert.ok(slides.filter(s=>s.type==='identity').every(s=>s.fields.length<=4));assert.ok(slides.every((s,i)=>s.pageNumber===i+1&&s.totalPages===slides.length));assert.deepEqual(project,before);});

test('Instagram image captions use a complete opening sentence',()=>{const {slides}=buildInstagramPresentation({title:'Demo',blocks:[{type:'text',title:'Idea',text:'A clear opening sentence. More detail follows.'},{type:'image',image:'/a'}]});assert.equal(slides.find(s=>s.type==='images').text,'A clear opening sentence.');});

test('Instagram profile never exceeds two pages and retains every field',()=>{const project={title:'Full profile',clientName:'Client',discipline:'Branding',industry:'Retail',role:'Designer',deliverables:'Deliverables '.repeat(20),challenge:'Challenge '.repeat(24),credits:'Credits '.repeat(24)};const expected=buildPresentation(project).slides.find(s=>s.type==='identity').fields;const profiles=buildInstagramPresentation(project).slides.filter(s=>s.type==='identity');assert.ok(profiles.length<=2);assert.deepEqual(profiles.flatMap(s=>s.fields),expected);});

import {panoramaCrop,panoramaPlacement} from '../src/cms/presentation-model.js';
test('landscape single image becomes two adjoining full-bleed panels after its story',()=>{const {slides}=buildInstagramPresentation({title:'Demo',blocks:[{type:'text',title:'Story',text:'Context.'},{type:'image',image:'/wide'},{type:'image',image:'/tall'}]},{'/wide':{width:2400,height:1357},'/tall':{width:1536,height:2048}});const pair=slides.filter(s=>s.type==='panorama');assert.deepEqual(pair.map(s=>s.panel),[0,1]);assert.ok(slides.findIndex(s=>s.type==='story')<slides.indexOf(pair[0]));assert.equal(slides.filter(s=>s.type==='images').length,1);for(const [w,h] of [[2400,1357],[2400,1600],[4000,1000]]){const a=panoramaCrop(w,h,0),b=panoramaCrop(w,h,1);assert.equal(a.x+a.w,b.x);assert.equal(a.y,b.y);assert.ok(a.x>=0&&b.x+b.w<=w+.00001);assert.equal(a.x,0);assert.equal(a.y,0);assert.equal(a.w+b.w,w);assert.equal(a.h,h);const da=panoramaPlacement(w,h,0),db=panoramaPlacement(w,h,1);assert.equal(da.x+da.w,1080+db.x);assert.ok(Math.abs(da.w/da.h-a.w/a.h)<1e-9);assert.ok(da.w<=a.w&&da.h<=a.h);assert.ok(da.y>=0&&da.y+da.h<=1350);}});

test('Instagram paired images receive a separate story so visuals keep enough space',()=>{const {slides}=buildInstagramPresentation({title:'Pair',blocks:[{type:'text',title:'Context',text:'A complete account of the design.'},{type:'grid',preset:1,images:['/one','/two']}]});const story=slides.find(s=>s.type==='story'),visual=slides.find(s=>s.type==='images');assert.equal(story.text,'A complete account of the design.');assert.equal(visual.text,'');assert.equal(visual.title,'');assert.deepEqual(visual.images,['/one','/two']);assert.equal(visual.fit,'contain');});

test('interactive blocks use their static snapshot in exports without changing the website source',()=>{const project={title:'Demo',coverImage:'/cover',blocks:[{id:'interactive',type:'html',html:'<button>Live interaction</button>',staticImage:'/snapshot',staticAlt:'Interface overview'}]},before=structuredClone(project);const {slides,warnings}=buildPresentation(project);assert.deepEqual(slides.filter(s=>s.type==='images').flatMap(s=>s.images),['/snapshot']);assert.equal(warnings.length,0);assert.deepEqual(project,before);});
