import test from 'node:test';import assert from 'node:assert/strict';
import {buildPresentation,presentationFrames,shortCopy} from '../src/cms/presentation-model.js';
import {composition} from '../src/layouts.js';
test('all 20 CMS compositions map every slot once within the guide page',()=>{for(let id=1;id<=20;id++){const frames=presentationFrames(id);assert.equal(frames.length,composition(id).boxes.length);assert.equal(new Set(frames.map(f=>`${f.x},${f.y}`)).size,frames.length);for(const f of frames){assert.ok(f.w>0&&f.h>0&&f.x>=0&&f.y>=0);assert.ok(f.x+f.w<=1920&&f.y+f.h<=1121);}}});
test('cover, identity and closing are automatic; source stays unchanged',()=>{const project={id:'demo',title:'Demo',summary:'A distinctive identity for a new brand.',coverImage:'/cover',clientName:'Client',blocks:[{id:'story',type:'text',title:'Idea',text:'My idea.'},{id:'visual',type:'grid',preset:5,images:['/a','/b','/c']}]};const original=structuredClone(project);const {slides}=buildPresentation(project);assert.deepEqual(slides.map(s=>s.type),['cover','identity','images','closing']);assert.equal(slides[0].description,project.summary);assert.equal(slides[2].title,'Idea');assert.equal(slides[1].fields.find(f=>f.label==='Client').value,'Client');assert.deepEqual(project,original);const updated=buildPresentation({...project,title:'Updated'});assert.equal(updated.slides[0].title,'Updated');});
test('extra images are preserved on continuation slides; hidden blocks excluded',()=>{const {slides,warnings}=buildPresentation({title:'Demo',blocks:[{type:'grid',preset:1,images:['/a','/b','/c','/d']},{type:'image',image:'/hidden',hidden:true},{type:'html',id:'interactive'}]});assert.deepEqual(slides.filter(s=>s.type==='images').flatMap(s=>s.images),['/a','/b','/c','/d']);assert.ok(warnings.some(s=>s.includes('static image')));assert.ok(warnings.some(s=>s.includes('cover')));});
test('short copy ends at sentence boundaries where possible',()=>{assert.equal(shortCopy('First complete sentence. Second sentence with more details.',30),'First complete sentence.');assert.ok(shortCopy('A long string of words to fit the slide without overflow',25).length<=25);});

import {pdfFontStyle} from '../src/cms/presentation-renderer.js';
test('native PDF preserves browser-normalized bold weights',()=>{assert.equal(pdfFontStyle('bold 108px PresentationManrope'),'bold');assert.equal(pdfFontStyle('700 108px PresentationManrope'),'bold');assert.equal(pdfFontStyle('30px PresentationManrope'),'normal');});

import {buildInstagramPresentation,INSTAGRAM_PAGE} from '../src/cms/presentation-model.js';
test('Instagram uses portrait dimensions and preserves images with readable profile batches',()=>{assert.deepEqual(INSTAGRAM_PAGE,{width:1080,height:1350});const project={title:'Demo',summary:'An identity.',clientName:'Client',role:'Designer',deliverables:'Identity',challenge:'Positioning',credits:'Studio',blocks:[{type:'grid',preset:5,images:['/a','/b','/c','/d']}]};const before=structuredClone(project),{slides}=buildInstagramPresentation(project);assert.deepEqual(slides.filter(s=>s.type==='images').flatMap(s=>s.images),['/a','/b','/c','/d']);assert.ok(slides.filter(s=>s.type==='images').every(s=>s.images.length<=2));assert.ok(slides.filter(s=>s.type==='identity').every(s=>s.fields.length<=3));assert.ok(slides.every((s,i)=>s.pageNumber===i+1&&s.totalPages===slides.length));assert.deepEqual(project,before);});

test('Instagram image captions use a complete opening sentence',()=>{const {slides}=buildInstagramPresentation({title:'Demo',blocks:[{type:'text',title:'Idea',text:'A clear opening sentence. More detail follows.'},{type:'image',image:'/a'}]});assert.equal(slides.find(s=>s.type==='images').text,'A clear opening sentence.');});
