import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {safeMessage,safePath,writeLog,pruneLogs,logsResponse} from '../server/runtime-logs.js';
import {authResponse} from '../server/owner-auth.js';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../server/migrations/0012_runtime_logs.sql',import.meta.url),'utf8'));const binding={prepare(sql){let args=[];return {bind(...values){args=values;return this;},async run(){return {meta:{changes:db.prepare(sql).run(...args).changes}};},async all(){return {results:db.prepare(sql).all(...args)};}};}};return {db,env:{DB:binding}};}
test('runtime messages redact credential, email and URL values and never retain URL queries',()=>{const message=safeMessage('token=private password=hidden Bearer abc.def mail user@example.com https://site.test/?secret=123');for(const value of ['private','hidden','abc.def','user@example.com','secret=123'])assert.ok(!message.includes(value));assert.equal(safePath('https://site.test/upload?token=secret'),'/upload');assert.equal(safeMessage('x'.repeat(3000)).length,1000);});
test('logs persist outside portfolio state and enforce time and count retention',async()=>{const {db,env}=fixture();await writeLog(env,{source:'worker',event:'POST request',path:'/api/upload?secret=x',status:503,requestId:'trace',duration:12.5,message:'password=private'});let row=db.prepare('SELECT * FROM runtime_logs').get();assert.equal(row.status,503);assert.equal(row.duration_ms,13);assert.equal(row.path,'/api/upload');assert.ok(!row.message.includes('private'));db.prepare('UPDATE runtime_logs SET created_at=?').run('2020-01-01T00:00:00.000Z');await pruneLogs(env);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM runtime_logs').get().n,0);});
test('monitoring viewer is private and public ingestion rejects foreign origins and abuse',async()=>{const {env}=fixture();assert.equal((await logsResponse(new Request('https://site.test/api/studio/logs'),env,{})).status,401);assert.equal((await logsResponse(new Request('https://site.test/api/runtime-log',{method:'POST',headers:{Origin:'https://evil.test'},body:'{}'}),env,{})).status,403);assert.equal((await logsResponse(new Request('https://site.test/api/runtime-log',{method:'POST',headers:{Origin:'https://site.test'},body:'{}'}),env,{})).status,202);});
test('owner can filter and trace logs with bounded cursor pagination',async()=>{
 const {env}=fixture();Object.assign(env,{OWNER_PASSWORD:'fixture-password',OWNER_SESSION_SECRET:'fixture-secret',OWNER_RATE_LIMITER:{limit:async()=>({success:true})}});
 const auth=await authResponse(new Request('https://site.test/api/owner/login',{method:'POST',headers:{Origin:'https://site.test','Content-Type':'application/json'},body:JSON.stringify({password:env.OWNER_PASSWORD})}),env);const cookie=auth.headers.get('Set-Cookie').split(';')[0];
 for(let i=0;i<103;i++)await writeLog(env,{level:i===102?'warning':'error',event:'upload',path:'/api/upload',requestId:'trace-1',message:'Failed'});
 const call=async query=>(await logsResponse(new Request('https://site.test/api/studio/logs?'+query,{headers:{Cookie:cookie}}),env,{})).json();
 const first=await call('level=error&trace=trace-1');assert.equal(first.items.length,100);assert.ok(first.next);assert.equal(first.stats.find(s=>s.level==='error').count,102);
 const second=await call('level=error&trace=trace-1&cursor='+encodeURIComponent(first.next));assert.equal(second.items.length,2);assert.equal(second.next,null);assert.ok(second.items.every(item=>!first.items.some(a=>a.id===item.id)));
});
