import {unzipSync} from 'fflate';
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {presentationVersion,projectImages,projectCaption} from '../src/cms/telegram-materials.js';
import {handleUpdate} from '../server/telegram-service.js';
import {queueBookingNotifications,flushTelegramDeliveries,enqueueDelivery} from '../server/telegram-delivery.js';
import {operationAction} from '../server/telegram-operations.js';
import {savePresentation,presentationRenderResponse,projectImage} from '../server/telegram-material-service.js';
import {schedule,updateSchedule,defaultSchedule} from '../server/calendar-service.js';
function fixture(){const db=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('../server/migrations/',import.meta.url)).sort())db.exec(readFileSync(new URL('../server/migrations/'+file,import.meta.url),'utf8'));const bound=(sql,args=[])=>({bind:(...a)=>bound(sql,a),first:async()=>db.prepare(sql).get(...args)||null,all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:{changes:db.prepare(sql).run(...args).changes}})});const kv=new Map();const env={DB:{prepare:sql=>bound(sql)},TELEGRAM_BOT_TOKEN:'123456:fixture-token-value-not-real',OWNER_SESSION_SECRET:'fixture',DESARTLY_AUTH:{get:async(k,type)=>{const value=kv.get(k);return type==='json'&&value?JSON.parse(value):value??null;},put:async(k,v)=>kv.set(k,v),delete:async k=>kv.delete(k)},S3_ENDPOINT:'https://storage.example.test',S3_BUCKET:'private',S3_ACCESS_KEY:'fixture',S3_SECRET_KEY:'fixture',ASSETS:{fetch:async()=>new Response(new Uint8Array([1,2,3]),{headers:{'Content-Type':'image/webp'}})}};db.prepare('UPDATE telegram_settings SET owner_id=?,owner_name=?,notifications_since=?').run('123','Owner',Date.now()-1000);const project={id:'fixture',title:'Fixture Project',summary:'A real project summary.',heroImage:'/projects/fixture/cover.webp',blocks:[{type:'image',image:'/projects/fixture/one.webp'}],announcement:{fa:'کپشن واقعی پروژه',en:'Actual saved caption',hashtags:'#Design'}};db.prepare('INSERT INTO portfolio_state(id,revision,value) VALUES(1,0,?)').run(JSON.stringify({draft:{cmsVersion:2,projects:[project]},published:{cmsVersion:2,projects:[]},media:[]}));return {env,db,kv,project};}
const makeBooking=(db,{id='a'.repeat(32),start=Date.now()+3600000,status='confirmed',created=Date.now(),email='client@example.test'}={})=>{db.prepare('INSERT INTO calendar_bookings(id,calendar_id,start_at,end_at,status,expires_at,signature,brief,confirmation,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,'primary',start,start+1800000,status,0,'signature',JSON.stringify({name:'Client',email,meetingType:'mentorship',message:'Private briefing'}),JSON.stringify({meetingUrl:'https://meet.google.com/test-link'}),new Date(created).toISOString());return id;};
test('material versions follow render content and ignore private notes; images and bilingual captions keep CMS order',async()=>{const {project}=fixture();const version=await presentationVersion(project,'linkedin');assert.equal(version,await presentationVersion({...project,announcement:{...project.announcement,notes:'Internal only'},updatedAt:'later'},'linkedin'));assert.notEqual(version,await presentationVersion({...project,title:'Changed'},'linkedin'));assert.notEqual(version,await presentationVersion(project,'instagram'));assert.deepEqual(projectImages({...project,blocks:[...project.blocks,{type:'image',image:'/hidden.webp',hidden:true},{type:'grid',images:[project.heroImage,'/projects/fixture/two.webp']}]}),[project.heroImage,'/projects/fixture/one.webp','/projects/fixture/two.webp']);assert.equal(projectCaption(project,'en'),'Actual saved caption\n\n#Design');assert.equal(projectCaption({announcement:{}},'fa'),null);});
test('private render endpoint rejects missing and expired job credentials without reading drafts',async()=>{const {env}=fixture();env.DB.prepare=()=>{throw Error('Draft was accessed');};for(const path of ['/_presentation-render','/api/internal/presentation'])assert.equal((await presentationRenderResponse(new Request('https://site.test'+path),env)).status,403);});
test('ready PDF is stored outside public media and delivered as bytes, never as a public URL',async t=>{const {env,db,project}=fixture();const calls=[];let storedBytes;t.mock.method(globalThis,'fetch',async(url,options)=>{calls.push([String(url),options]);if(options.method==='PUT'){storedBytes=options.body;assert.notEqual(new TextDecoder().decode(storedBytes.slice(0,5)),'%PDF-');return new Response(null,{status:200});}if(String(url).startsWith('https://storage.example.test'))return new Response(storedBytes,{headers:{'Content-Type':'application/octet-stream'}});assert(options.body instanceof FormData);assert.equal(options.body.get('chat_id'),'123');assert.equal(await options.body.get('document').text(),'%PDF-fixture');return Response.json({ok:true,result:{message_id:8}});});await savePresentation(env,project,'linkedin',new TextEncoder().encode('%PDF-fixture'));await enqueueDelivery(env,'asset:test','asset',{projectId:'fixture',material:'linkedin'});await flushTelegramDeliveries(env);await flushTelegramDeliveries(env);assert.equal(db.prepare('SELECT status FROM telegram_deliveries').get().status,'sent');assert.equal(calls.filter(c=>c[0].includes('/sendDocument')).length,1);assert(calls[0][0].includes('/desartly/private/telegram/'));assert.equal(db.prepare('SELECT value FROM portfolio_state').get().value.includes('storage_key'),false);});
test('ambiguous Telegram delivery is held and never automatically resent',async t=>{const {env,db}=fixture();let sends=0;t.mock.method(globalThis,'fetch',async(url)=>{if(String(url).includes('sendDocument')){sends++;throw Error('Connection lost after acceptance');}return Response.json({ok:true,result:{message_id:1}});});await enqueueDelivery(env,'asset:lost','asset',{projectId:'fixture',material:'cover'});await flushTelegramDeliveries(env);await flushTelegramDeliveries(env);assert.equal(sends,1);assert.equal(db.prepare('SELECT status FROM telegram_deliveries').get().status,'uncertain');});
test('booking alerts and reminders are durable, exclude historical bookings and cancelled or moved versions',async t=>{const {env,db}=fixture();let sends=0;t.mock.method(globalThis,'fetch',async()=>{sends++;return Response.json({ok:true,result:{message_id:sends}});});const id=makeBooking(db);makeBooking(db,{id:'b'.repeat(32),created:Date.now()-86400000,start:Date.now()+5*3600000});await queueBookingNotifications(env);await queueBookingNotifications(env);assert.equal(db.prepare('SELECT count(*) AS n FROM telegram_deliveries').get().n,2);db.prepare('UPDATE calendar_bookings SET start_at=start_at+7200000 WHERE id=?').run(id);await flushTelegramDeliveries(env);assert.equal(sends,0);assert.equal(db.prepare("SELECT count(*) AS n FROM telegram_deliveries WHERE status='obsolete'").get().n,2);});
test('cancel preview cannot mutate Google and confirmation can only run once',async t=>{const {env,db,kv}=fixture();const id=makeBooking(db);env.GOOGLE_CLIENT_ID='test';env.GOOGLE_CLIENT_SECRET='test';const key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(env.OWNER_SESSION_SECRET)),{name:'AES-GCM'},false,['encrypt']);const iv=new Uint8Array(12),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify({refreshToken:'test',accessToken:'test',expires:Date.now()+3600000})));kv.set('google-calendar:connection',JSON.stringify({iv:Buffer.from(iv).toString('base64'),data:Buffer.from(data).toString('base64')}));let deletes=0;t.mock.method(globalThis,'fetch',async(url,options)=>{if(String(url).includes('googleapis.com')){assert.equal(options.method,'DELETE');deletes++;return new Response(null,{status:204});}return Response.json({ok:true,result:{message_id:1}});});await operationAction(env,'123','cancel:'+id,{owner_id:'123'});assert.equal(deletes,0);const preview=db.prepare('SELECT id FROM telegram_actions').get().id;await operationAction(env,'123','confirm:'+preview,{owner_id:'123'});assert.equal(deletes,1);assert.equal(db.prepare('SELECT status FROM calendar_bookings WHERE id=?').get(id).status,'cancelled');await assert.rejects(()=>operationAction(env,'123','confirm:'+preview,{}));assert.equal(deletes,1);});
test('changed appointment or schedule invalidates the old preview before an external mutation',async t=>{const {env,db}=fixture();let google=0;t.mock.method(globalThis,'fetch',async url=>{if(String(url).includes('googleapis.com'))google++;return Response.json({ok:true,result:{message_id:1}});});const id=makeBooking(db);await operationAction(env,'123','cancel:'+id,{});db.prepare('UPDATE calendar_bookings SET start_at=start_at+1000 WHERE id=?').run(id);await operationAction(env,'123','confirm:'+db.prepare('SELECT id FROM telegram_actions').get().id,{});assert.equal(google,0);assert.equal(db.prepare('SELECT status FROM telegram_actions').get().status,'needs-review');const old=await schedule(env);await updateSchedule(env,{...defaultSchedule,startHour:11});await assert.rejects(()=>updateSchedule(env,{...defaultSchedule,startHour:12},old));assert.equal((await schedule(env)).startHour,11);});
test('owner can request saved captions and hidden/unpaired or foreign users get no private content',async t=>{const {env,db}=fixture();const texts=[];t.mock.method(globalThis,'fetch',async(url,options)=>{texts.push(JSON.parse(options.body).text);return Response.json({ok:true,result:{message_id:1}});});const update=(user,text)=>({update_id:12,message:{from:{id:user},chat:{id:user,type:'private'},text}});await handleUpdate(update(999,'کپشن Fixture'),env,{owner_id:'123'});assert.equal(texts.length,0);await handleUpdate(update(123,'کپشن Fixture'),env,{owner_id:'123'});assert(texts[0].includes('کپشن واقعی'));assert(!texts.some(x=>x?.includes('انتشار در کانال')));await operationAction(env,'123','/note '+makeBooking(db)+' Keep this private',{});assert.equal(db.prepare('SELECT note FROM telegram_client_notes').get().note,'Keep this private');});

test('ordered original-file albums attach private bytes and partial failures cannot resend completed parts',async t=>{
 const {env,db,project}=fixture();project.blocks=Array.from({length:11},(_,i)=>({type:'image',image:`/projects/fixture/${i}.webp`}));db.prepare('UPDATE portfolio_state SET value=? WHERE id=1').run(JSON.stringify({draft:{cmsVersion:2,projects:[project]},media:[]}));let calls=0;
 t.mock.method(globalThis,'fetch',async(url,options)=>{if(String(url).includes('sendDocument')){calls++;const document=options.body.get('document');assert.equal(document.type,'application/zip');const files=unzipSync(new Uint8Array(await document.arrayBuffer()));assert.equal(Object.keys(files).length,calls===1?10:2);assert.deepEqual([...Object.values(files)[0]],[1,2,3]);if(calls===2)throw Error('Response lost');return Response.json({ok:true,result:{message_id:100}});}assert(!String(url).includes('sendMediaGroup'));return Response.json({ok:true,result:{message_id:100}});});
 for(const offset of [0,10])await enqueueDelivery(env,'album:'+offset,'asset',{projectId:'fixture',material:'originals',offset});await flushTelegramDeliveries(env);await flushTelegramDeliveries(env);assert.equal(calls,2);assert.deepEqual(db.prepare('SELECT status FROM telegram_deliveries ORDER BY rowid').all().map(r=>r.status),['sent','uncertain']);
});

test('uploaded project images resolve nested S3 variant references and cannot list the bucket',async t=>{const {env,db,project}=fixture();const id='uploaded';project.heroImage='/api/media/'+id;db.prepare('UPDATE portfolio_state SET value=? WHERE id=1').run(JSON.stringify({draft:{cmsVersion:2,projects:[project]},media:[{id,variants:[{width:1280,asset:{storage:'s3',key:'desartly/real-image-1280.webp'}},{width:2560,asset:{storage:'s3',key:'desartly/real-image-2560.webp'}},{width:640,asset:{storage:'s3',key:'desartly/real-image-640.webp'}}]}]}));const urls=[];t.mock.method(globalThis,'fetch',async url=>{urls.push(String(url));return new Response('image-bytes',{headers:{'Content-Type':'image/webp'}});});await projectImage(env,project,project.heroImage);await projectImage(env,project,project.heroImage,{original:true});assert(urls[0].endsWith('/desartly/real-image-1280.webp'));assert(urls[1].endsWith('/desartly/real-image-2560.webp'));await assert.rejects(()=>projectImage(env,project,'/api/media/not-in-project'));assert.equal(urls.length,2);});

test('client note prompts bind the next message to the selected owner record and validate session outcomes',async t=>{const {env,db}=fixture();const id=makeBooking(db);t.mock.method(globalThis,'fetch',async()=>Response.json({ok:true,result:{message_id:1}}));await operationAction(env,'123','input:note:'+id,{});await handleUpdate({update_id:21,message:{from:{id:123},chat:{id:123,type:'private'},text:'The client requested a brand proposal.'}},env,{owner_id:'123'});assert.equal(db.prepare('SELECT note FROM telegram_client_notes').get().note,'The client requested a brand proposal.');assert.equal(db.prepare("SELECT status FROM telegram_actions WHERE kind='input'").get().status,'done');await assert.rejects(()=>operationAction(env,'123','outcome:'+id+':attended',{}));db.prepare('UPDATE calendar_bookings SET end_at=? WHERE id=?').run(Date.now()-1000,id);await operationAction(env,'123','outcome:'+id+':attended',{});assert.equal(db.prepare('SELECT outcome FROM telegram_client_notes').get().outcome,'attended');});
test('follow-up reminders are delivered once for their current version and cancelled dates suppress queued messages',async t=>{const {env,db}=fixture();const id=makeBooking(db);db.prepare('INSERT INTO telegram_client_notes(booking_id,note,follow_up_at,updated_at) VALUES(?,?,?,?)').run(id,'Follow up about the proposal',Date.now()-1000,1);let followups=0;t.mock.method(globalThis,'fetch',async(url,options)=>{if(JSON.parse(options.body).text?.startsWith('👥'))followups++;return Response.json({ok:true,result:{message_id:1}});});await queueBookingNotifications(env);await flushTelegramDeliveries(env);await queueBookingNotifications(env);await flushTelegramDeliveries(env);assert.equal(followups,1);db.prepare('UPDATE telegram_client_notes SET updated_at=2').run();await queueBookingNotifications(env);db.prepare('UPDATE telegram_client_notes SET follow_up_at=NULL,updated_at=3').run();await flushTelegramDeliveries(env);assert.equal(followups,1);});
