import test from 'node:test';
import assert from 'node:assert/strict';
import {workerPageResponse} from '../server/worker-pages.js';
const shell='<html><head><title>Old</title></head><body><div id="root"></div></body></html>';
const state={publishedAt:'2026-10-09',published:{projects:[{id:'tesla-track-mode',title:'Tesla Track Mode',summary:'Live concept'},{id:'private',title:'Secret',hidden:true}],blogPosts:[],pages:{}}};
function fixture(){const assets=[];return {assets,env:{ASSETS:{fetch:async req=>{assets.push(new URL(req.url).pathname);return new Response(shell,{headers:{'Content-Type':'text/html'}});}}},store:{read:async()=>state}};}
test('Cloudflare serves public HTML from shell and D1 without Vercel, with matching metadata',async()=>{
 const {env,store,assets}=fixture();const r=await workerPageResponse(new Request('https://www.desartly.info/work/tesla-track-mode'),env,store);const html=await r.text();assert.equal(r.status,200);assert.deepEqual(assets,['/shell.html']);assert.match(html,/<h1>Tesla Track Mode<\/h1>/);assert.match(html,/rel="canonical" href="https:\/\/www.desartly.info\/work\/tesla-track-mode"/);assert.equal(r.headers.get('X-Desartly-Host'),'cloudflare');
});
test('missing and private projects remain 404 and do not expose content',async()=>{for(const path of ['/work/private','/missing']){const {env,store}=fixture();const r=await workerPageResponse(new Request('https://desartly.layebuzz.workers.dev'+path),env,store);assert.equal(r.status,404);assert.doesNotMatch(await r.text(),/Secret/);}});
test('Studio and booking choose the right shell and keep private pages uncacheable',async()=>{for(const [url,shellPath,robots] of [['https://studio.desartly.info/login','/studio-app/index.html','noindex, nofollow'],['https://book.desartly.info/','/shell.html','noindex, follow']]){const {env,store,assets}=fixture();const r=await workerPageResponse(new Request(url),env,store);assert.equal(r.status,200);assert.deepEqual(assets,[shellPath]);assert.match(r.headers.get('Cache-Control'),/no-store/);assert.equal(r.headers.get('X-Robots-Tag'),robots);}});
test('public private-path redirect preserves query and static files use ASSETS directly',async()=>{const {env,store,assets}=fixture();const r=await workerPageResponse(new Request('https://www.desartly.info/login?next=%2Fstudio'),env,store);assert.equal(r.status,302);assert.equal(r.headers.get('Location'),'https://studio.desartly.info/login?next=%2Fstudio');await workerPageResponse(new Request('https://www.desartly.info/assets/app.js'),env,store);assert.deepEqual(assets,['/assets/app.js']);});
test('sitemap uses shared published data, HEAD has no body, unavailable D1 fails clearly',async()=>{const {env,store}=fixture();let r=await workerPageResponse(new Request('https://www.desartly.info/sitemap.xml'),env,store);assert.match(await r.text(),/work\/tesla-track-mode/);r=await workerPageResponse(new Request('https://www.desartly.info/',{method:'HEAD'}),env,store);assert.equal(r.status,200);assert.equal(await r.text(),'');r=await workerPageResponse(new Request('https://www.desartly.info/'),env,{read:async()=>{throw Error('offline');}});assert.equal(r.status,503);});
test('page handler never retries a mutation',async()=>{const {env,store,assets}=fixture();const r=await workerPageResponse(new Request('https://www.desartly.info/contact',{method:'POST',body:'x'}),env,store);assert.equal(r.status,405);assert.deepEqual(assets,[]);});
