import {defaults} from '../src/cms/schema.js';
import {isVisibleProject} from '../src/cms/visibility.js';
import {encodeStoredStateAsync,decodeStoredStateAsync,stateStorageLimit} from './state-storage.js';
export function initialState(){return {revision:0,draft:defaults(),published:defaults(),history:[],media:[],inbox:[],events:{},updatedAt:null};}
export class D1Store{
 constructor(db){this.db=db;}
 async skillList(){const rows=await this.db.prepare('SELECT value FROM agent_skills').all();return rows.results.map(r=>JSON.parse(r.value));}
 async skillGet(id){const row=await this.db.prepare('SELECT value FROM agent_skills WHERE id=?').bind(id).first();return row?JSON.parse(row.value):null;}
 async skillWrite(skill,expected){const statement=expected===0?this.db.prepare('INSERT OR IGNORE INTO agent_skills(id,revision,value) VALUES(?,?,?)').bind(skill.id,skill.revision,JSON.stringify(skill)):this.db.prepare('UPDATE agent_skills SET revision=?,value=? WHERE id=? AND revision=?').bind(skill.revision,JSON.stringify(skill),skill.id,expected);const result=await statement.run();if(!result.meta.changes)throw Object.assign(Error('Skill changed. Refresh before uploading.'),{status:409});}
 async readAccess(){const row=await this.db.prepare("SELECT json_extract(value,'$.agentKeys') AS keys FROM portfolio_state WHERE id=1").first();return {agentKeys:JSON.parse(row?.keys||'[]')};}
 async storageUsage(){const row=await this.db.prepare('SELECT length(CAST(value AS BLOB)) AS bytes FROM portfolio_state WHERE id=1').first();return row?.bytes||0;}
 async read(){const row=await this.db.prepare('SELECT value FROM portfolio_state WHERE id = 1').first();return row?await decodeStoredStateAsync(row.value):initialState();}
 async write(state,expected){const next={...state,revision:expected+1,updatedAt:new Date().toISOString()},stored=next.historyStorageVersion===1?await encodeStoredStateAsync(next):JSON.stringify(next);if(new TextEncoder().encode(stored).length>stateStorageLimit)throw Object.assign(Error(next.historyStorageVersion===1?'Active CMS content exceeds its storage limit after lossless history compression. Keep large assets in the media library.':'CMS content metadata exceeds its storage limit. Image optimization is separate; lossless history storage must be enabled by the site administrator.'),{status:413});await this.db.prepare('INSERT OR IGNORE INTO portfolio_state(id,revision,value) VALUES(1,0,?)').bind(JSON.stringify(initialState())).run();const result=await this.db.prepare('UPDATE portfolio_state SET revision=?, value=? WHERE id=1 AND revision=?').bind(next.revision,stored,expected).run();if(!result.meta.changes)throw Object.assign(Error('Content changed in another session. Reload before saving.'),{status:409});return next;}
 async readMarketing(){const row=await this.db.prepare("SELECT revision,json_extract(value,'$.marketing') AS marketing FROM portfolio_state WHERE id=1").first();return {revision:row?.revision||0,marketing:JSON.parse(row?.marketing||'{"programs":[],"tasks":[]}')};}
 async writeMarketing(marketing,expected){const value=JSON.stringify(marketing);if(new TextEncoder().encode(value).length>220000)throw Object.assign(Error('Marketing records reached their storage budget.'),{status:413});const result=await this.db.prepare("UPDATE portfolio_state SET revision=?,value=json_set(value,'$.marketing',json(?),'$.revision',?,'$.updatedAt',?) WHERE id=1 AND revision=? AND length(CAST(json_set(value,'$.marketing',json(?)) AS BLOB))<=1800000").bind(expected+1,value,expected+1,new Date().toISOString(),expected,value).run();if(!result.meta.changes)throw Object.assign(Error('Marketing changed. Retry with fresh records.'),{status:409});}
 async readMedia(){
  const row=await this.db.prepare("SELECT revision, json_extract(value,'$.media') AS media, json_extract(value,'$.customMediaFolders') AS folders, json_extract(value,'$.mediaFolderLocations') AS locations, json_extract(value,'$.mediaActivity') AS activity, json_extract(value,'$.mediaUndo') AS undo, json_extract(value,'$.mediaFolderColors') AS colors, json_extract(value,'$.mediaFolderMetadata') AS metadata, json_extract(value,'$.trashedMediaFolders') AS trash FROM portfolio_state WHERE id=1").first();
  if(!row)return {revision:0,media:[],customMediaFolders:[],mediaFolderLocations:{}};
  const state={revision:row.revision,media:JSON.parse(row.media||'[]'),customMediaFolders:JSON.parse(row.folders||'[]'),mediaFolderLocations:JSON.parse(row.locations||'{}'),mediaActivity:JSON.parse(row.activity||'[]'),mediaUndo:JSON.parse(row.undo||'[]'),mediaFolderColors:JSON.parse(row.colors||'{}'),mediaFolderMetadata:JSON.parse(row.metadata||'{}'),trashedMediaFolders:JSON.parse(row.trash||'[]')};
  const roots=await this.db.prepare("SELECT 'Projects/'||json_extract(p.value,'$.id') AS folder FROM portfolio_state s,json_each(s.value,'$.draft.projects') p UNION SELECT 'Projects/'||json_extract(p.value,'$.id') FROM portfolio_state s,json_each(s.value,'$.published.projects') p UNION SELECT 'Journal/'||json_extract(p.value,'$.id') FROM portfolio_state s,json_each(s.value,'$.draft.blogPosts') p UNION SELECT 'Journal/'||json_extract(p.value,'$.id') FROM portfolio_state s,json_each(s.value,'$.published.blogPosts') p").all();
  const summaries=await this.db.prepare("SELECT 'Projects/'||json_extract(p.value,'$.id') AS folder, json_extract(p.value,'$.id') AS id, json_extract(p.value,'$.hidden') AS hidden, json_extract(p.value,'$.archived') AS archived, json_extract(p.value,'$.managed') AS managed FROM portfolio_state s,json_each(s.value,'$.draft.projects') p UNION SELECT 'Projects/'||json_extract(p.value,'$.id'),json_extract(p.value,'$.id'),json_extract(p.value,'$.hidden'),json_extract(p.value,'$.archived'),json_extract(p.value,'$.managed') FROM portfolio_state s,json_each(s.value,'$.published.projects') p UNION SELECT 'Journal/'||json_extract(p.value,'$.id'),json_extract(p.value,'$.id'),0,json_extract(p.value,'$.archived'),0 FROM portfolio_state s,json_each(s.value,'$.draft.blogPosts') p UNION SELECT 'Journal/'||json_extract(p.value,'$.id'),json_extract(p.value,'$.id'),0,json_extract(p.value,'$.archived'),0 FROM portfolio_state s,json_each(s.value,'$.published.blogPosts') p").all();
  state._registeredCustomMediaFolders=[...state.customMediaFolders];
  const allowed=new Set(summaries.results.filter(r=>r.folder.startsWith('Journal/')?!r.archived:isVisibleProject({...r,managed:Boolean(r.managed)})||(!r.archived&&r.managed)).map(r=>r.folder));
  state.customMediaFolders=[...new Set([...state.customMediaFolders,...roots.results.filter(r=>allowed.has(r.folder)).map(r=>state.mediaFolderLocations[r.folder]||r.folder)])].filter(path=>!state.trashedMediaFolders.some(r=>path===r.path||path.startsWith(r.path+'/')));return state;
 }
 async writeMedia(state,expected){
  const updatedAt=new Date().toISOString();
  const fields={media:[],customMediaFolders:[],mediaFolderLocations:{},mediaActivity:[],mediaUndo:[],mediaFolderColors:{},mediaFolderMetadata:{},trashedMediaFolders:[]};
  const setters=Object.keys(fields).map(key=>`'$.${key}',json(?)`).join(',');
  const values=Object.entries(fields).map(([key,fallback])=>JSON.stringify(state[key]??fallback));
  const result=await this.db.prepare(`WITH next AS (SELECT json_set(value,${setters},'$.revision',?,'$.updatedAt',?) AS value FROM portfolio_state WHERE id=1 AND revision=?) UPDATE portfolio_state SET revision=?,value=(SELECT value FROM next) WHERE id=1 AND revision=? AND length(CAST((SELECT value FROM next) AS BLOB))<=1800000`).bind(...values,expected+1,updatedAt,expected,expected+1,expected).run();
  if(!result.meta.changes){
   // One-time migration for a legacy oversized row whose codec was enabled but
   // whose historical snapshots have not yet been physically compressed.
   if(await this.storageUsage()>stateStorageLimit){const full=await this.read();if(full.revision===expected&&full.historyStorageVersion===1)return this.write({...full,...Object.fromEntries(Object.keys(fields).map(key=>[key,state[key]??fields[key]]))},expected);}
   throw Object.assign(Error('Media changed or the library exceeded its storage budget. Reload before retrying.'),{status:409});
  }return {...state,revision:expected+1,updatedAt};
 }

}
