import {validateMarketingSchedule} from './marketing-schedule.js';
import {marketingTemplates,programTemplates,marketingStages,marketingWeek} from '../src/cms/marketing-catalog.js';
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status});};
const text=(value,max=400)=>{if(typeof value!=='string'||value.length>max)fail('Use text within the field limit.');return value.trim();};
const date=value=>{if(!value)return '';if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value+'T12:00:00Z'))||new Date(value+'T12:00:00Z').toISOString().slice(0,10)!==value)fail('Use a valid calendar date.');return value;};
export function marketingAction(state,body,now=new Date()){
 if(body.revision!==state.revision)fail('Marketing changed in another session. Refresh before saving.',409);const next=structuredClone(state),m=next.marketing||{programs:[],tasks:[]};next.marketing=m;m.programs||=[];m.tasks||=[];const program=m.programs.find(p=>p.id===body.programId),task=m.tasks.find(t=>t.id===body.taskId),stamp=now.toISOString();
 const createTask=(p,values,id=crypto.randomUUID())=>{if(m.tasks.length>=500)fail('This workspace supports 500 task records. Export records before reorganizing your workspace.');if(values.status!==undefined&&!['todo','doing'].includes(values.status))fail('Choose an initial task status.');const template=values.templateId?marketingTemplates.find(t=>t.id===values.templateId):null;if(values.templateId&&!template)fail('Choose an existing task template.');const title=text(values.title||template?.title||'',180);if(!title)fail('Give the task a concrete title.');const stage=values.stage||template?.stage||'acquisition';if(!marketingStages.some(([id])=>id===stage))fail('Choose a supported funnel stage.');m.tasks.push({id,programId:p.id,templateId:template?.id||'',channel:template?.channel||'custom',stage,title,brief:text(values.brief??template?.brief??'',600),due:date(values.due),done:false,status:values.status==='doing'?'doing':'todo',startedAt:values.status==='doing'?stamp:null,createdAt:stamp});};
 if(body.action==='save-schedule'){m.schedule=validateMarketingSchedule(body.schedule,m,now);}
 else if(body.action==='create-program'){if(m.programs.length>=30)fail('Keep at most 30 programs in this workspace.');const template=body.templateId?programTemplates.find(t=>t.id===body.templateId):null;if(body.templateId&&!template)fail('Choose a program template.');const title=text(body.title||template?.title||'',180);if(!title)fail('Name this marketing program.');const selected=body.templates??template?.templates??[];if(!Array.isArray(selected)||selected.length>30||selected.some(id=>!marketingTemplates.some(t=>t.id===id)))fail('Choose up to 30 supported task templates.');const p={id:crypto.randomUUID(),title,goal:text(body.goal||template?.goal||'',600),market:text(body.market||'',180),ongoing:body.ongoing!==false,start:date(body.start)||stamp.slice(0,10),end:body.ongoing===false?date(body.end):'',templates:[...new Set(selected)],createdAt:stamp,archived:false};if(!p.ongoing&&(!p.end||p.end<p.start))fail('Set an end date on or after the start.');m.programs.push(p);}
 else if(body.action==='update-program'){if(!program)fail('Program not found.',404);if(body.title!==undefined){program.title=text(body.title,180);if(!program.title)fail('Name this program.');}if(body.goal!==undefined)program.goal=text(body.goal,600);if(body.market!==undefined)program.market=text(body.market,180);if(body.ongoing!==undefined){if(typeof body.ongoing!=='boolean')fail('Use a valid program duration.');program.ongoing=body.ongoing;}if(body.start!==undefined)program.start=date(body.start);if(body.end!==undefined)program.end=program.ongoing?'':date(body.end);if(!program.ongoing&&(!program.end||program.end<program.start))fail('Set a valid program end date.');if(body.templates!==undefined){if(!Array.isArray(body.templates)||body.templates.length>30||body.templates.some(id=>!marketingTemplates.some(t=>t.id===id)))fail('Choose valid task templates.');program.templates=[...new Set(body.templates)];}if(body.archived!==undefined){if(typeof body.archived!=='boolean')fail('Use a valid archive preference.');program.archived=body.archived;}}
 else if(body.action==='add-task'){if(!program||program.archived)fail('Choose an active program.');createTask(program,body);}
 else if(body.action==='add-week'){if(!program||program.archived)fail('Choose an active program.');const week=marketingWeek(now);for(const id of program.templates){const key=program.id+':'+id+':'+week;if(!m.tasks.some(t=>t.id===key))createTask(program,{templateId:id,due:date(body.due)},key);}}
 else if(body.action==='update-task'){if(!task)fail('Task not found.',404);if(body.title!==undefined){task.title=text(body.title,180);if(!task.title)fail('Name the task.');}if(body.brief!==undefined)task.brief=text(body.brief,600);if(body.due!==undefined)task.due=date(body.due);if(body.status!==undefined){if(!['todo','doing','done'].includes(body.status))fail('Choose a valid task status.');task.status=body.status;task.done=body.status==='done';if(body.status==='doing')task.startedAt||=stamp;if(task.done){task.completedAt=stamp;task.creditWeek||=marketingWeek(now);}else task.completedAt=null;}if(body.done!==undefined){if(typeof body.done!=='boolean')fail('Use a valid completion status.');task.done=body.done;task.status=body.done?'done':'todo';if(task.done){task.completedAt=stamp;task.creditWeek||=marketingWeek(now);}else task.completedAt=null;}if(body.note!==undefined)task.note=text(body.note,600);if(body.evidence!==undefined){task.evidence=text(body.evidence,500);if(task.evidence){let url;try{url=new URL(task.evidence);}catch{fail('Use a valid evidence URL.');}if(!['https:','http:'].includes(url.protocol)||url.username||url.password)fail('Use a credential-free HTTP or HTTPS link.');}}if(body.outcome!==undefined){if(!body.outcome||typeof body.outcome!=='object'||Array.isArray(body.outcome))fail('Use valid task results.');task.outcome={};for(const key of ['leads','meetings','proposals','wins']){const v=body.outcome[key]??0;if(!Number.isSafeInteger(v)||v<0||v>100000)fail('Use nonnegative whole numbers for results.');task.outcome[key]=v;}}if(body.archived!==undefined){if(typeof body.archived!=='boolean')fail('Use a valid archive preference.');task.archived=body.archived;}}
 else fail('Choose a supported marketing action.');
 if(new TextEncoder().encode(JSON.stringify(m)).length>220000)fail('Marketing records reached their storage budget. Export and simplify older records.',413);return next;
}
