import {Unzip,UnzipInflate} from 'fflate';
import {bounded} from './content-api.js';
import {isOwner} from './owner-auth.js';
export const skillIds=['desartly-case-study','desartly-article','desartly-skill-bundle'];
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status});};
export function inspectSkill(bytes,id){
 if(!skillIds.includes(id))fail('Choose a supported writing skill.');const bundle=id==='desartly-skill-bundle';let count=0,total=0,skill='',found=false;
 const unzip=new Unzip(file=>{if(++count>(bundle?12000:64)||file.originalSize>(bundle?20000000:1000000))fail('Skill archive is too large.');const path=file.name;if(!path.startsWith(id+'/')||path.includes('\\')||path.split('/').some(p=>p==='..'||p==='.')||path.includes('\0'))fail('Archive paths must stay inside the skill folder.');if(path.endsWith('/'))return;if(!bundle&&!/\.(md|ya?ml|mjs|js|py|json|txt)$/.test(path))fail('Unsupported skill resource.');if(bundle&&path!==id+'/SKILL.md'){total+=file.originalSize||0;if(total>200000000)fail('Expanded bundle exceeds its size limit.');return;}let chunks=[],size=0;file.ondata=(error,data,final)=>{if(error)throw error;size+=data.length;total+=data.length;if(size>1000000||total>(bundle?200000000:2000000))fail('Expanded skill exceeds its size limit.');if(path===id+'/SKILL.md')chunks.push(data);if(final&&path===id+'/SKILL.md'){found=true;const all=new Uint8Array(size);let offset=0;for(const part of chunks){all.set(part,offset);offset+=part.length;}skill=new TextDecoder('utf-8',{fatal:true}).decode(all);}};file.start();});unzip.register(UnzipInflate);unzip.push(bytes,true);
 if(!found||!skill.startsWith('---\n'))fail('A complete SKILL.md with frontmatter is required.');const front=skill.split('\n---')[0];const name=front.match(/^name:\s*(.+)$/m)?.[1]?.trim(),version=front.match(/^\s+version:\s*["']?([0-9]+\.[0-9]+\.[0-9]+)["']?\s*$/m)?.[1];if(name!==id||!version||!/^description:\s*\S/m.test(front))fail('Skill name, description and semantic version are required.');return {id,version,files:count,expandedBytes:total};
}
export async function skillResponse(request,env,store,media){const url=new URL(request.url);if(!url.pathname.startsWith('/api/skills'))return null;const json=(body,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
 try{const parts=url.pathname.split('/').filter(Boolean);if(parts.length===2&&request.method==='GET'){const records=await store.skillList();return json({skills:skillIds.map(id=>{const r=records.find(s=>s.id===id);return r?{...r,asset:undefined,versions:(r.versions||[]).map(({asset,...v})=>v),download:'/api/skills/'+id+'/download'}:{id,version:null,revision:0,download:'/downloads/'+id+'.zip',bundled:true};})});}
 const id=parts[2];if(!skillIds.includes(id))fail('Unknown skill.',404);const current=await store.skillGet(id);
 if(parts[3]==='download'&&request.method==='GET'){if(id==='desartly-skill-bundle'&&!(await isOwner(request,env)))fail('Owner sign-in required to download the personal skill bundle.',403);if(!current)return env.ASSETS?env.ASSETS.fetch(new Request(url.origin+'/downloads/'+id+'.zip')):json({error:'Upload the first skill version in AI assistant.'},404);const revision=url.searchParams.get('revision'),record=revision?([current,...(current.versions||[])].find(v=>String(v.revision)===revision)):current;if(!record)fail('Skill version not found.',404);const response=await media.get(record.asset);return new Response(response.body,{headers:{'Content-Type':'application/zip','Content-Disposition':'attachment; filename="'+id+'-'+record.version+'.zip"','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','ETag':'"'+record.sha256+'"'}});}
 if(request.method!=='POST'||parts.length!==3)fail('Not found.',404);if(!(await isOwner(request,env)))fail('Owner sign-in required to update skills.',403);if(request.headers.get('Origin')!==url.origin)fail('Request origin rejected.',403);const expected=Number(request.headers.get('X-Skill-Revision'));if(!Number.isSafeInteger(expected)||expected!==(current?.revision||0))fail('Skill changed. Refresh before uploading.',409);
 const bytes=await bounded(request,id==='desartly-skill-bundle'?64000000:2000000),info=inspectSkill(bytes,id);const sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');if(current?.sha256===sha256)return json({skill:current,unchanged:true});if(current&&[current,...(current.versions||[])].some(v=>v.version===info.version))fail('Use a new version number for changed skill content.',409);
 const asset=await media.put('skills/'+id+'/'+sha256+'.zip',bytes,'application/zip');const next={...info,revision:expected+1,sha256,bytes:bytes.length,asset,updatedAt:new Date().toISOString(),versions:current?[{...current,versions:undefined},...(current.versions||[])].slice(0,5):[]};await store.skillWrite(next,expected);return json({skill:{...next,asset:undefined}});
 }catch(error){return json({error:error.message},error.status||400);}}
