import {isOwner} from './owner-auth.js';
import {D1Store} from './content-store.js';
import {materialize} from '../src/cms/materialize.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
const enc=new TextEncoder();
async function key(env){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(env.OWNER_SESSION_SECRET)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
async function token(env){if(env.TELEGRAM_BOT_TOKEN)return env.TELEGRAM_BOT_TOKEN;const value=await env.DESARTLY_AUTH.get('telegram:token');if(!value)return null;const bytes=Uint8Array.from(atob(value),c=>c.charCodeAt(0));return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes.slice(0,12)},await key(env),bytes.slice(12)));}
async function putToken(env,value){const iv=crypto.getRandomValues(new Uint8Array(12)),body=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(env),enc.encode(value))),bytes=new Uint8Array(iv.length+body.length);bytes.set(iv);bytes.set(body,12);await env.DESARTLY_AUTH.put('telegram:token',btoa(String.fromCharCode(...bytes)));}
export async function telegramCall(env,method,body){const secret=await token(env);if(!secret)throw Error('Connect your Telegram bot first.');let response;try{response=await fetch(`https://api.telegram.org/bot${secret}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});}catch{throw Error('Telegram did not confirm the request. Check connection before retrying.');}const data=await response.json();if(!response.ok||!data.ok)throw Error('Telegram rejected the request. Check bot access and connection.');return data.result;}
const menu={inline_keyboard:[[{text:'🗂 پروژه‌ها',callback_data:'projects:0'},{text:'⚙️ تنظیمات',callback_data:'settings'}],[{text:'بازکردن Studio',url:'https://studio.desartly.info/studio/telegram'}]]};
async function handleUpdate(update,env,settings){const callback=update.callback_query,message=callback?.message||update.message,user=callback?.from||message?.from;if(!user||message?.chat?.type!=='private')return;const text=String(message.text||'');
 if(!settings.owner_id&&text.startsWith('/start ')){const code=text.slice(7).trim();if(code&&code===settings.pair_code&&settings.pair_expires>Date.now()){await env.DB.prepare('UPDATE telegram_settings SET candidate_id=?,candidate_name=? WHERE id=1 AND owner_id IS NULL AND pair_code=? AND pair_expires>? AND candidate_id IS NULL').bind(String(user.id),String(user.username||user.first_name||'').slice(0,100),code,Date.now()).run();await telegramCall(env,'sendMessage',{chat_id:user.id,text:'درخواست اتصال ثبت شد. در Studio شناسه و نام حساب را بررسی و تأیید کن.'});}return;}
 if(String(user.id)!==settings.owner_id||String(message.chat.id)!==settings.owner_id)return;
 if(callback)await telegramCall(env,'answerCallbackQuery',{callback_query_id:callback.id});
 const action=callback?.data||text;
 if(action.startsWith('projects:')||action==='/projects'){const page=Math.max(0,Math.min(100,Number(action.split(':')[1])||0)),state=await new D1Store(env.DB).read(),projects=materialize(structuredClone(state.draft)).projects.filter(p=>!p.archived),items=projects.slice(page*8,page*8+8);await telegramCall(env,'sendMessage',{chat_id:user.id,text:items.length?'پروژه‌های Studio — صفحهٔ '+(page+1):'پروژه‌ای در این صفحه نیست.',reply_markup:{inline_keyboard:[...items.map(p=>[{text:p.title.slice(0,70),callback_data:'project:'+p.id}]),...(projects.length>(page+1)*8?[[{text:'صفحهٔ بعد',callback_data:'projects:'+(page+1)}]]:[]),...(page?[[{text:'صفحهٔ قبل',callback_data:'projects:'+(page-1)}]]:[])]}});}
 else if(action.startsWith('project:')){const state=await new D1Store(env.DB).read(),p=materialize(structuredClone(state.draft)).projects.find(p=>p.id===action.slice(8)&&!p.archived);if(p)await telegramCall(env,'sendMessage',{chat_id:user.id,text:(p.title+'\n\n'+String(p.summary||'').replace(/<[^>]*>/g,'').slice(0,2200)+'\n\nوضعیت: '+p.status+'\nخروجی PDF: دریافت فایل در فاز بعد فعال می‌شود.').slice(0,3800),reply_markup:{inline_keyboard:[[{text:'بازکردن پروژه در CMS',url:'https://studio.desartly.info/studio/projects/'+encodeURIComponent(p.id)}],[{text:'بازگشت به پروژه‌ها',callback_data:'projects:0'}]]}});}
 else await telegramCall(env,'sendMessage',{chat_id:user.id,text:action==='settings'?'ربات به حساب مالک متصل است. رزرو سایت خودکار و تأییدشده باقی می‌ماند. انتشار کانال هنوز فعال نیست.':'Desartly Studio\nمدیریت خصوصی پروژه‌ها. جلسه‌ها، دریافت فایل و انتشار تأییدشده در مراحل بعد اضافه می‌شوند.',reply_markup:menu});
}
export async function telegramResponse(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/api/studio/telegram')&&url.pathname!=='/api/telegram/webhook')return null;if(!env.DB||!env.DESARTLY_AUTH||!env.OWNER_SESSION_SECRET)return json({error:'Telegram storage is unavailable.'},503);
 if(url.pathname==='/api/telegram/webhook'){if(request.method!=='POST')return json({error:'Method not allowed.'},405);const secret=await env.DESARTLY_AUTH.get('telegram:webhook');if(!secret||request.headers.get('X-Telegram-Bot-Api-Secret-Token')!==secret)return json({error:'Invalid webhook.'},403);const raw=await request.text();if(raw.length>64000)return json({error:'Update too large.'},413);let update;try{update=JSON.parse(raw);}catch{return json({error:'Invalid update.'},400);}if(!Number.isSafeInteger(update.update_id))return json({error:'Invalid update.'},400);const claim=await env.DB.prepare("INSERT OR IGNORE INTO telegram_updates(update_id,status,created_at) VALUES(?,'processing',?)").bind(update.update_id,Date.now()).run();if(!claim.meta?.changes)return json({ok:true});try{const settings=await env.DB.prepare('SELECT * FROM telegram_settings WHERE id=1').first();await handleUpdate(update,env,settings);await env.DB.prepare("UPDATE telegram_updates SET status='done' WHERE update_id=?").bind(update.update_id).run();}catch{await env.DB.prepare("UPDATE telegram_updates SET status='uncertain' WHERE update_id=?").bind(update.update_id).run();}return json({ok:true});}
 if(!await isOwner(request,env))return json({error:'Owner sign-in required.'},401);if(!['GET','POST'].includes(request.method))return json({error:'Method not allowed.'},405);if(request.method==='POST'&&request.headers.get('Origin')!==url.origin)return json({error:'Request origin rejected.'},403);
 try{const settings=await env.DB.prepare('SELECT * FROM telegram_settings WHERE id=1').first();if(request.method==='GET'){const events=await env.DB.prepare('SELECT update_id,status,created_at FROM telegram_updates ORDER BY created_at DESC LIMIT 20').all();return json({configured:!!await token(env),botName:settings.bot_name,ownerId:settings.owner_id,ownerName:settings.owner_name,candidateId:settings.candidate_id,candidateName:settings.candidate_name,events:events.results||[]});}const raw=await request.text();if(raw.length>6000)return json({error:'Request too large.'},413);const body=JSON.parse(raw);
 if(body.action==='connect'){if(typeof body.token!=='string'||!/^\d{5,15}:[A-Za-z0-9_-]{20,100}$/.test(body.token))throw Error('Enter the BotFather token in this private form.');if(settings.owner_id)throw Error('A bot is already paired. Keep its existing connection.');const temp={...env,TELEGRAM_BOT_TOKEN:body.token},bot=await telegramCall(temp,'getMe',{});const secret=crypto.randomUUID().replaceAll('-','');await env.DESARTLY_AUTH.put('telegram:webhook',secret);await putToken(env,body.token);await telegramCall(temp,'setWebhook',{url:'https://desartly.layebuzz.workers.dev/api/telegram/webhook',secret_token:secret,max_connections:1,allowed_updates:['message','callback_query']});await env.DB.prepare('UPDATE telegram_settings SET bot_name=?,updated_at=? WHERE id=1').bind(bot.username,Date.now()).run();return json({ok:true,botName:bot.username});}
 if(body.action==='pair'){if(settings.owner_id)throw Error('The owner is already connected.');if(!settings.bot_name)throw Error('Connect the bot first.');const code=crypto.randomUUID().replaceAll('-','');await env.DB.prepare('UPDATE telegram_settings SET pair_code=?,pair_expires=?,candidate_id=NULL,candidate_name=NULL WHERE id=1 AND owner_id IS NULL').bind(code,Date.now()+600000).run();return json({url:'https://t.me/'+settings.bot_name+'?start='+code});}
 if(body.action==='approve'){if(!settings.candidate_id||body.candidateId!==settings.candidate_id||settings.pair_expires<Date.now())throw Error('The connection request expired. Start again.');const claim=await env.DB.prepare('UPDATE telegram_settings SET owner_id=candidate_id,owner_name=candidate_name,candidate_id=NULL,candidate_name=NULL,pair_code=NULL,pair_expires=NULL WHERE id=1 AND owner_id IS NULL AND candidate_id=?').bind(body.candidateId).run();if(!claim.meta?.changes)throw Error('Owner connection changed. Refresh.');return json({ok:true});}
 return json({error:'Unknown action.'},400);
 }catch(error){return json({error:error.message||'Telegram connection failed.'},400);}
}
