export function photoCanvasSize(width,height){if(!Number.isFinite(width)||!Number.isFinite(height)||width<1||height<1)throw Error('Invalid image dimensions.');const ratio=Math.max(width,height)/Math.min(width,height),baseW=ratio>20&&height>width?height/20:width,baseH=ratio>20&&width>height?width/20:height,scale=Math.min(1,4096/Math.max(baseW,baseH),9998/(baseW+baseH));return {width:Math.max(1,Math.ceil(baseW*scale)),height:Math.max(1,Math.ceil(baseH*scale)),imageWidth:Math.max(1,Math.floor(width*scale)),imageHeight:Math.max(1,Math.floor(height*scale))};}
export async function withPhotoEncoder(env,run){
 if(!env.PRESENTATION_BROWSER)throw Error('سرویس آماده‌سازی آلبوم عکس در دسترس نیست. فایل‌های اصلی را می‌توانی جدا دریافت کنی.');
 const {default:puppeteer}=await import('@cloudflare/puppeteer');let browser;
 try{browser=await puppeteer.launch(env.PRESENTATION_BROWSER);const page=await browser.newPage();return await run(async(bytes,mime)=>{
  let base64='';for(let i=0;i<bytes.length;i+=32768)base64+=String.fromCharCode(...bytes.subarray(i,i+32768));base64=btoa(base64);
  const dimensions=await page.evaluate(async({base64,mime})=>{const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),bitmap=await createImageBitmap(new Blob([bytes],{type:mime}));const size={width:bitmap.width,height:bitmap.height};bitmap.close();return size;},{base64,mime});const size=photoCanvasSize(dimensions.width,dimensions.height);
  const data=await page.evaluate(async({base64,mime,size})=>{const bitmap=await createImageBitmap(new Blob([Uint8Array.from(atob(base64),c=>c.charCodeAt(0))],{type:mime})),canvas=document.createElement('canvas');canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,(canvas.width-size.imageWidth)/2,(canvas.height-size.imageHeight)/2,size.imageWidth,size.imageHeight);bitmap.close();let quality=.96,data=canvas.toDataURL('image/jpeg',quality);while(data.length>12*1024*1024&&quality>.5){quality-=.08;data=canvas.toDataURL('image/jpeg',quality);}return data.split(',')[1];},{base64,mime,size});const output=Uint8Array.from(atob(data),c=>c.charCodeAt(0));if(output.length>10*1024*1024)throw Error('نسخه عکس از محدودیت آلبوم بزرگ‌تر است؛ فایل اصلی را دریافت کن.');return output;
 });}catch(error){if(/429|rate limit|acquisition/i.test(error.message||''))throw Object.assign(Error('آلبوم در صف محدودیت سرویس قرار گرفت.'),{rejected:true,retryAfter:60});throw error;}finally{if(browser)await browser.close().catch(()=>{});}
}
