import {isOwner} from './owner-auth.js';
import {D1Store} from './content-store.js';
import {materialize} from '../src/cms/materialize.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
import {token,putToken,telegramCall} from './telegram-client.js';
export {telegramCall} from './telegram-client.js';
import {assistantMenu,operationAction} from './telegram-operations.js';
import {projectImages,projectCaption,presentationVersion} from '../src/cms/telegram-materials.js';
import {telegramProject} from './telegram-material-service.js';
import {enqueueDelivery,flushTelegramDeliveries} from './telegram-delivery.js';
const reply=(env,owner,text,rows=[])=>telegramCall(env,'sendMessage',{chat_id:owner,text:String(text).slice(0,4000),...(rows.length?{reply_markup:{inline_keyboard:rows}}:{})});
const normalize=value=>String(value).normalize('NFKC').replaceAll('ي','ی').replaceAll('ك','ک').toLowerCase().trim();
async function projectCard(env,owner,p){
 const rows=await env.DB.prepare('SELECT format,version FROM telegram_exports WHERE project_id=?').bind(p.id).all();const labels=[];for(const row of rows.results)labels.push((row.format==='instagram'?'عمودی':'افقی')+': '+(row.version===await presentationVersion(p,row.format)?'آماده':'نیازمند بازتولید'));
 const action=material=>'asset:'+material+':'+p.id;
 await reply(env,owner,p.title+'\n\n'+String(p.summary||'').replace(/<[^>]*>/g,'').slice(0,1500)+'\n\nوضعیت: '+(p.status==='published'?'منتشرشده':'پیش‌نویس')+'\nخدمات: '+String(p.deliverables||p.discipline||'در CMS ثبت نشده').slice(0,350)+'\nخروجی PDF: '+(labels.join('، ')||'در اولین درخواست تولید می‌شود.')+'\nدریافت فقط در همین گفت‌وگوی خصوصی انجام می‌شود.',[
 [{text:'پرزنتیشن افقی',callback_data:action('linkedin')},{text:'پرزنتیشن عمودی',callback_data:action('instagram')}],
 [{text:'هر دو PDF',callback_data:action('both')},{text:'آلبوم تصاویر',callback_data:action('album')}],
 [{text:'کاور اصلی',callback_data:action('cover')},{text:'کپشن فارسی',callback_data:action('fa')},{text:'English caption',callback_data:action('en')}],
 ...rows.results.length?[[{text:'دریافت PDF قدیمی با برچسب',callback_data:action('old')}]]:[],
 ...(p.status==='published'?[[{text:'پروژه در سایت',url:'https://www.desartly.info/work/'+encodeURIComponent(p.id)}]]:[]),
 [{text:'پروژه در CMS',url:'https://studio.desartly.info/studio/projects/'+encodeURIComponent(p.id)},{text:'پروژه‌ها',callback_data:'projects:0'}]
 ]);
}
async function requestMaterial(env,owner,project,material,updateId){
 if(['fa','en'].includes(material)){const caption=projectCaption(project,material);if(!caption){await reply(env,owner,'کپشن '+(material==='fa'?'فارسی':'انگلیسی')+' این پروژه هنوز در CMS نوشته نشده است.');return;}for(let i=0;i<caption.length;i+=3800)await reply(env,owner,caption.slice(i,i+3800));return;}
 if(material==='old'){await reply(env,owner,'این گزینه نسخهٔ ذخیره‌شده را حتی اگر قدیمی باشد، با برچسب نیازمند بازتولید می‌فرستد.',[[{text:'نسخهٔ ذخیره‌شدهٔ افقی',callback_data:'asset:old-linkedin:'+project.id},{text:'نسخهٔ ذخیره‌شدهٔ عمودی',callback_data:'asset:old-instagram:'+project.id}]]);return;}
 const allowed=['linkedin','instagram','both','album','cover','old-linkedin','old-instagram'];if(!allowed.includes(material))throw Error('نوع فایل معتبر انتخاب کن.');
 const kinds=material==='both'?['linkedin','instagram']:[material];let count=0;
 for(const requested of kinds){const old=requested.startsWith('old-'),kind=requested.replace('old-','');if(old&&!await env.DB.prepare('SELECT project_id FROM telegram_exports WHERE project_id=? AND format=?').bind(project.id,kind).first())throw Error('نسخهٔ ذخیره‌شده‌ای وجود ندارد.');const parts=kind==='album'?Math.ceil(projectImages(project).length/10):1;if(!parts)throw Error('آلبوم این پروژه هنوز تصویر ندارد.');for(let i=0;i<parts;i++){await enqueueDelivery(env,`asset:${updateId}:${kind}:${i}`,'asset',{projectId:project.id,material:kind,old,offset:i*10});count++;}}
 await reply(env,owner,'درخواست '+project.title+' ثبت شد. فایل آماده مستقیماً می‌رسد؛ تولید PDF جدید ممکن است کمی زمان ببرد.'+(count>1?' آلبوم/فایل‌ها به ترتیب در '+count+' بخش ارسال می‌شوند.':''));
}
export async function handleUpdate(update,env,settings,ctx){
 const callback=update.callback_query,message=callback?.message||update.message,user=callback?.from||message?.from;if(!user||message?.chat?.type!=='private')return;const text=String(message.text||'');
 if(!settings.owner_id&&text.startsWith('/start ')){const code=text.slice(7).trim();if(code&&code===settings.pair_code&&settings.pair_expires>Date.now()){await env.DB.prepare('UPDATE telegram_settings SET candidate_id=?,candidate_name=? WHERE id=1 AND owner_id IS NULL AND pair_code=? AND pair_expires>? AND candidate_id IS NULL').bind(String(user.id),String(user.username||user.first_name||'').slice(0,100),code,Date.now()).run();await reply(env,user.id,'درخواست اتصال ثبت شد. در Studio شناسه و نام حساب را بررسی و تأیید کن.');}return;}
 if(String(user.id)!==settings.owner_id||String(message.chat.id)!==settings.owner_id)return;
 if(callback)await telegramCall(env,'answerCallbackQuery',{callback_query_id:callback.id});const owner=String(user.id),action=callback?.data||text;
 try{
 if(!callback&&!text.startsWith('/')){const input=await env.DB.prepare("SELECT * FROM telegram_actions WHERE owner_id=? AND kind='input' AND status='pending' AND expires_at>? ORDER BY created_at DESC LIMIT 1").bind(owner,Date.now()).first();if(input){const payload=JSON.parse(input.payload);await operationAction(env,owner,'/'+payload.kind+' '+payload.id+' '+text,settings);await env.DB.prepare("UPDATE telegram_actions SET status='done' WHERE id=? AND status='pending'").bind(input.id).run();return;}}
 if(callback&&!action.startsWith('input:')&&!action.startsWith('dismiss:'))await env.DB.prepare("UPDATE telegram_actions SET status='cancelled' WHERE owner_id=? AND kind='input' AND status='pending'").bind(owner).run();
 if(action.startsWith('asset:')){const [,material,id]=action.split(':');await requestMaterial(env,owner,await telegramProject(env,id),material,update.update_id);if(ctx)ctx.waitUntil(flushTelegramDeliveries(env,{allowGeneration:false}));else await flushTelegramDeliveries(env);return;}
 if(await operationAction(env,owner,action,settings))return;
 if(action.startsWith('projects:')||action==='/projects'){
 const page=Math.max(0,Math.min(100,Number(action.split(':')[1])||0)),state=await new D1Store(env.DB).read(),projects=materialize(structuredClone(state.draft)).projects.filter(p=>!p.archived),items=projects.slice(page*8,page*8+8);
 await reply(env,owner,'🗂 پروژه‌های Studio — صفحهٔ '+(page+1)+'\nبرای جست‌وجو نام پروژه را بنویس یا /find نام پروژه را بفرست.',[...items.map(p=>[{text:p.title.slice(0,70),callback_data:'project:'+p.id}]),...(projects.length>(page+1)*8?[[{text:'صفحهٔ بعد',callback_data:'projects:'+(page+1)}]]:[]),...(page?[[{text:'صفحهٔ قبل',callback_data:'projects:'+(page-1)}]]:[])]);return;
 }
 if(action.startsWith('project:')){await projectCard(env,owner,await telegramProject(env,action.slice(8)));return;}
 if(action==='/start'||action==='/help'||action==='menu'){await telegramCall(env,'sendMessage',{chat_id:owner,text:'Desartly Studio — Ali Komeili\n\nنام پروژه را بنویس و پرزنتیشن، آلبوم، کاور یا کپشن آن را بگیر. جلسه‌ها، زمان‌های رزرو و پروندهٔ مشتری از همین‌جا قابل مدیریت‌اند. همهٔ دریافت‌ها خصوصی‌اند.',reply_markup:assistantMenu});return;}
 const request=action.match(/^(پرزنتیشن|آلبوم|البوم|کاور|کپشن|pdf|cover|album|caption)\s+(?:(افقی|عمودی|فارسی|انگلیسی|landscape|portrait|english|persian)\s+)?(?:پروژه(?:ٔ)?\s+)?(.+)$/i);
 const state=await new D1Store(env.DB).read(),query=normalize(request?.[3]||action.replace(/^\/find\s+/,'')),matches=materialize(structuredClone(state.draft)).projects.filter(p=>!p.archived&&(normalize(p.title).includes(query)||normalize(p.id).includes(query))).slice(0,20);
 if(matches.length===1){const requested=request?(/^(کاور|cover)$/i.test(request[1])?'cover':/^(آلبوم|البوم|album)$/i.test(request[1])?'album':/^(کپشن|caption)$/i.test(request[1])?(/^(انگلیسی|english)$/i.test(request[2]||'')?'en':'fa'):/^(عمودی|portrait)$/i.test(request[2]||'')?'instagram':'linkedin'):null;if(requested){await requestMaterial(env,owner,matches[0],requested,update.update_id);if(ctx)ctx.waitUntil(flushTelegramDeliveries(env,{allowGeneration:false}));else await flushTelegramDeliveries(env);}else await projectCard(env,owner,matches[0]);}
 else await reply(env,owner,matches.length?'پروژهٔ موردنظر را انتخاب کن:':'پروژه پیدا نشد. نام دقیق‌تر بنویس یا /projects را بفرست.',matches.map(p=>[{text:p.title,callback_data:'project:'+p.id}]));
 }catch(error){await reply(env,owner,error.uncertain?'تلگرام نتیجه را تأیید نکرد. پیش از درخواست دوباره، گفت‌وگو و وضعیت CMS را بررسی کن.':error.message||'درخواست انجام نشد. وضعیت را در CMS بررسی کن.');}
}
export async function telegramResponse(request,env,ctx){const url=new URL(request.url);if(url.pathname!=='/api/studio/telegram'&&url.pathname!=='/api/telegram/webhook')return null;if(!env.DB||!env.DESARTLY_AUTH||!env.OWNER_SESSION_SECRET)return json({error:'Telegram storage is unavailable.'},503);
 if(url.pathname==='/api/telegram/webhook'){if(request.method!=='POST')return json({error:'Method not allowed.'},405);const secret=await env.DESARTLY_AUTH.get('telegram:webhook');if(!secret||request.headers.get('X-Telegram-Bot-Api-Secret-Token')!==secret)return json({error:'Invalid webhook.'},403);const raw=await request.text();if(raw.length>64000)return json({error:'Update too large.'},413);let update;try{update=JSON.parse(raw);}catch{return json({error:'Invalid update.'},400);}if(!Number.isSafeInteger(update.update_id))return json({error:'Invalid update.'},400);const claim=await env.DB.prepare("INSERT OR IGNORE INTO telegram_updates(update_id,status,created_at) VALUES(?,'processing',?)").bind(update.update_id,Date.now()).run();if(!claim.meta?.changes)return json({ok:true});try{const settings=await env.DB.prepare('SELECT * FROM telegram_settings WHERE id=1').first();await handleUpdate(update,env,settings,ctx);await env.DB.prepare("UPDATE telegram_updates SET status='done' WHERE update_id=?").bind(update.update_id).run();}catch{await env.DB.prepare("UPDATE telegram_updates SET status='uncertain' WHERE update_id=?").bind(update.update_id).run();}return json({ok:true});}
 if(!await isOwner(request,env))return json({error:'Owner sign-in required.'},401);if(!['GET','POST'].includes(request.method))return json({error:'Method not allowed.'},405);if(request.method==='POST'&&request.headers.get('Origin')!==url.origin)return json({error:'Request origin rejected.'},403);
 try{const settings=await env.DB.prepare('SELECT * FROM telegram_settings WHERE id=1').first();if(request.method==='GET'){const events=await env.DB.prepare('SELECT update_id,status,created_at FROM telegram_updates ORDER BY created_at DESC LIMIT 20').all();const deliveries=await env.DB.prepare('SELECT id,kind,status,message_id,last_error,created_at,updated_at FROM telegram_deliveries ORDER BY created_at DESC LIMIT 30').all();return json({preferences:{notifications:settings.notifications,reminders:settings.reminders,reminderMinutes:settings.reminder_minutes},deliveries:deliveries.results||[],configured:!!await token(env),botName:settings.bot_name,ownerId:settings.owner_id,ownerName:settings.owner_name,candidateId:settings.candidate_id,candidateName:settings.candidate_name,events:events.results||[]});}const raw=await request.text();if(raw.length>6000)return json({error:'Request too large.'},413);const body=JSON.parse(raw);
 if(body.action==='preferences'){if(!settings.owner_id)throw Error('Connect your owner account first.');for(const name of ['notifications','reminders','reminder_minutes'])if(body[name]!==undefined){if(!(name==='reminder_minutes'?[30,60,1440]:[0,1]).includes(body[name]))throw Error('Choose a valid preference.');await env.DB.prepare(`UPDATE telegram_settings SET ${name}=?,updated_at=? WHERE id=1`).bind(body[name],Date.now()).run();}return json({ok:true});}
 if(body.action==='process'){if(!settings.owner_id)throw Error('Connect your owner account first.');ctx?.waitUntil(flushTelegramDeliveries(env,{allowGeneration:false}));return json({ok:true});}
 if(body.action==='retry'){if(!settings.owner_id)throw Error('Connect your owner account first.');const claim=await env.DB.prepare("UPDATE telegram_deliveries SET status='pending',attempts=0,next_attempt=0,updated_at=? WHERE id=? AND status='failed'").bind(Date.now(),String(body.id)).run();if(!claim.meta?.changes)throw Error('Only a confirmed failed delivery can be retried.');ctx?.waitUntil(flushTelegramDeliveries(env,{allowGeneration:false}));return json({ok:true});}
 if(body.action==='connect'){if(typeof body.token!=='string'||!/^\d{5,15}:[A-Za-z0-9_-]{20,100}$/.test(body.token))throw Error('Enter the BotFather token in this private form.');if(settings.owner_id)throw Error('A bot is already paired. Keep its existing connection.');const temp={...env,TELEGRAM_BOT_TOKEN:body.token},bot=await telegramCall(temp,'getMe',{});const secret=crypto.randomUUID().replaceAll('-','');await env.DESARTLY_AUTH.put('telegram:webhook',secret);await putToken(env,body.token);await telegramCall(temp,'setWebhook',{url:'https://desartly.layebuzz.workers.dev/api/telegram/webhook',secret_token:secret,max_connections:1,allowed_updates:['message','callback_query']});await env.DB.prepare('UPDATE telegram_settings SET bot_name=?,updated_at=? WHERE id=1').bind(bot.username,Date.now()).run();return json({ok:true,botName:bot.username});}
 if(body.action==='pair'){if(settings.owner_id)throw Error('The owner is already connected.');if(!settings.bot_name)throw Error('Connect the bot first.');const code=crypto.randomUUID().replaceAll('-','');await env.DB.prepare('UPDATE telegram_settings SET pair_code=?,pair_expires=?,candidate_id=NULL,candidate_name=NULL WHERE id=1 AND owner_id IS NULL').bind(code,Date.now()+600000).run();return json({url:'https://t.me/'+settings.bot_name+'?start='+code});}
 if(body.action==='approve'){if(!settings.candidate_id||body.candidateId!==settings.candidate_id||settings.pair_expires<Date.now())throw Error('The connection request expired. Start again.');const claim=await env.DB.prepare('UPDATE telegram_settings SET owner_id=candidate_id,owner_name=candidate_name,candidate_id=NULL,candidate_name=NULL,pair_code=NULL,pair_expires=NULL,notifications_since=? WHERE id=1 AND owner_id IS NULL AND candidate_id=?').bind(Date.now(),body.candidateId).run();if(!claim.meta?.changes)throw Error('Owner connection changed. Refresh.');return json({ok:true});}
 return json({error:'Unknown action.'},400);
 }catch(error){return json({error:error.message||'Telegram connection failed.'},400);}
}
