export const orbitGraphic=`<svg viewBox="0 0 640 460" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">
 <path d="M76 230H564M320 42V418" stroke="currentColor" opacity=".09"/>
 <circle cx="320" cy="230" r="164" stroke="currentColor" opacity=".12" stroke-dasharray="2 8"/>
 <g stroke="currentColor" stroke-width="1.2"><ellipse cx="320" cy="230" rx="244" ry="91" transform="rotate(-28 320 230)" opacity=".3"/><ellipse cx="320" cy="230" rx="213" ry="136" transform="rotate(34 320 230)" opacity=".16"/></g>
 <circle cx="320" cy="230" r="66" fill="#f0ebfa"/><circle cx="320" cy="230" r="66" stroke="#7951c5" stroke-opacity=".3"/>
 <path d="M268 216C294 200 349 203 379 224M260 241C297 225 345 230 376 247" stroke="#7951c5" stroke-opacity=".35"/>
 <circle cx="116" cy="331" r="11" fill="#252a36"/><circle cx="499" cy="138" r="5" fill="#7951c5"/>
 <g class="orbit-satellite"><circle cx="320" cy="66" r="8" fill="#7951c5"/><circle cx="320" cy="66" r="15" stroke="#7951c5" stroke-opacity=".2"/></g>
 <path d="M481 343h12m-6-6v12M154 110h8m-4-4v8" stroke="currentColor" opacity=".35"/>
 <circle cx="487" cy="349" r="2" fill="currentColor" opacity=".3"/>
</svg>`;
export const orbitErrorCss=`
.orbit-error{--orbit-ink:#252a36;--orbit-muted:#707481;--orbit-violet:#7951c5;color:var(--orbit-ink);font-family:"DM Sans",sans-serif;padding:clamp(36px,7vw,100px) clamp(24px,6vw,88px);max-width:1360px;margin:auto;min-height:68svh;display:grid;grid-template-columns:1fr 1.12fr;align-items:center;gap:32px}
.orbit-error-copy{max-width:510px}.orbit-error-kicker{font-size:11px;letter-spacing:.16em;text-transform:uppercase;display:flex;align-items:center;gap:12px;color:var(--orbit-muted);margin:0 0 26px}.orbit-error-kicker:before{content:"";height:1px;width:28px;background:var(--orbit-violet)}
.orbit-error h1{font-family:Manrope,"DM Sans",sans-serif;font-size:clamp(42px,5.6vw,76px);font-weight:500;line-height:1.08;letter-spacing:-.055em;margin:0 0 24px}.orbit-error-description{max-width:370px;font-size:16px;line-height:1.7;color:var(--orbit-muted);margin:0 0 32px}
.orbit-error-actions{display:flex;align-items:center;flex-wrap:wrap;gap:22px}.orbit-error-primary{display:inline-flex;align-items:center;gap:28px;background:var(--orbit-ink);color:#fff;border:0;border-radius:999px;padding:15px 24px;min-height:48px;font:inherit;font-size:14px;cursor:pointer;text-decoration:none;transition:background .2s}.orbit-error-primary:hover{background:#4b3b68}.orbit-error-secondary{font-size:14px;text-decoration:underline;text-underline-offset:5px;padding:12px 0;min-height:44px}.orbit-error a:focus-visible,.orbit-error button:focus-visible{outline:2px solid var(--orbit-violet);outline-offset:5px}
.orbit-error-art{position:relative;min-width:0;pointer-events:none}.orbit-error-art svg{display:block;width:100%;height:auto;color:var(--orbit-ink)}.orbit-error-code{position:absolute;inset:0;display:grid;place-items:center;font-family:Manrope,sans-serif;font-size:36px;font-weight:500;letter-spacing:-.06em}.orbit-error-coordinate{text-align:center;color:var(--orbit-muted);font-size:10px;letter-spacing:.15em;text-transform:uppercase;margin:0}
.orbit-satellite{transform-origin:320px 230px;animation:desartly-orbit 50s linear infinite}@keyframes desartly-orbit{to{transform:rotate(360deg)}}
.orbit-error-standalone{min-height:100svh;background:#fff}.orbit-error-brand{display:inline-block;margin:32px clamp(24px,6vw,88px);font-family:Manrope,sans-serif;font-size:25px;font-weight:650;letter-spacing:-.07em;text-decoration:none;color:var(--orbit-ink,#252a36)}.orbit-error-brand sup{font-size:10px;vertical-align:top;margin-left:3px}
@media(max-width:700px){.orbit-error{grid-template-columns:1fr;gap:28px;min-height:auto;padding-top:28px;padding-bottom:56px}.orbit-error-art{grid-row:1;max-width:380px;width:100%;margin:auto}.orbit-error-copy{max-width:460px}.orbit-error h1{font-size:44px}.orbit-error-kicker{margin-bottom:20px}.orbit-error-description{font-size:15px;margin-bottom:24px}.orbit-error-code{font-size:28px}.orbit-error-standalone .orbit-error-brand{margin-top:24px;margin-bottom:0}}
@media(prefers-reduced-motion:reduce){.orbit-satellite{animation:none}.orbit-error-primary{transition:none}}
`;
export function orbitNotFoundHtml(){return `<style>${orbitErrorCss}</style><main id="main" class="orbit-error"><div class="orbit-error-copy"><p class="orbit-error-kicker">404 / Off the map</p><h1>A little out<br/>of orbit.</h1><p class="orbit-error-description">This page may have moved, or the link is no longer here. Let’s find your way back.</p><div class="orbit-error-actions"><a class="orbit-error-primary" href="/">Back to Desartly <span aria-hidden="true">↗</span></a><a class="orbit-error-secondary" href="/work">Explore projects</a></div></div><div class="orbit-error-art">${orbitGraphic}<span class="orbit-error-code">404</span><p class="orbit-error-coordinate">Desartly / A new direction</p></div></main>`;}
