import{readFile,writeFile,mkdir}from'node:fs/promises';import{spawnSync}from'node:child_process';import{randomBytes,createHash,createCipheriv,createDecipheriv}from'node:crypto';import{resolve}from'node:path';
import{createMediaArchive,readMediaArchive}from'../src/cms/media-archive.js';
const destination=resolve(process.argv[2]||'../backups'),key=await readFile(resolve(process.argv[3]||'../backup-recovery.key'));if(key.length!==32)throw Error('Invalid recovery key.');await mkdir(destination,{recursive:true,mode:0o700});
const config=await readFile('/Users/ali/.wrangler/config/default.toml','utf8'),cfToken=config.match(/^oauth_token\s*=\s*"([^"]+)"/m)?.[1];if(!cfToken)throw Error('Cloudflare login required.');
function request(url,headers=[],body,method='GET',binary=false){const cfg=['silent','show-error','fail','max-time = 30','connect-timeout = 8','retry = 2','retry-delay = 1','retry-all-errors','write-out = "%{stderr}HTTP %{http_code}"','url = '+JSON.stringify(url),'request = '+JSON.stringify(method),...headers.map(h=>'header = '+JSON.stringify(h))];if(body!==undefined)cfg.push('header = "Content-Type: application/json"','data = '+JSON.stringify(JSON.stringify(body)));const r=spawnSync('curl',['--config','-'],{input:cfg.join('\n'),...(binary?{}:{encoding:'utf8'}),maxBuffer:20*1024*1024});if(r.status!==0)throw Error('Backup transfer failed ('+method+'): '+r.stderr.toString().match(/HTTP \d+/)?.[0]);return binary?r.stdout:JSON.parse(r.stdout);}
const secretUrl='https://api.cloudflare.com/client/v4/accounts/f4b1108ab283470d34628c2f3d67c77a/workers/scripts/desartly/secrets';
const token=randomBytes(32).toString('hex'),ticket={hash:createHash('sha256').update(token).digest('hex'),expiresAt:new Date(Date.now()+30*60*1000).toISOString()};
const result=request(secretUrl,['Authorization: Bearer '+cfToken],{name:'BACKUP_READ_TICKET',text:JSON.stringify(ticket),type:'secret_text'},'PUT');if(!result.success)throw Error('Unable to create temporary read-only backup access.');
let primaryError;
try{
 const base='https://desartly.layebuzz.workers.dev/api/studio/media-backup',headers=['Authorization: Bearer '+token];
 const manifest=request(base,headers),total=manifest.media.reduce((n,m)=>n+m.variants.length,0);
 const blob=await createMediaArchive(manifest,async(m,i,v)=>{const b=request(base+'/file?'+new URLSearchParams({id:m.id,variant:i,source:v.source}),headers,undefined,'GET',true);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);},(done)=>{if(done%50===0||done===total)console.log('Verified downloads: '+done+'/'+total);});
 const checked=await readMediaArchive(blob);if(checked.manifest.media.length!==manifest.media.length)throw Error('Archive verification failed.');
 const date=new Date().toISOString().replace(/[:.]/g,'-'),path=resolve(destination,'desartly-media-'+date+'.zip.enc'),plain=Buffer.from(await blob.arrayBuffer()),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv),ciphertext=Buffer.concat([cipher.update(plain),cipher.final()]),tag=cipher.getAuthTag(),bytes=Buffer.concat([Buffer.from('DSZ1'),iv,tag,ciphertext]);const recovery=createDecipheriv('aes-256-gcm',key,iv);recovery.setAuthTag(tag);if(!Buffer.concat([recovery.update(ciphertext),recovery.final()]).equals(plain))throw Error('Media encryption recovery failed.');await writeFile(path,bytes,{mode:0o600,flag:'wx'});
 const proof={createdAt:new Date().toISOString(),file:path,media:manifest.media.length,files:total,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),allEntryChecksumsVerified:true,encryptionRoundTrip:true,includesArchivedAndPrivate:true};await writeFile(path+'.proof.json',JSON.stringify(proof,null,2),{mode:0o600});console.log(JSON.stringify(proof,null,2));
}catch(e){primaryError=e;throw e;}finally{try{const removed=request(secretUrl+'/BACKUP_READ_TICKET',['Authorization: Bearer '+cfToken],undefined,'DELETE');if(!removed.success)throw Error('Temporary backup access cleanup failed. Ticket expires automatically.');}catch(e){if(primaryError)console.error('Temporary access cleanup requires retry; it also expires automatically.');else throw e;}}
