import fs from 'node:fs';
const root=new URL('./',import.meta.url);
const html=name=>fs.readFileSync(new URL(name+'.html',root),'utf8');
const project={id:'afc-qatar',title:'AFC Qatar',category:'Product & AI',tags:['Product & AI','Art Direction','Experience Design'],year:'2023',sample:true,cover:0,coverImage:'/projects/afc-qatar/cover-luxury.webp?v=91da2f7c',heroImage:'/projects/afc-qatar/cover-luxury.webp?v=91da2f7c',summary:'An editorial approach to the Asian Cup matchday. Architecture, anticipation and a thoughtfully composed ticketing journey — through Flightio.',clientName:'AFC Qatar',clientLabel:'THE CLIENT',clientLogo:'/projects/afc-qatar/afc-transparent.webp',clientDescription:'AFC Asian Cup Qatar 2023. Project delivered through Flightio as the intermediary.',challenge:'Make ticket discovery feel like the beginning of an extraordinary experience.',role:'Art direction, experience design and interactive prototyping.',deliverables:'Campaign imagery, responsive landing, interaction studies and a generated wireframe.',outcome:'A concept journey from emotional discovery to a clear, considered seat selection.',credits:'Design: Ali Komeili · Project via Flightio.',blocks:[
{id:'afc-opening',type:'text',layout:'statement',chapter:'01 / THE EXPERIENCE',title:'The experience starts before kick-off.',text:'The direction borrows from luxury hospitality: architectural imagery, a restrained palette and room to breathe. The match is the destination. Every choice on the way there deserves the same care.'},
{id:'afc-landing',type:'html',title:'AFC Qatar · Luxury matchday landing experience',autoHeight:true,scrollSync:true,previewHeight:2150,mobileHeight:3100,html:html('landing')},
{id:'afc-details',type:'text',layout:'chapter',chapter:'02 / THE INTERACTIONS',title:'Every interaction, considered.',text:'An animated seat atlas and a personal invitation turn selection into a continuous conversation. Soft reveals, responsive totals and tactile states guide the eye without interrupting the journey. Try the areas, guest count and saved encounter below.'},
{id:'afc-interactions',type:'html',title:'AFC Qatar · Seat atlas and personal invitation',autoHeight:true,scrollSync:true,previewHeight:1500,mobileHeight:2700,html:html('interactions')},
{id:'afc-process',type:'text',layout:'chapter',chapter:'03 / THE STRUCTURE',title:'From intent to interface.',text:'Discover. Choose. Experience. The generated sketch translates this progression into desktop and mobile views, making the visual hierarchy and seat-selection flow visible before the final surface.'},
{id:'afc-wireframe',type:'image',image:'/projects/afc-qatar/wireframe.webp',alt:'Generated graphite and burgundy wireframe study showing a luxury Qatar landing, mobile view and stadium seat-selection flow'},
{id:'afc-close',type:'text',layout:'note',title:'A quieter interface. A more memorable experience.',text:'Ivory, oxblood and warm metallic light create the visual world. Motion follows the main page scroll, while each interaction remains clear with reduced motion. Illustrative concept imagery, fixtures and prices are used to demonstrate the experience; no live ticketing or measured outcomes are claimed.'}
]};
fs.writeFileSync(new URL('project.json',root),JSON.stringify(project,null,2)+'\n');
console.log(`AFC project: ${Buffer.byteLength(JSON.stringify(project))} bytes; ${project.blocks.filter(b=>b.type==='html').length} merged HTML blocks. No application imports.`);
