import fs from 'node:fs';
const root=new URL('./',import.meta.url);
const html=name=>fs.readFileSync(new URL(name+'.html',root),'utf8');
const project={id:'afc-qatar',title:'AFC Qatar · Be There. Feel It All.',category:'Product & AI',tags:['Product & AI','Art Direction','Campaign'],year:'2023',sample:true,cover:0,coverImage:'/projects/afc-qatar/cover.webp',heroImage:'/projects/afc-qatar/cover.webp',summary:'The energy of the stands, translated into a clear ticketing journey. An AFC Asian Cup Qatar landing page, presented through Flightio.',clientName:'Flightio',clientLabel:'PROJECT INTERMEDIARY',clientLogo:'/projects/afc-qatar/flightio-logo.webp',clientDescription:'Project intermediary for the AFC Qatar landing-page presentation. Flightio connects the travel context with the matchday experience.',challenge:'Turn the emotion of a major football tournament into a focused route to match tickets.',role:'Art direction, landing-page UI and interaction concept.',deliverables:'Campaign cover, responsive landing page, interactive ticket components and a sketch wireframe.',outcome:'A working design prototype connecting match discovery, stand selection and a transparent ticket total.',credits:'Design presentation: Ali Komeili. Project intermediary: Flightio. AFC and Flightio marks supplied for this study.',blocks:[
{id:'afc-intro',type:'text',layout:'statement',title:'From the first roar to the final tap.',text:'Football is emotional. Buying a ticket should feel effortless. This direction pairs stadium-scale imagery and condensed typography with a simple, deliberate booking flow.'},
{id:'afc-chapter-01',type:'text',layout:'chapter',chapter:'01 / THE LANDING',title:'One stage. One clear invitation.',text:'A cinematic opening draws the fan in. Team filters bring the right matches forward, while the ticket action stays visible and easy to understand. Try the filters and ticket previews below.'},
{id:'afc-landing',type:'html',title:'AFC Qatar · Interactive ticketing landing page',autoHeight:true,html:html('landing')},
{id:'afc-chapter-02',type:'text',layout:'chapter',chapter:'02 / THE DETAILS',title:'Make every choice feel immediate.',text:'The experience responds to intent: selecting a stand updates the ticket, adding a guest recalculates the total, and following a team changes the saved state. The same controls work with a mouse, touch or keyboard.'},
{id:'afc-interactions',type:'html',title:'AFC Qatar · Seat selection and reactive ticket',autoHeight:true,html:html('interactions')},
{id:'afc-chapter-03',type:'text',layout:'chapter',chapter:'03 / THE PROCESS',title:'A simple structure beneath the spectacle.',text:'The journey starts with a single invitation, narrows into a match choice and finishes with a visible ticket summary. This reconstructed sketch makes the hierarchy and mobile decisions explicit.'},
{id:'afc-wireframe',type:'html',title:'AFC Qatar · Sketch wireframe board',autoHeight:true,html:html('wireframe')},
{id:'afc-close',type:'text',layout:'note',title:'Designed for the moment. Built around the fan.',text:'A restrained palette keeps the stadium imagery in focus. Lightweight interactions explain what changed, and reduced-motion preferences are respected. This is a design study: fixtures, prices and seat categories illustrate the flow; no ticketing system or measured conversion result is claimed.'}
]};
fs.writeFileSync(new URL('project.json',root),JSON.stringify(project,null,2)+'\n');
console.log(`AFC project: ${Buffer.byteLength(JSON.stringify(project))} bytes; ${project.blocks.filter(b=>b.type==='html').length} merged HTML blocks. Not imported into application JS.`);
