import React from 'react';
export const chartTypes=['bar','line','funnel','radar','scanpath','metrics'];
export function ArticleChart({block:b}){
 const labels=b.labels||[],values=b.values||[],max=Math.max(1,...values),colors=['#244d3b','#a56b13','#72568d','#bc593b'],fmt=v=>Number(v).toLocaleString('fa')+(b.unit||''),W=640,H=310;
 let graphic;
 if(b.chartType==='metrics')graphic=<div className="article-metric-grid">{labels.map((l,i)=><div key={i}><strong>{fmt(values[i])}</strong><span>{l}</span></div>)}</div>;
 else if(b.chartType==='funnel'){graphic=<svg viewBox="0 0 640 330" role="img" aria-label={b.title}>{labels.map((l,i)=>{const top=360*values[i]/max,bottom=360*(values[i+1]??values[i])/max,y=12+i*(300/Math.max(labels.length,1));return <g key={i}><polygon points={`${380-top/2},${y} ${380+top/2},${y} ${380+bottom/2},${y+300/Math.max(labels.length,1)-12} ${380-bottom/2},${y+300/Math.max(labels.length,1)-12}`} fill={colors[i%4]}/><text x="174" y={y+150/Math.max(labels.length,1)+5} textAnchor="end" fontSize="21">{l}</text><text x="590" y={y+150/Math.max(labels.length,1)+5} textAnchor="start" fontSize="21">{fmt(values[i])}</text></g>})}</svg>;}
 else if(b.chartType==='bar')graphic=<div className="article-bars">{labels.map((l,i)=><div key={i}><div><span>{l}</span><b>{fmt(values[i])}</b></div><div className="article-bar-track"><i style={{width:Math.max(0,values[i]/max*100)+'%',background:colors[i%4]}}/></div></div>)}</div>;
 else if(b.chartType==='radar'){const n=labels.length,xy=(i,r)=>[320+Math.sin(i/n*Math.PI*2)*r,150-Math.cos(i/n*Math.PI*2)*r];graphic=<svg viewBox="0 0 640 330" role="img" aria-label={b.title}>{[.25,.5,.75,1].map(r=><polygon key={r} points={labels.map((_,i)=>xy(i,115*r).join(',')).join(' ')} fill="none" stroke="#d5dacc"/>)}{labels.map((l,i)=>{const [x,y]=xy(i,145);return <text key={i} x={x} y={y} textAnchor="middle" fontSize="17">{l}</text>})}<polygon points={values.map((v,i)=>xy(i,115*v/100).join(',')).join(' ')} fill="#244d3b25" stroke="#244d3b" strokeWidth="3"/>{values.map((v,i)=>{const [x,y]=xy(i,115*v/100);return <circle key={i} cx={x} cy={y} r="4" fill="#244d3b"/>})}</svg>;}
 else if(b.chartType==='scanpath'){const points=b.points||[[150,65],[310,110],[440,200],[210,230]];graphic=<svg viewBox="0 0 640 330" role="img" aria-label={b.title}><rect x="20" y="10" width="600" height="300" rx="20" fill="#efeee4"/>{labels.map((l,i)=><text key={i} x={points[i]?.[0]} y={(points[i]?.[1]||0)-30} textAnchor="middle" fontSize="18">{l}</text>)}<polyline points={points.map(p=>p.join(',')).join(' ')} fill="none" stroke="#bc593b" strokeDasharray="6 5" strokeWidth="3"/>{points.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r={16+(values[i]||0)/5} fill="#e1aa3a35"/><circle cx={x} cy={y} r="15" fill="#244d3b"/><text x={x} y={y+6} fill="white" textAnchor="middle" fontSize="17">{i+1}</text></g>)}</svg>;}
 else{const coords=values.map((v,i)=>[52+i*(W-100)/Math.max(values.length-1,1),H-45-v/max*(H-80)]);graphic=<svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label={b.title}>{[0,.5,1].map(r=><g key={r}><line x1="52" y1={H-45-r*(H-80)} x2="600" y2={H-45-r*(H-80)} stroke="#d5dacc"/><text x="40" y={H-39-r*(H-80)} textAnchor="end" fontSize="15">{Math.round(max*r)}</text></g>)}<polyline points={coords.map(p=>p.join(',')).join(' ')} fill="none" stroke="#244d3b" strokeWidth="4"/>{coords.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="5" fill="#244d3b"/><text x={x} y={y-14} textAnchor="middle" fontSize="16">{fmt(values[i])}</text><text x={x} y="300" textAnchor="middle" fontSize="15">{labels[i]}</text></g>)}</svg>;}
 return <section className="article-chart"><header><span className="chart-sample">{b.sample?'دادهٔ فرضی · صرفاً تست نمایش':'دادهٔ ارائه‌شده'}</span><h2>{b.title}</h2><p>{b.description}</p></header><div className="article-chart-graphic">{graphic}</div>{b.insight&&<p className="chart-insight">{b.insight}</p>}<footer>{b.source||'منبع مشخص نشده'}{b.sample&&' · نتایج واقعی MyOm نیست.'}</footer><details><summary>مشاهدهٔ جدول داده‌ها</summary><table><thead><tr><th>شاخص</th><th>مقدار</th></tr></thead><tbody>{labels.map((l,i)=><tr key={i}><td>{l}</td><td>{fmt(values[i])}</td></tr>)}</tbody></table></details></section>;
}
