import React,{useEffect,useRef,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {X,ArrowUpRight,ArrowLeft,Check} from 'lucide-react';
import {disciplines} from './project-tags.js';
import {targetIndustries} from './cms/growth-model.js';
import './booking.css';
import {NativeCalendar} from './NativeCalendar.jsx';
export function BookingLauncher(){return <Link className="booking-launcher" to="/contact" aria-label="Book a call with Ali Komeili"><span className="booking-person"><b>Ali Komeili</b><small>Let’s make something matter.</small></span><strong>Book a call <ArrowUpRight size={16}/></strong></Link>}
export function BookCall({standalone=false}){
 const [mobile,setMobile]=useState(()=>window.matchMedia('(max-width:700px)').matches);
 useEffect(()=>{const media=window.matchMedia('(max-width:700px)'),update=()=>setMobile(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 const modal=!standalone&&!mobile;
 const navigate=useNavigate(),dialog=useRef(null),[step,setStep]=useState(1),[brief,setBrief]=useState(()=>{try{const saved=JSON.parse(sessionStorage.getItem('desartly-brief'));if(saved&&Date.now()-saved.at<86400000)return saved.brief;}catch{}return {meetingType:'briefing',name:'',email:'',company:'',message:'',industry:'',services:[]};});
 const close=()=>standalone?window.location.assign('https://www.desartly.info/work'):navigate('/work');
 useEffect(()=>{if(!modal)return;const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.focus();const key=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=[...dialog.current.querySelectorAll('button:not(:disabled),input,textarea,select,a[href],iframe')].filter(n=>n.getClientRects().length);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.isConnected&&previous.focus();};},[modal]);
 useEffect(()=>{const heading=dialog.current?.querySelector('.booking-content h2');heading?.setAttribute('tabindex','-1');heading?.focus({preventScroll:true});if(modal&&dialog.current)dialog.current.scrollTop=0;else if(step===2)window.scrollTo({top:0,behavior:'instant'});},[step,modal]);
 useEffect(()=>{try{sessionStorage.setItem('desartly-brief',JSON.stringify({brief,at:Date.now()}));}catch{}},[brief]);
 const patch=(key,value)=>setBrief(b=>({...b,[key]:value}));
 const content=step===1?<form onSubmit={e=>{e.preventDefault();if(!brief.services.length){e.currentTarget.querySelector('input[type=checkbox]')?.focus();return;}setStep(2);}}><h2>A little about your conversation</h2><fieldset className="booking-type"><legend>Session type</legend>{[["briefing","Project briefing","Explore a project, its scope and next steps."],["mentorship","Mentorship","Discuss your portfolio, design practice or career direction."]].map(([value,label,detail])=><label key={value}><input type="radio" name="meeting-type" checked={(brief.meetingType||"briefing")===value} onChange={()=>patch("meetingType",value)}/><span><strong>{label}</strong><small>{detail}</small></span></label>)}</fieldset><div className="booking-fields"><label>Your name<input required maxLength={100} value={brief.name} onChange={e=>patch('name',e.target.value)} autoComplete="name"/></label><label>Email address<input required maxLength={254} type="email" value={brief.email} onChange={e=>patch('email',e.target.value)} autoComplete="email"/></label></div><label>Company, organisation or independent practice<input required maxLength={150} value={brief.company} onChange={e=>patch('company',e.target.value)} autoComplete="organization"/></label><fieldset><legend>What can I help with? <small>Choose at least one</small></legend><div className="booking-services">{disciplines.map(d=><label key={d}><input type="checkbox" checked={brief.services.includes(d)} onChange={e=>patch('services',e.target.checked?[...brief.services,d]:brief.services.filter(x=>x!==d))}/>{d}</label>)}</div></fieldset><label>Industry<select required value={brief.industry} onChange={e=>patch('industry',e.target.value)}><option value="">Select an industry</option>{targetIndustries.map(i=><option key={i}>{i}</option>)}<option>Other</option></select></label><label>What would you like to discuss?<textarea required minLength={10} maxLength={1500} rows={3} value={brief.message} onChange={e=>patch('message',e.target.value)} placeholder="Your context, questions and what you want to achieve."/></label><p className="booking-muted">Your brief stays in this browser tab for up to 24 hours. Confirming shares it with Ali and Google Calendar. <Link to="/privacy">Privacy details</Link></p><button type="button" className="booking-back" onClick={()=>{setBrief({meetingType:'briefing',name:'',email:'',company:'',message:'',industry:'',services:[]});try{sessionStorage.removeItem('desartly-booking-attempt');}catch{}}}>Clear my brief</button><button className="booking-primary" disabled={!brief.services.length} type="submit">Choose a time <ArrowUpRight size={18}/></button></form>:<NativeCalendar brief={brief} onBack={()=>setStep(1)} onDone={()=>{try{sessionStorage.removeItem('desartly-brief');sessionStorage.removeItem('desartly-booking-attempt');}catch{}close();}}/>;
 if(standalone)return <div className="booking-page" ref={dialog}><header className="booking-page-header"><a className="booking-page-brand" href="https://www.desartly.info"><img src="/favicon.svg" alt=""/>Desartly<span>CONVERSATIONS</span></a><a href="https://www.desartly.info/work">Explore the portfolio <ArrowUpRight size={16}/></a></header><main className="booking-page-layout"><aside className="booking-page-intro"><div className="booking-host"><span className="booking-host-avatar">AK</span><div><strong>Ali Komeili</strong><small>Independent multidisciplinary designer</small></div></div><span className="booking-page-eyebrow">A CONVERSATION, WITH PURPOSE</span><h1>Good ideas deserve<br/><em>a little time.</em></h1><p>A new project or a fresh perspective on your design practice. Choose your conversation, then find a time that works.</p><div className="booking-session-summary"><span className="booking-duration">30<small>MINUTES</small></span><div><strong>{brief.meetingType==='mentorship'?'Mentorship':'Project briefing'}</strong><span>Google Meet · Online</span><span>Times shown in Tehran</span></div></div><ol className="booking-page-progress" aria-label="Booking steps"><li aria-current={step===1?'step':undefined}><span>{step>1?<Check size={16}/>:1}</span><div>Your conversation<small>A little context before we meet</small></div></li><li aria-current={step===2?'step':undefined}><span>2</span><div>A time to connect<small>Live availability · Instant confirmation</small></div></li></ol><p className="booking-page-note">No back-and-forth. Your appointment is confirmed as soon as you book.</p></aside><section className="booking-page-stage booking-content" aria-label={step===1?'Your conversation':'Choose your appointment'}>{content}</section></main><footer className="booking-page-footer"><span>Desartly · Ali Komeili</span><a href="https://www.desartly.info/privacy">Privacy & your information</a></footer></div>;
 return <div className={mobile?"booking-mobile-shell":"booking-backdrop"} onClick={e=>{if(modal&&e.target===e.currentTarget)close();}}><section ref={dialog} tabIndex={-1} className={mobile?"booking-dialog booking-mobile":"booking-dialog"} role={modal?"dialog":undefined} aria-modal={modal?true:undefined} aria-labelledby="booking-title"><header className="booking-header"><div><span>ALI KOMEILI<small>Independent designer</small></span></div><button aria-label="Close booking" onClick={close}><X size={22}/></button></header><div className="booking-body"><aside className="booking-story"><span className="booking-kicker">A GOOD PROJECT STARTS WITH A CONVERSATION</span><h1 id="booking-title">Book a call.</h1><p>Choose a project briefing or a mentoring session. Share a little context, then reserve 30 minutes with Ali.</p><p className="booking-demo">30 minutes · Google Meet</p></aside><div className="booking-content">{content}</div></div></section></div>;
}
