import React,{useEffect,useMemo,useState} from 'react';
import {FileText,Folder,FolderPlus,Grid2X2,Image as ImageIcon,List,MoreHorizontal,Plus,Search,Star,Upload} from 'lucide-react';
import {optimizeImage} from './data.js';

const text=v=>String(v||'').toLowerCase();
export function CollectionLibrary({kind='article',items,setItems,onOpen,onNew}){
 const[query,setQuery]=useState(''),[selectedId,setSelectedId]=useState(items[0]?.id||''),[filter,setFilter]=useState('all');
 const selected=items.find(i=>i.id===selectedId)||items[0];
 const visible=useMemo(()=>items.filter(item=>(filter==='all'||(filter==='hidden'?item.hidden:!item.hidden))&&(!query||text(item.title+' '+item.category+' '+item.excerpt+' '+item.summary).includes(text(query)))),[items,query,filter]);
 const patch=values=>setItems(current=>current.map(item=>item.id===selected.id?{...item,...values}:item));
 useEffect(()=>{if(!items.some(i=>i.id===selectedId))setSelectedId(items[0]?.id||'')},[items,selectedId]);
 return <main className="collection-library" data-editor-ui>
  <header className="library-heading"><div><span className="eyebrow">CONTENT / {kind==='article'?'JOURNAL':'PROJECTS'}</span><h1>{kind==='article'?'Articles':'Projects'}</h1><p>Find an item, complete its details, then open the visual canvas when layout matters.</p></div><button className="button" onClick={onNew}><Plus size={15}/> New {kind}</button></header>
  <div className="library-toolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${kind}s`}/></label><div className="status-tabs">{['all','visible','hidden'].map(v=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} key={v}>{v}</button>)}</div><span>{visible.length} items</span></div>
  <div className="library-split"><section className="content-list">{visible.map(item=><button key={item.id} className={item.id===selected?.id?'active':''} onClick={()=>setSelectedId(item.id)}><span className="content-thumb">{item.coverImage?<img src={item.coverImage} alt=""/>:<FileText size={20}/>}</span><span><strong>{item.title||`Untitled ${kind}`}</strong><small>{item.category||'Uncategorised'} · {item.date||'No date'}</small></span><i className={item.hidden?'draft':'published'}>{item.hidden?'Hidden':'Visible'}</i></button>)}</section>
   {selected&&<section className="content-inspector"><div className="content-inspector-head"><div><span>DETAILS</span><h2>{selected.title||`Untitled ${kind}`}</h2></div><button className="button" onClick={()=>onOpen(items.indexOf(selected))}>Open visual editor →</button></div>
    <label>Title<input value={selected.title||''} onChange={e=>patch({title:e.target.value})}/></label>
    <div className="two-fields"><label>Category<input value={selected.category||''} onChange={e=>patch({category:e.target.value})}/></label>{kind==='article'&&<label>Publish date<input type="date" value={selected.date||''} onChange={e=>patch({date:e.target.value})}/></label>}</div>
    <label>{kind==='article'?'Excerpt':'Introduction'}<textarea rows="4" value={(kind==='article'?selected.excerpt:selected.summary)||''} onChange={e=>patch(kind==='article'?{excerpt:e.target.value}:{summary:e.target.value})}/></label>
    <label>Card cover<div className="cover-field">{selected.coverImage?<img src={selected.coverImage} alt=""/>:<span><ImageIcon/>No cover</span>}<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)patch({coverImage:await optimizeImage(f,{purpose:'cover',aspect:kind==='article'?1.5:1})})}}/></div></label>
    <label className="publish-switch"><input type="checkbox" checked={!selected.hidden} onChange={e=>patch({hidden:!e.target.checked})}/><span><strong>{selected.hidden?'Hidden from public lists':'Visible in public lists'}</strong><small>All edits remain in the site draft until you use Publish.</small></span></label>
   </section>}
  </div>
 </main>;
}

export function MediaLibrary({onNotice}){
 const[items,setItems]=useState([]),[query,setQuery]=useState(''),[folder,setFolder]=useState('All files'),[view,setView]=useState('grid'),[sort,setSort]=useState('newest'),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[newFolder,setNewFolder]=useState(''),[extraFolders,setExtraFolders]=useState([]),[starred,setStarred]=useState(()=>JSON.parse(localStorage.getItem('desartly-starred-media')||'[]'));
 const load=async()=>{const r=await fetch('/api/studio');if(r.ok)setItems((await r.json()).media||[])};
 useEffect(()=>{load()},[]);
 const folders=['All files','Recent','Starred',...Array.from(new Set([...extraFolders,...items.map(i=>i.folder||'Uploads')])).sort()];
 const visible=useMemo(()=>items.filter(i=>(folder==='All files'||(folder==='Recent'&&Date.now()-new Date(i.createdAt||0).getTime()<30*864e5)||(folder==='Starred'&&starred.includes(i.id))||(i.folder||'Uploads')===folder)&&(!query||text(i.name+' '+i.alt).includes(text(query)))).sort((a,b)=>sort==='name'?String(a.name).localeCompare(String(b.name)):String(b.createdAt).localeCompare(String(a.createdAt))),[items,folder,query,sort,starred]);
 async function meta(item,values){const r=await fetch('/api/studio/media',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,name:values.name??item.name,alt:values.alt??item.alt,folder:values.folder??item.folder})});if(r.ok){setItems(current=>current.map(v=>v.id===item.id?{...v,...values}:v));setSelected(v=>v?.id===item.id?{...v,...values}:v)}}
 async function upload(files){setBusy(true);try{for(const file of files){await optimizeImage(file);onNotice?.(`Imported ${file.name}`)}await load()}catch(e){onNotice?.(e.message)}finally{setBusy(false)}}
 function addFolder(){const name=newFolder.trim();if(!name)return;setExtraFolders(current=>current.includes(name)?current:[...current,name]);setFolder(name);setNewFolder('');}
 function toggleStar(item){setStarred(current=>{const next=current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id];localStorage.setItem('desartly-starred-media',JSON.stringify(next));return next})}
 return <main className="media-drive" data-editor-ui><header className="library-heading"><div><span className="eyebrow">DATABASE / ASSETS</span><h1>Files</h1><p>A shared media library for every page, project, article and credential.</p></div><label className="button"><Upload size={15}/>{busy?'Uploading…':'Upload files'}<input hidden type="file" multiple accept="image/*" disabled={busy} onChange={e=>upload([...e.target.files])}/></label></header>
  <div className="drive-shell"><aside><button className="drive-new"><Plus size={18}/> New</button><nav>{folders.map(name=><button className={folder===name?'active':''} onClick={()=>setFolder(name)} key={name}><Folder size={16}/>{name}<span>{name==='All files'?items.length:items.filter(i=>(i.folder||'Uploads')===name).length}</span></button>)}</nav><div className="new-folder"><input value={newFolder} onChange={e=>setNewFolder(e.target.value)} placeholder="New folder"/><button onClick={addFolder}><FolderPlus size={16}/></button></div></aside>
   <section className="drive-main"><div className="drive-toolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search files"/></label><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Last modified</option><option value="name">Name</option></select><button aria-label="Grid view" className={view==='grid'?'active':''} onClick={()=>setView('grid')}><Grid2X2 size={16}/></button><button aria-label="List view" className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={16}/></button></div>
    <div className={`drive-files ${view}`}>{visible.map(item=><button key={item.id} onClick={()=>setSelected(item)} className={selected?.id===item.id?'selected':''}><span className="drive-preview">{item.type?.startsWith('image')?<img src={item.url} alt=""/>:<FileText/>}</span><span><strong>{item.name}</strong><small>{item.folder||'Uploads'}</small></span><MoreHorizontal size={16}/></button>)}</div>
   </section>
   {selected&&<aside className="file-details"><button className="close-details" onClick={()=>setSelected(null)}>×</button><div className="detail-preview">{selected.type?.startsWith('image')?<img src={selected.url} alt={selected.alt||''}/>:<FileText/>}</div><h2>{selected.name}</h2><button className={`star-file ${starred.includes(selected.id)?'active':''}`} onClick={()=>toggleStar(selected)}><Star size={15}/>{starred.includes(selected.id)?'Starred':'Add to starred'}</button><label>Name<input value={selected.name||''} onChange={e=>setSelected({...selected,name:e.target.value})} onBlur={()=>meta(selected,{name:selected.name})}/></label><label>Folder<select value={selected.folder||'Uploads'} onChange={e=>meta(selected,{folder:e.target.value})}>{folders.filter(f=>!['All files','Recent','Starred'].includes(f)).map(f=><option key={f}>{f}</option>)}</select></label><label>Alt text<textarea rows="4" value={selected.alt||''} onChange={e=>setSelected({...selected,alt:e.target.value})} onBlur={()=>meta(selected,{alt:selected.alt})}/></label><a className="button" href={selected.url} target="_blank" rel="noreferrer">Open file</a><small>{selected.type} · {selected.variants?.at(-1)?.size?Math.round(selected.variants.at(-1).size/1024)+' KB':''}</small></aside>}
  </div>
 </main>;
}
