import React,{useEffect,useState} from 'react';
import {ArrowUp,ArrowDown,Plus,Trash2,Image} from 'lucide-react';
import {resolveHeroSlides} from './hero-slides.js';
export {resolveHeroSlides} from './hero-slides.js';
export function HeroSlideEditor({page,projects,onChange}){
 const slides=resolveHeroSlides(page,projects),[media,setMedia]=useState([]),[picker,setPicker]=useState(null),[query,setQuery]=useState('');
 useEffect(()=>{fetch('/api/cms/state').then(r=>r.ok?r.json():null).then(data=>setMedia((data?.media||data?.state?.media||[]).filter(m=>!m.trashedAt&&m.type?.startsWith('image/')))).catch(()=>{});},[]);
 const values=slides.map(({project,key,...slide})=>({...slide,id:key,projectId:project.id}));
 const save=next=>onChange({heroSlides:next});
 const patch=(i,changes)=>save(values.map((s,n)=>n===i?{...s,...changes}:s));
 const move=(i,delta)=>{const next=[...values];[next[i],next[i+delta]]=[next[i+delta],next[i]];save(next);};
 return <section className="hero-slide-editor"><h3>Homepage hero</h3><p>Wide project images · soft crossfade. Add, remove or reorder slides independently of selected work.</p>{slides.map((s,i)=><div className="hero-slide-edit" key={s.key}><div className="hero-edit-preview">{s.image&&<img src={s.image} alt=""/>}<span>Slide {i+1}</span></div><label>Project<select value={s.project.id} onChange={e=>patch(i,{projectId:e.target.value,image:'',alt:''})}>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><button onClick={()=>{setPicker(i);setQuery('');}}><Image size={14}/>Choose library image</button><label>Image URL<input type="url" value={values[i].image||''} onChange={e=>patch(i,{image:e.target.value})} placeholder="Uses project cover by default"/></label><label>Image description<input value={s.alt||''} onChange={e=>patch(i,{alt:e.target.value})} placeholder={s.project.title}/></label><label>Image focus<select value={s.position||'50% 50%'} onChange={e=>patch(i,{position:e.target.value})}><option value="50% 50%">Centre</option><option value="50% 25%">Upper centre</option><option value="25% 50%">Left</option><option value="75% 50%">Right</option></select></label><div className="hero-edit-actions"><button aria-label={'Move slide '+(i+1)+' up'} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button aria-label={'Move slide '+(i+1)+' down'} disabled={i===slides.length-1} onClick={()=>move(i,1)}><ArrowDown size={15}/></button><button aria-label={'Remove slide '+(i+1)} disabled={slides.length===1} onClick={()=>save(values.filter((_,n)=>n!==i))}><Trash2 size={15}/></button></div></div>)}<button disabled={!projects.length} onClick={()=>save([...values,{id:crypto.randomUUID(),projectId:projects.find(p=>!values.some(s=>s.projectId===p.id))?.id||projects[0].id,image:''}])}><Plus size={15}/>Add slide</button>{picker!==null&&<div className="hero-library-picker"><div><h4>Choose an image</h4><button onClick={()=>setPicker(null)}>Close</button></div><input aria-label="Search hero images" placeholder="Search library" value={query} onChange={e=>setQuery(e.target.value)}/><div className="hero-library-results">{media.filter(m=>(m.name+' '+m.folder).toLowerCase().includes(query.toLowerCase())).map(m=><button key={m.id} onClick={()=>{patch(picker,{image:m.url,alt:m.alt||''});setPicker(null);}}><img src={m.url} alt="" loading="lazy"/><span>{m.name}</span></button>)}</div>{!media.length&&<p>No library images loaded. Paste an image URL above or use the project cover.</p>}</div>}</section>;
}
