// Shared by Studio's preview and the server: one rendering for every email.
export const mailTemplates = [
 {id:'letter',name:'Personal letter',tag:'CORRESPONDENCE',title:'A note from Desartly',description:'A considered, personal message.',fields:[]},
 {id:'booking',name:'Session booking',tag:'YOUR CONVERSATION',title:'Your time is reserved.',description:'A confirmed conversation, with all the details.',fields:[['client','Client name'],['date','Date and time'],['meetingUrl','Google Meet link','url']]},
 {id:'mentorship',name:'Mentorship',tag:'MENTORSHIP · 30 MINUTES',title:'Space for your next step.',description:'A focused conversation about your design practice.',fields:[['client','Client name'],['date','Date and time'],['meetingUrl','Google Meet link','url'],['topic','Conversation focus']]},
 {id:'kickoff',name:'Project kickoff',tag:'A NEW CHAPTER',title:'Good things start here.',description:'Welcome your client and set the next step.',fields:[['client','Client name'],['project','Project name'],['nextStep','Next step'],['date','Kickoff date']]},
 {id:'completion',name:'Project completion',tag:'MADE TOGETHER',title:'From an idea to something real.',description:'Celebrate the work and share the final handover.',fields:[['client','Client name'],['project','Project name'],['deliveryUrl','Handover link','url'],['nextStep','Handover notes']]},
 {id:'proposal',name:'Project proposal',tag:'A PROPOSAL FOR YOU',title:'A direction worth exploring.',description:'Present a clear scope, timeline and investment.',fields:[['client','Client name'],['project','Project name'],['scope','Scope of work'],['timeline','Timeline'],['investment','Investment'],['proposalUrl','Proposal link','url']]},
];
export const escapeMail=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeMailUrl(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}}
export function mailDesignHtml(message,template='letter',fields={}){
 const t=mailTemplates.find(t=>t.id===template)||mailTemplates[0];
 const rows=t.fields.filter(([key,,type])=>fields[key]&&type!=='url').map(([key,label])=>`<tr><td style="padding:12px 0;border-bottom:1px solid #e5e7ee;font-size:12px;color:#697182;width:34%;vertical-align:top">${escapeMail(label)}</td><td dir="auto" style="padding:12px 0;border-bottom:1px solid #e5e7ee;font-size:14px;line-height:1.6">${escapeMail(fields[key])}</td></tr>`).join('');
 const links=t.fields.filter(([key,,type])=>type==='url'&&safeMailUrl(fields[key])).map(([key,label])=>`<a href="${escapeMail(safeMailUrl(fields[key]))}" style="display:inline-block;background:#272c38;color:white;padding:14px 22px;text-decoration:none;border-radius:6px;font-size:13px;margin:20px 8px 0 0">${escapeMail(label)} ↗</a>`).join('');
 return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"></head><body style="margin:0;background:#f3f4f8;color:#242936;font-family:Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:32px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;margin:auto;background:white;border:1px solid #e1e4eb;border-radius:12px;overflow:hidden"><tr><td style="padding:28px 30px;border-bottom:1px solid #e5e7ee"><img src="https://www.desartly.info/email/desartly-avatar.png" width="36" height="36" alt="Desartly" style="vertical-align:middle;border-radius:9px;margin-right:12px"><a href="https://www.desartly.info" style="font-size:24px;font-weight:bold;color:#242936;text-decoration:none;vertical-align:middle">Desartly®</a><p style="font-size:10px;letter-spacing:1.6px;color:#697182;margin:16px 0 0">ALI KOMEILI · INDEPENDENT DESIGN PRACTICE</p></td></tr><tr><td style="padding:36px 30px 28px"><p style="font-size:10px;letter-spacing:2px;color:#7958b6;margin:0 0 16px">${t.tag}</p><h1 style="font-size:32px;line-height:1.2;letter-spacing:-1px;font-weight:500;margin:0 0 24px">${t.title}</h1><div dir="auto" style="white-space:pre-wrap;overflow-wrap:anywhere;font-size:15px;line-height:1.9">${escapeMail(message)}</div>${rows?`<table role="presentation" width="100%" cellspacing="0" style="margin-top:24px">${rows}</table>`:''}${links}</td></tr><tr><td style="padding:24px 30px;background:#f9f9fc;border-top:1px solid #e5e7ee;color:#697182;font-size:12px;line-height:1.8"><strong style="color:#242936">Ali Komeili</strong><br>Independent multidisciplinary designer<br><a href="https://www.desartly.info" style="color:#242936">desartly.info</a> &nbsp;·&nbsp; <a href="https://book.desartly.info" style="color:#242936">Book a conversation ↗</a></td></tr></table><p style="text-align:center;font-size:10px;color:#88909e;letter-spacing:1px">THOUGHTFUL DESIGN. MEANINGFUL CONVERSATIONS.</p></td></tr></table></body></html>`;
}
export function mailDesignText(message,template,fields={}){const t=mailTemplates.find(t=>t.id===template)||mailTemplates[0];return message+'\n\n'+t.fields.filter(([key])=>fields[key]).map(([key,label])=>label+': '+fields[key]).join('\n');}
