import React from 'react';
import { ProjectTagsEditor } from './ProjectTagsEditor.jsx';
import { ClientProfile } from './ClientProfile.jsx';
import {optimizeImage} from './data.js';
const structures={
 'Product & AI':['The challenge','My role & constraints','Understanding the workflow','A key design decision','The experience','Outcome & lessons'],
 Branding:['The brand challenge','Audience & positioning','The central idea','A key design decision','The identity system','Applications & lessons'],
 Advertising:['The communication challenge','Audience & message','The campaign idea','A key design decision','Channels & executions','Outcome & lessons']
};
export function caseTemplate(category){return (structures[category]||structures['Product & AI']).flatMap((title,i)=>[{id:crypto.randomUUID(),type:'text',title,text:''},...([3,4].includes(i)?[{id:crypto.randomUUID(),type:'grid',preset:i===3?1:5,images:[]}]:[])]);}
export const agentDemo=`<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px/1.7 system-ui;margin:0;padding:30px;color:#202632;background:#f7f8fc}small{color:#656d7b}button{padding:12px 16px;margin:5px;border:1px solid #d9ddeb;background:white;cursor:pointer}article{padding:20px;background:white;margin-top:20px;border-left:3px solid #3475ef}h1{font-size:28px;line-height:1.3}</style><small>INTERACTION CONCEPT · SIMULATED OUTPUT</small><h1>A research assistant you can steer.</h1><p>Choose an example brief to explore the workflow. No model or private data is used.</p><button onclick="show(0)">Compare onboarding flows</button><button onclick="show(1)">Group interview notes</button><button onclick="show(2)">Plan a usability study</button><article id="result" aria-live="polite">Choose a brief to see a sample plan.</article><script>const plans=['Define the audience → compare entry points → identify friction → review recommendations.','Remove identifying details → group observations → check exceptions → approve themes.','Clarify the research question → draft tasks → review participant criteria → approve the plan.'];function show(i){document.getElementById('result').textContent=plans[i]+' You review the plan before anything is executed.'}</script></html>`;
export function CaseFields({project,onChange}){async function chooseClientLogo(event){const file=event.target.files?.[0];if(file)onChange({clientLogo:await optimizeImage(file,{purpose:'cover',aspect:1})});}return <section className="case-fields" data-editor-ui><div><h2>Project essentials</h2><p>Give visitors a useful 30-second overview. Empty fields stay hidden.</p></div><div className="case-field-grid"><ProjectTagsEditor project={project} onChange={onChange}/><label>Project year<input type="number" min="1900" max="2100" step="1" value={project.year||''} placeholder="YYYY" onChange={e=>onChange({year:e.target.value})}/></label><label>Client name<input value={project.clientName||''} placeholder={project.title||'Client name'} onChange={e=>onChange({clientName:e.target.value})}/></label>{[['challenge','The problem'],['role','Your role'],['deliverables','Deliverables'],['outcome','Outcome / evidence'],['credits','Collaborators / credits'],['clientDescription','Client profile']].map(([key,label])=><label key={key}>{label}<textarea rows={2} value={project[key]||''} onChange={e=>onChange({[key]:e.target.value})}/></label>)}<label>Project status<select value={project.sample===false?'real':'concept'} onChange={e=>onChange({sample:e.target.value!=='real'})}><option value="concept">Concept / self-initiated study</option><option value="real">Real project</option></select></label><label>Related journal article ID<input value={project.relatedNote||''} placeholder="Article slug (optional)" onChange={e=>onChange({relatedNote:e.target.value})}/></label></div><div className="client-logo-field"><div>{project.clientLogo?<img src={project.clientLogo} alt="Client logo preview"/>:<span>No logo</span>}</div><label>Client logo · square card<input type="file" accept="image/*" onChange={chooseClientLogo}/><small>600 × 600 px. Appears only in the compact client card.</small></label>{project.clientLogo&&<button onClick={()=>onChange({clientLogo:''})}>Remove</button>}</div><div className="case-template-actions"><button onClick={()=>onChange({blocks:[...project.blocks,...caseTemplate(project.category)]})}>+ Add {project.category} case-study structure</button><button onClick={()=>onChange({blocks:[...project.blocks,{id:crypto.randomUUID(),type:'text',title:'A key design decision',text:'Option A:\n\nOption B:\n\nWhy I chose this direction:\n\nThe trade-off:'}]})}>+ Design decision</button>{project.category==='Product & AI'&&<button onClick={()=>onChange({blocks:[...project.blocks,{id:crypto.randomUUID(),type:'html',title:'Guided agent concept',html:agentDemo}]})}>+ Guided interaction demo</button>}</div><small>Templates append sections without replacing your existing work. Only add outcomes you can support.</small></section>}
export function CaseBrief({project,withCover=false}){const rows=[['Year',String(project.year||'')],['Challenge',project.challenge],['My role',project.role],['Deliverables',project.deliverables],['Outcome',project.outcome],['Credits',project.credits]].filter(([,v])=>v?.trim());const image=project.heroImage||project.coverImage;const hasClient=Boolean(project.clientName?.trim()||(project.clientLogo&&project.title));if(!rows.length&&!hasClient&&!image)return null;return <section className={'project-overview'+(withCover&&image?' has-cover':'')+(hasClient?' has-client':'')} aria-label="Project at a glance">{withCover&&image&&<figure className="project-overview-cover"><img src={image} alt={`${project.title} project cover`} loading="eager" decoding="async"/></figure>}<div className="project-overview-copy"><div className="case-brief-data"><span className="eyebrow">AT A GLANCE</span>{rows.length>0&&<dl>{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}</div></div>{hasClient&&<ClientProfile project={project}/>}</section>}
